### ISSUE TITLE
Suave template server crashing error

### ISSUE THREAD

**Issue by spaasis** [ionide/ionide-vscode-fsharp#1080]
**Describe the bug**
With a clean install of VSCode and Ionide, a Suave template project throws an unhandled exception. 

**To Reproduce**
Steps to reproduce the behaviour:
1. F# New Project
2. Select the Suave project type
3. Start creating the project
4. See the error at F# Language Service (server) output
5. Bonus, maybe related: no intellisense or other language features

**Expected behaviour**
No errors. everything should just work

**Output**
```
Running: /usr/bin/dotnet /home/usr/.vscode-oss/extensions/ionide.ionide-fsharp-3.35.0/bin_netcore/fsautocomplete.dll --mode http --port 8857 --hostPID=9036
Server crashing error - Object reference not set to an instance of an object. 
    at System.Globalization.CalendarData.NormalizeDatePattern(String input)
   at System.Globalization.CalendarData.LoadCalendarDataFromSystem(String localeName, CalendarId calendarId)
   at System.Globalization.CalendarData..ctor(String localeName, CalendarId calendarId, Boolean bUseUserOverrides)
   at System.Globalization.CultureData.GetCalendar(CalendarId calendarId)
   at System.Globalization.CultureData.DateSeparator(CalendarId calendarId)
   at System.Globalization.DateTimeFormatInfo.InitializeOverridableProperties(CultureData cultureData, CalendarId calendarId)
   at System.Globalization.CultureInfo.get_DateTimeFormat()
   at System.DateTimeFormat.Format(DateTime dateTime, String format, IFormatProvider provider, TimeSpan offset)
   at System.DateTimeFormat.Format(DateTime dateTime, String format, IFormatProvider provider)
   at Suave.Logging.Formatting.formatLocalTime@564(LiterateOptions options, Int64 utcTicks)
   at Suave.Logging.Formatting.literateDefaultTokeniser(LiterateOptions options, Message message)
   at Suave.Logging.LiterateConsoleTarget.colouriseThenNewLine(Message message)
   at Suave.Logging.LiterateConsoleTarget.Suave-Logging-Logger-log(LogLevel level, FSharpFunc`2 msgFactory)
   at FsAutoComplete.Suave.start(Commands commands, ParseResults`1 args) in D:\Programowanie\ionide\paket-files\github.com\fsharp\FsAutoComplete\src\FsAutoComplete\FsAutoComplete.Suave.fs:line 255
   at FsAutoComplete.Program.entry(String[] args) in D:\Programowanie\ionide\paket-files\github.com\fsharp\FsAutoComplete\src\FsAutoComplete\Program.fs:line 43
```

**Environment (please complete the following information):**
 - OS: Linux x64 5.0.8-arch1-1-ARCH
 - Ionide version: 3.35.0
 - VSCode version: 1.33.1
 - dotnet SDK version: 2.2.105
 - mono / .Net Framework version: 5.20.1

**Additional context**
The language features issue might not be relevant here, since they don't work with other project types either

**Comment by spaasis** [comment]
Hmm, seems this was all a configuration error on my end. When I didn't set FSAC to dotnetcore the project started to load. Then I implemented this fix https://github.com/ionide/ionide-vscode-fsharp/issues/1001#issuecomment-460099633 to get rid of the framework error and now everything seems to work.

I'll dig into why FSAC doesn't work with the dotnetcore option.
Would there be issues in adding the `netfx.props` file to the template by default?
