### ISSUE TITLE
Ionide FSAC process crash on startup

### ISSUE THREAD

**Issue by MangelMaxime** [ionide/ionide-vscode-fsharp#1088]
**Describe the bug**

It seems that Ionide 3.36.0 is broken for me. When Ionide is starting FSAC it's sending it a `CompilerLocation` request but FSAC crash when serializing it.

**To Reproduce**
Steps to reproduce the behaviour:

1. Open any project using Ionide 3.36.0 (under Mac OS X?)
2. Go to `Output` console
3. Choose `F# Language Service` or `F# Language Service (server)`
4. See that the server replied an error 500

Here are the logs I am getting:

**F# Language Service (server) logs**
```
Running: mono /Users/maximemangel/.vscode/extensions/ionide.ionide-fsharp-3.36.0/bin/fsautocomplete.exe --mode http --port 8550 --hostPID=62395
[15:33:20 INF] tracking host PID 62395
Resolving startup promise because FSAC printed the 'listener started' message
[15:33:20 INF] Smooth! Suave listener started in 42,778ms with binding 127.0.0.1:8550
[15:33:20 ERR] request failed
System.Runtime.Serialization.SerializationException: Type 'FsAutoComplete.CoreResponse+CompilerLocation' with data contract name 'CoreResponse.CompilerLocation:http://schemas.datacontract.org/2004/07/FsAutoComplete' is not expected. Add any types not known statically to the list of known types - for example, by using the KnownTypeAttribute attribute or by adding them to the list of known types passed to DataContractSerializer.
  at System.Runtime.Serialization.Json.JsonFormatWriterInterpreter.InternalSerialize (System.Reflection.MethodInfo methodInfo, System.Func`1[TResult] memberValue, System.Type memberType, System.Boolean writeXsiType) [0x0008d] in <6e0d89180eb54b1da79d034d07f7fe42>:0 
  at System.Runtime.Serialization.Json.JsonFormatWriterInterpreter.WriteValue (System.Type memberType, System.Object memberValue) [0x00219] in <6e0d89180eb54b1da79d034d07f7fe42>:0 
  at System.Runtime.Serialization.Json.JsonFormatWriterInterpreter.WriteCollection (System.Runtime.Serialization.CollectionDataContract collectionContract) [0x000dc] in <6e0d89180eb54b1da79d034d07f7fe42>:0 
  at System.Runtime.Serialization.Json.JsonFormatWriterInterpreter.WriteCollectionToJson (System.Runtime.Serialization.XmlWriterDelegator xmlWriter, System.Object obj, System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson context, System.Runtime.Serialization.CollectionDataContract dataContract) [0x0004c] in <6e0d89180eb54b1da79d034d07f7fe42>:0 
  at System.Runtime.Serialization.Json.JsonFormatWriterGenerator+CriticalHelper+<>c__DisplayClass1_0.<GenerateCollectionWriter>b__0 (System.Runtime.Serialization.XmlWriterDelegator xmlWriter, System.Object obj, System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson context, System.Runtime.Serialization.CollectionDataContract dataContract) [0x0000b] in <6e0d89180eb54b1da79d034d07f7fe42>:0 
  at System.Runtime.Serialization.Json.JsonCollectionDataContract.WriteJsonValueCore (System.Runtime.Serialization.XmlWriterDelegator jsonWriter, System.Object obj, System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson context, System.RuntimeTypeHandle declaredTypeHandle) [0x00016] in <6e0d89180eb54b1da79d034d07f7fe42>:0 
  at System.Runtime.Serialization.Json.JsonDataContract.WriteJsonValue (System.Runtime.Serialization.XmlWriterDelegator jsonWriter, System.Object obj, System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson context, System.RuntimeTypeHandle declaredTypeHandle) [0x00007] in <6e0d89180eb54b1da79d034d07f7fe42>:0 
  at System.Runtime.Serialization.Json.DataContractJsonSerializer.WriteJsonValue (System.Runtime.Serialization.Json.JsonDataContract contract, System.Runtime.Serialization.XmlWriterDelegator writer, System.Object graph, System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson context, System.RuntimeTypeHandle declaredTypeHandle) [0x00000] in <6e0d89180eb54b1da79d034d07f7fe42>:0 
  at System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.WriteDataContractValue (System.Runtime.Serialization.DataContract dataContract, System.Runtime.Serialization.XmlWriterDelegator xmlWriter, System.Object obj, System.RuntimeTypeHandle declaredTypeHandle) [0x00034] in <6e0d89180eb54b1da79d034d07f7fe42>:0 
  at System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeWithoutXsiType (System.Runtime.Serialization.DataContract dataContract, System.Runtime.Serialization.XmlWriterDelegator xmlWriter, System.Object obj, System.RuntimeTypeHandle declaredTypeHandle) [0x0003c] in <6e0d89180eb54b1da79d034d07f7fe42>:0 
  at System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalWriteObjectContent (System.Runtime.Serialization.XmlWriterDelegator writer, System.Object graph) [0x0009a] in <6e0d89180eb54b1da79d034d07f7fe42>:0 
  at System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalWriteObject (System.Runtime.Serialization.XmlWriterDelegator writer, System.Object graph) [0x00008] in <6e0d89180eb54b1da79d034d07f7fe42>:0 
  at System.Runtime.Serialization.XmlObjectSerializer.InternalWriteObject (System.Runtime.Serialization.XmlWriterDelegator writer, System.Object graph, System.Runtime.Serialization.DataContractResolver dataContractResolver) [0x00000] in <6e0d89180eb54b1da79d034d07f7fe42>:0 
  at System.Runtime.Serialization.XmlObjectSerializer.WriteObjectHandleExceptions (System.Runtime.Serialization.XmlWriterDelegator writer, System.Object graph, System.Runtime.Serialization.DataContractResolver dataContractResolver) [0x00073] in <6e0d89180eb54b1da79d034d07f7fe42>:0 
  at System.Runtime.Serialization.XmlObjectSerializer.WriteObjectHandleExceptions (System.Runtime.Serialization.XmlWriterDelegator writer, System.Object graph) [0x00000] in <6e0d89180eb54b1da79d034d07f7fe42>:0 
  at System.Runtime.Serialization.Json.DataContractJsonSerializer.WriteObject (System.Xml.XmlDictionaryWriter writer, System.Object graph) [0x0000d] in <6e0d89180eb54b1da79d034d07f7fe42>:0 
  at System.Runtime.Serialization.Json.DataContractJsonSerializer.WriteObject (System.IO.Stream stream, System.Object graph) [0x00018] in <6e0d89180eb54b1da79d034d07f7fe42>:0 
  at Suave.Json.toJson[T] (T o) [0x0001b] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at FsAutoComplete.Suave+app@197-69.Invoke (Microsoft.FSharp.Core.Unit unitVar) [0x00015] in <5cd0125896d80ea9a74503835812d05c>:0 
  at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult] (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt, TResult result1, Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] part2) [0x00005] in <5c64a986dff9fae1a745038386a9645c>:0 
  at Suave.Filters+path@304-1.Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at Suave.WebPart+bind@25-9[b].Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at Suave.Filters+path@304-1.Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at Suave.WebPart+bind@25-9[b].Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at Suave.Filters+path@304-1.Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at Suave.WebPart+bind@25-9[b].Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at Suave.Filters+path@304-1.Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at Suave.WebPart+bind@25-9[b].Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at Suave.Filters+path@304-1.Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at Suave.WebPart+bind@25-9[b].Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at Suave.Filters+path@304-1.Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at Suave.WebPart+bind@25-9[b].Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at Suave.Filters+path@304-1.Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at Suave.WebPart+bind@25-9[b].Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at Suave.Filters+path@304-1.Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at Suave.WebPart+bind@25-9[b].Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at Suave.Filters+path@304-1.Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at Suave.WebPart+bind@25-9[b].Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at Suave.Filters+path@304-1.Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at Suave.WebPart+bind@25-9[b].Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at Suave.Filters+path@304-1.Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at Suave.WebPart+bind@25-9[b].Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at Suave.Filters+path@304-1.Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at Suave.WebPart+bind@25-9[b].Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at Suave.Filters+path@304-1.Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at Suave.WebPart+bind@25-9[b].Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at Suave.Filters+path@304-1.Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at Suave.WebPart+bind@25-9[b].Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at Suave.Filters+path@304-1.Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at Suave.WebPart+bind@25-9[b].Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at Suave.Filters+path@304-1.Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at Suave.WebPart+bind@25-9[b].Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at Suave.Filters+path@304-1.Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at Suave.WebPart+bind@25-9[b].Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at Suave.Filters+path@304-1.Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at Suave.WebPart+bind@25-9[b].Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at Suave.Filters+path@304-1.Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at Suave.WebPart+bind@25-9[b].Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at Suave.Filters+path@304-1.Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at Suave.WebPart+bind@25-9[b].Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at Suave.Filters+path@304-1.Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at Suave.WebPart+bind@25-9[b].Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at Suave.Filters+path@304-1.Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at Suave.WebPart+bind@25-9[b].Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at Suave.Filters+path@304-1.Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at <StartupCode$Suave>.$SocketMonad+Return@9-1[a].Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at <StartupCode$Suave>.$SocketMonad+Return@9-1[a].Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at <StartupCode$Suave>.$SocketMonad+Return@9-1[a].Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at <StartupCode$Suave>.$SocketMonad+Return@9-1[a].Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at <StartupCode$Suave>.$SocketMonad+Return@9-1[a].Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at Suave.Sockets.SocketOpModule+orInputError@46-1[a].Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at <StartupCode$Suave>.$SocketMonad+Return@9-1[a].Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at <StartupCode$Suave>.$SocketMonad+Return@9-1[a].Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at <StartupCode$Suave>.$SocketMonad+Return@9-1[a].Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at <StartupCode$Suave>.$SocketMonad+Return@9-1[a].Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at <StartupCode$Suave>.$SocketMonad+Return@9-1[a].Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at <StartupCode$Suave>.$SocketMonad+Return@9-1[a].Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at <StartupCode$Suave>.$SocketMonad+Return@9-1[a].Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at <StartupCode$Suave>.$SocketMonad+Return@9-1[a].Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at Suave.Sockets.SocketOpModule+orInputError@46-1[a].Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at <StartupCode$Suave>.$SocketMonad+Return@9-1[a].Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at <StartupCode$Suave>.$SocketMonad+Return@9-1[a].Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at <StartupCode$Suave>.$ConnectionFacade+-ctor@141-16.Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at <StartupCode$Suave>.$SocketMonad+Return@9-1[a].Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5be6fbc6043d660ea7450383c6fbe65b>:0 
  at Microsoft.FSharp.Control.Trampoline.Execute (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] firstAction) [0x00020] in <5c64a986dff9fae1a745038386a9645c>:0 
```

**F# Language Service logs**
```
[15:33:19 INFO ] No FSAC url provided, using http://127.0.0.1:8550/
[15:33:19 INFO ] No runtime specified, defaulting to .NET
[15:33:19 INFO ] finding FSAC for
	runtime: Implied (NET)
	mono: mono
	dotnet: /usr/local/share/dotnet/dotnet
[15:33:20 INFO ] listening notification on /notify started
[15:33:20 INFO ] listening notification on /notifyWorkspace started
[15:33:20 INFO ] listening notification on /notifyAnalyzer started
[15:33:20 DEBUG] REQ (001) -> {compilerlocation}
Data=""
[15:33:20 ERROR] RES (001) <- {compilerlocation} ERROR in 248 ms: {stack: Error: Request failed with status code 500
	at createError (/Users/maximemangel/.vscode/extensions/ionide.ionide-fsharp-3.36.0/fsharp.js:14139:15)
	at settle (/Users/maximemangel/.vscode/extensions/ionide.ionide-fsharp-3.36.0/fsharp.js:18704:12)
	at IncomingMessage.handleStreamEnd (/Users/maximemangel/.vscode/extensions/ionide.ionide-fsharp-3.36.0/fsharp.js:28155:11)
	at IncomingMessage.emit (events.js:187:15)
	at endReadableNT (_stream_readable.js:1090:12)
	at process._tickCallback (internal/process/next_tick.js:63:19), message: Request failed with status code 500, config: [object Object], request: [object Object], response: [object Object]} Data=undefined
```

**Expected behaviour**
FSAC should not crash

**Screenshots**

**Environment (please complete the following information):**
 - OS: Mac OS X
 - Ionide version: 3.36.0
 - VSCode version:  1.33.1
 - dotnet SDK version: I can't use donet SDK because the F# compiler is crash due to SO.
 - mono / .Net Framework version: 

```
Mono JIT compiler version 5.16.0.221 (2018-06/b63e5378e38 Mon Nov 19 18:08:09 EST 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           normal
        SIGSEGV:       altstack
        Notification:  kqueue
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        Interpreter:   yes
        LLVM:          yes(3.6.0svn-mono-release_60/0b3cb8ac12c)
        GC:            sgen (concurrent by default)
```

**Additional context**

**Comment by Krzysztof-Cieslak** [comment]
Can reproduce, however, it's not crashing FSAC completely for me - everything else seems to be working.

**Comment by MangelMaxime** [comment]
For me, it is crashing everything...

I am using the experimental version of Ionide for now because this one seems to work.

**Comment by ameier38** [comment]
Mine was crashing when FSAC was set to `net`. Switching to `netcore` fixed it for me. (on Windows)

**Comment by Krzysztof-Cieslak** [comment]
Fix is getting released right now, should be online in couple of minutes

**Comment by MangelMaxime** [comment]
I confirm this is working for me.

Thank you for fast the fix :)
