### ISSUE TITLE
Ionide 4 and FAKE 5 build script

### ISSUE THREAD

**Issue by theimowski** [ionide/ionide-vscode-fsharp#1126]
**Describe the bug**

FAKE 5 build scripts seem to be not parsed by Ionide 4 preview

**To Reproduce**

setup build.fsx script using [groupref](https://fake.build/fake-fake5-modules.html#Declaring-FAKE-5-dependencies-within-the-script) approach

Clearing caches + reloading window didn't help

**Screenshots**

![image](https://user-images.githubusercontent.com/5909015/59346687-266bba00-8d13-11e9-8ebf-845b0fda673d.png)

**Environment (please complete the following information):**
 - OS: MacOS 10.14.5
 - Ionide version: experimental 0.3.0
 - VSCode version: 1.36.0-insider 
 - dotnet SDK version: 3.0.100-preview5-011568
 - mono / .Net Framework version:

**Comment by Krzysztof-Cieslak** [comment]
Fixed in https://github.com/fsharp/FsAutoComplete/pull/406

**Comment by theimowski** [comment]
Still got same issue in ionide-experimental 0.3.1

Following are output logs:

```
[Error - 8:38:12 AM] Request textDocument/codeAction failed.
  Message: System.ArgumentException: The index was outside the range of elements in the list.
Parameter name: n
   at Microsoft.FSharp.Collections.PrivateListHelpers.nth[a](FSharpList`1 l, Int32 n)
   at FsAutoComplete.Lsp.GetInterfaceStubCodeAction@986-2.Invoke(FSharpList`1 _arg32) in D:\Programowanie\Projekty\Ionide\FsAutoComplete\src\FsAutoComplete\FsAutoComplete.Lsp.fs:line 987
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1)
   at FsAutoComplete.Lsp.HandleTypeCheckCodeAction@840-7.Invoke(AsyncActivation`1 ctxt) in D:\Programowanie\Projekty\Ionide\FsAutoComplete\src\FsAutoComplete\FsAutoComplete.Lsp.fs:line 840
   at <StartupCode$FsAutoComplete-Core>.$Commands.TryGetLatestTypeCheckResultsForFile@312-12.Invoke(AsyncActivation`1 ctxt) in D:\Programowanie\Projekty\Ionide\FsAutoComplete\src\FsAutoComplete.Core\Commands.fs:line 312
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
  Code: -32603 
[Error - 8:38:12 AM] Request textDocument/codeAction failed.
  Message: System.ArgumentException: The index was outside the range of elements in the list.
Parameter name: n
   at Microsoft.FSharp.Collections.PrivateListHelpers.nth[a](FSharpList`1 l, Int32 n)
   at FsAutoComplete.Lsp.GetInterfaceStubCodeAction@986-2.Invoke(FSharpList`1 _arg32) in D:\Programowanie\Projekty\Ionide\FsAutoComplete\src\FsAutoComplete\FsAutoComplete.Lsp.fs:line 987
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1)
   at FsAutoComplete.Lsp.HandleTypeCheckCodeAction@840-7.Invoke(AsyncActivation`1 ctxt) in D:\Programowanie\Projekty\Ionide\FsAutoComplete\src\FsAutoComplete\FsAutoComplete.Lsp.fs:line 840
   at <StartupCode$FsAutoComplete-Core>.$Commands.TryGetLatestTypeCheckResultsForFile@312-12.Invoke(AsyncActivation`1 ctxt) in D:\Programowanie\Projekty\Ionide\FsAutoComplete\src\FsAutoComplete.Core\Commands.fs:line 312
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
  Code: -32603 
[Error - 8:38:16 AM] Request textDocument/hover failed.
  Message: Cached typecheck results not yet available
  Code: -32603 
```
