### ISSUE TITLE
Adding this extension to Gitpod results in the following error on startup

### ISSUE THREAD

**Issue by 7sharp9** [ionide/ionide-vscode-fsharp#1198]
**Describe the bug**
Adding this extension to gitpod results in this error and no tooling support, looks like the language server fails to start due to a path issue.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a repo
2. Open Gitpod
3. Add vsix extension
4. Add docker image: `image: gitpod/workspace-dotnet`
5. start workspace

Log:
```
[LSP call] Initialize
[LSP call] Initialized
[LSP call] FSharpWorkspacePeek
[LSP call] WorkspaceDidChangeConfiguration:
 {AutomaticWorkspaceInit = false;
 WorkspaceModePeekDeepLevel = 4;
 ExcludeProjectDirectories =
  [|".git"; "paket-files"; ".fable"; "node_modules"|];
 KeywordsAutocomplete = true;
 ExternalAutocomplete = false;
 Linter = true;
 UnionCaseStubGeneration = true;
 UnionCaseStubGenerationBody = "failwith "Not Implemented"";
 RecordStubGeneration = true;
 RecordStubGenerationBody = "failwith "Not Implemented"";
 InterfaceStubGeneration = true;
 InterfaceStubGenerationObjectIdentifier = "this";
 InterfaceStubGenerationMethodBody = "failwith "Not Implemented"";
 UnusedOpensAnalyzer = true;
 UnusedDeclarationsAnalyzer = true;
 SimplifyNameAnalyzer = true;
 ResolveNamespaces = true;
 EnableReferenceCodeLens = true;
 EnableAnalyzers = false;
 AnalyzersPath = [|"packages/Analyzers"; "analyzers"|];
 DisableInMemoryProjectReferences = false;
 LineLens = {Enabled = "replaceCodeLens";
             Prefix = "  // ";};}
[LSP call] FSharpWorkspaceLoad
[LSP] Notify - Workspace (WorkspaceLoad false)
[LSP] Notify - Workspace (ProjectLoading "/workspace/myriad/src/Myriad/Myriad.fsproj")
[LSP] Notify - Workspace
  (ProjectError
     (ProjectNotRestored "/workspace/myriad/src/Myriad/Myriad.fsproj"))
[LSP] Notify - Workspace
  (ProjectError
     (GenericError
        ("/workspace/myriad/src/Myriad/Myriad.fsproj",
         "Project file '/workspace/myriad/src/Myriad/Myriad.fsproj' parsing failed")))
[LSP] Notify - Workspace (ProjectLoading "/workspace/myriad/src/Example/Example.fsproj")
[LSP] Notify - Workspace
  (ProjectError
     (ProjectNotRestored "/workspace/myriad/src/Example/Example.fsproj"))
[LSP] Notify - Workspace
  (ProjectError
     (GenericError
        ("/workspace/myriad/src/Example/Example.fsproj",
         "Project file '/workspace/myriad/src/Example/Example.fsproj' parsing failed")))
[LSP] Notify - Workspace (WorkspaceLoad true)
[LSP call] TextDocumentDidOpen
[LSP call] TextDocumentCodeAction
[Commands] TryGetLatestTypeCheckResultsForFile - /workspace/myriad/src/Myriad/ast.fs; State - Some 1; Checked - <null>
[LSP call] TextDocumentCodeLens
[FSharpChecker] Current Queue Length: 0
[Checker] GetDeclarations - /workspace/myriad/src/Myriad/ast.fs
[LSP] Notify - Canceled
  (InfoRes
     "Request cancelled (exn was System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Dotnet.ProjInfo.Workspace.Utils.runProcess(FSharpFunc`2 log, String workingDir, String exePath, String args)
   at Dotnet.ProjInfo.Inspect.msbuild[a](MSBuildExePath msbuildExe, FSharpFunc`2 run, String project, FSharpList`1 args)
   at Dotnet.ProjInfo.Inspect.getProjectInfo[a,b,c](FSharpFunc`2 log, FSharpFunc`2 msbuildExec, FSharpFunc`2 getArgs, FSharpList`1 additionalArgs, String projPath)
   at Dotnet.ProjInfo.Workspace.NETFrameworkInfoProvider.getInstalledNETVersions(MSBuildExePath msbuildHost)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Dotnet.ProjInfo.Workspace.NetFWInfo.LatestVersion()
   at <StartupCode$FsAutoComplete-Core>.$CompilerServiceInterface.GetProjectOptionsFromScript@462.Invoke(Unit unitVar) in /Users/chris/Programming/ionide-vscode-fsharp/paket-files/github.com/fsharp/FsAutoComplete/src/FsAutoComplete.Core/CompilerServiceInterface.fs:line 462
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction))")
[FSharpChecker] Current Queue Length: 0
[Checker] TryGetRecentCheckResultsForFile - /workspace/myriad/src/Myriad/ast.fs
[FSharpChecker] Current Queue Length: 0
[Checker] TryGetRecentCheckResultsForFile - /workspace/myriad/src/Myriad/ast.fs
[FSharpChecker] Current Queue Length: 0
[Checker] TryGetRecentCheckResultsForFile - /workspace/myriad/src/Myriad/ast.fs
[FSharpChecker] Current Queue Length: 0
[Checker] TryGetRecentCheckResultsForFile - /workspace/myriad/src/Myriad/ast.fs
[BACKGROUND SERVICE] Msg: File update /workspace/myriad/src/Myriad/ast.fs
[BACKGROUND SERVICE] Msg: Files to check []
[LSP call] TextDocumentHover
[LSP] PositionHandler - Position request: /workspace/myriad/src/Myriad/ast.fs at (25,29)
[FSharpChecker] Current Queue Length: 0
[Checker] TryGetRecentCheckResultsForFile - /workspace/myriad/src/Myriad/ast.fs
[LSP] PositionHandler - Cached typecheck results not yet available
[Error - 11:48:31 AM] Request textDocument/hover failed.
  Message: Cached typecheck results not yet available
  Code: -32603 
```

Im not exactly sure what it can't find...

**Comment by 7sharp9** [comment]
@enricosada Would it be possible to add some diagnostics to the above to see where the msbuild search is failing?   I think thats where this is falling over...

**Comment by 7sharp9** [comment]
@Krzysztof-Cieslak Could a log of why parsing failed be added as part of the verbose logging?

**Comment by Krzysztof-Cieslak** [comment]
This is VSCode's devcontainer dockerfile used in SAFE stack - Ionide is definitely working fine with it.
 https://github.com/SAFE-Stack/SAFE-template/blob/master/Content/.devcontainer/Dockerfile

I'd imagine that something similar would be enough for the GitPod.

**Comment by Krzysztof-Cieslak** [comment]
This is fixed as far as I understand.
