### ISSUE TITLE
Intellisense not working in .fsx files with mono 6.0.0

### ISSUE THREAD

**Issue by ZeekoZhu** [ionide/ionide-vscode-fsharp#1216]
**Describe the bug**
Intellisense doesn't work in `.fsx` files with mono 6.0.0.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create an empty directory `mono6-test`
2. Open the directory with VSCode
3. Create a fsx file `main.fsx` with content `printfn 'hello'`
4. Hover mouse over `printfn`, no intellisense appear
5. Open F# output, see errors

**Expected behaviour**
Intellisense information should show up.

![image](https://user-images.githubusercontent.com/13861843/65016130-083ad900-d956-11e9-8cfc-665757c09415.png)

**Environment:**
 - OS: Linux x64 4.19.69-1-MANJARO 18.1.0
 - Ionide version: both 4.0.6 and 0.3.5
 - VSCode version: 1.37.1
 - dotnet SDK version: 2.2.401
 - mono / .Net Framework version: 6.0.0

**Additional context**
F# output panel shows these error messages:

```
[LSP] Notify - Canceled
  (InfoRes
     "Request cancelled (exn was System.Exception: error getting msbuild info: unexpected MSBuildFailed
  (1,
   ("/tmp/tmpAzDW5s.tmp", "msbuild",
    "/tmp/tmpAzDW5s.tmp/EnvironmentInfo.proj /t:_Inspect_GetProperties /p:_Inspect_GetProperties_OutFile=/tmp/tmpIitP6I.tmp.GetProperties.txt /p:CustomAfterMicrosoftCommonTargets=/tmp/tmp8ANr8Y.tmp.proj-info.hook.targets /nologo /verbosity:quiet"))
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1647.Invoke(String message)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Dotnet.ProjInfo.Workspace.NetFWInfo.LatestVersion()
   at <StartupCode$FsAutoComplete-Core>.$CompilerServiceInterface.GetProjectOptionsFromScript@456.Invoke(Unit unitVar) in D:\Programowanie\Projekty\Ionide\FsAutoComplete\src\FsAutoComplete.Core\CompilerServiceInterface.fs:line 456
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction))")
```

Hover mouse over any symbol, F# output shows

```
[Checker] TryGetRecentCheckResultsForFile - /home/zeeko/Projects/FSAC-mono6.0.0/test.fsx
[LSP] PositionHandler - Cached typecheck results not yet available
[Error - 2:02:21 PM] Request textDocument/hover failed.
  Message: Cached typecheck results not yet available
  Code: -32603 
```

I try to execute the failed msbuild command, and get this error:

```
$ msbuild /tmp/tmpaBaiGF.tmp/EnvironmentInfo.proj /t:_Inspect_GetProperties /p:_Inspect_GetProperties_OutFile=/tmp/tmpVo8xr1.tmp.GetProperties.txt /p:CustomAfterMicrosoftCommonTargets=/tmp/tmpgHYXdn.tmp.proj-info.hook.targets /nologo /verbosity:quiet
/usr/lib/mono/msbuild/15.0/bin/Microsoft.CSharp.CurrentVersion.targets(331,5): error MSB4019: The imported project "/usr/lib/mono/msbuild/15.0/bin/Roslyn/Microsoft.CSharp.Core.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. [/tmp/tmpaBaiGF.tmp/EnvironmentInfo.proj]
```

**Workaround**

Downgrade mono to 5.x

**Comment by ZeekoZhu** [comment]
Install [msbuild-16-bin](https://aur.archlinux.org/packages/msbuild-16-bin/) can fix this problem.
