### ISSUE TITLE
intellisense not working on fsx file

### ISSUE THREAD

**Issue by jackfoxy** [ionide/ionide-vscode-fsharp#1275]
**Describe the bug**
mouseover intellisense not working for fsx file

**To Reproduce**
1.  use https://gist.github.com/jackfoxy/ba315d2190ae563f5a7d40cf72428fcf
2. download gist saving to something.fsx
3. open file
4. hover over anything, and nothing happens (see F# Output)

**Expected behavior**
Expect to see similar pop-up information to Visual Studio, where opening this file and seeing intellisense works.

**F# Output**

```
[Error - 10:43:46 AM] Request textDocument/definition failed.
  Message: Cached typecheck results not yet available
  Code: -32603 
[Error - 10:43:46 AM] Request textDocument/hover failed.
  Message: Cached typecheck results not yet available
  Code: -32603 
[Error - 10:43:47 AM] Request textDocument/definition failed.
  Message: Cached typecheck results not yet available
  Code: -32603 
[Error - 10:43:47 AM] Request textDocument/definition failed.
  Message: Cached typecheck results not yet available
  Code: -32603 
```

**Environment (please complete the following information):**
 - OS: Windows 10 build 18363
 - Ionide version: 4.4.1
 - VSCode version:
Version: 1.41.1 (system setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

 - dotnet SDK version: 3.1.100
 - mono / .Net Framework version: n/a

**Additional context**
Works in Visual Studio 16.4.2

**Comment by Krzysztof-Cieslak** [comment]
If you want to run scripts with only SDK installed have you set `FSharp.useSdkScripts` option to `true`?

**Comment by jackfoxy** [comment]
I just set that setting.
If the file is named something.fsx, and it is the only file open in Code, Ionide does all the syntax colorization and the "FSI: send file" gadget is enabled and works, but still no tooltip pop-ups on hover.

**Comment by baronfel** [comment]
Try closing the file, reloading the window, and then reopening the file.

K, I think this is a timing issue because the default setting is netfx, but then the users setting for useSdkScripts is sent _after the file is open but before typechecking is complete_, so the invalidation that fires doesn't clean out the typecheck results.  This is one reason why I want to move to netcore scripts as the default sooner rather than later.

**Comment by jackfoxy** [comment]
I don't understand what you mean by reloading the window...
I closed file, I closed Code. I reopened Code. I opened file from recent, still no tooltips.

**Comment by baronfel** [comment]
@jackfoxy reload in this case means using the 'reload window' command from the command palette, but that's just a shortcut for the close + reopen procedure you mentioned.

**Comment by jackfoxy** [comment]
Thanks. I learned something. Still not change.

**Comment by Krzysztof-Cieslak** [comment]
Sample gist just works of me without any problems
![image](https://user-images.githubusercontent.com/5427083/72650081-9f08b800-397f-11ea-8e7b-55a7bbc6b917.png)

**Comment by jackfoxy** [comment]
Still no hover-over tools tips for me, now on Ionide 4.4.5.
Maybe I have a conflicting extension installed.

**Comment by nhirschey** [comment]
I have a project where I have the same issue with scripts whenever I try to use netcore fsautocomplete. .fs files work with tooltips, but .fsx files do not.

Ionide only works with scripts when I use the .net fsautocomplete version. (Windows, 3.1 netcore and .net sdk versions).

**Comment by Ellyll** [comment]
This also happens for me on Ubuntu 18.04.4 LTS, netcore 3.1.102, Ionide-fsharp 4.6.3, VSCode 1.42.1.

**Comment by brpratt** [comment]
Does the problem go away if you set `FSharp.dotNetRoot` to the base path indicated by `dotnet --info`? I recently saw a similar problem that was resolved by properly setting this value:

https://github.com/ionide/ionide-vscode-fsharp/issues/1306#issuecomment-602059317

**Comment by jackfoxy** [comment]
@brpratt I see my `FSharp.dotNetRoot `is not set to anything and `dotnet --info` is pointing to the lastest 3.1.101 sdk. 

But retesting on current Ionide shows the problem has gone away, probably in some intervening update. So I am closing.

**Comment by mastoj** [comment]
I'm having the same issue on Windows, did you figure out what the actual problem is? I just switched back to Windows after being on Mac for a couple of years, maybe I regret that soon :). 

Ionide version: 4.10

Output from `dotnet --info`

```
C:\Users\TomasJansson>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.201\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  3.1.201 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

Settings related to fsharp/ionide in vscode:

```
    "FSharp.addFsiWatcher": true,
    "FSharp.infoPanelShowOnStartup": true,
    "FSharp.useSdkScripts": true,
    "FSharp.dotNetRoot": "C:\\Program Files\\dotnet\\sdk\\3.1.201\\"
```

**Comment by jackfoxy** [comment]
@mastoj  I don't use Ionide very much, but when I do it is always on Windows. 
I currently have the 3.1.201 SDK as the most recent, and I retested my test case at the top of this issue, and it still works for me.
 My VS Code is up to date, as is Ionide.

**Comment by mastoj** [comment]
Hm. I guess there is a setting or something I haven’t set then.

**Comment by mastoj** [comment]
Not sure it helps for the issue, but here is the log from the dev tools in code:

```
abstractExtensionService.ts:400 [ms-vscode.powershell-preview]: Command `workbench.action.debug.start` appears multiple times in the `commands` section.
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.fsharp.
Old grammar file: file:///c%3A/Users/TomasJansson/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/extensions/fsharp/syntaxes/fsharp.tmLanguage.json.
New grammar file: file:///c%3A/Users/TomasJansson/.vscode-insiders/extensions/ionide.ionide-fsharp-4.10.0/syntaxes/fsharp.json
register @ TMScopeRegistry.ts:45
s @ TMGrammarFactory.ts:73
_getOrCreateGrammarFactory @ abstractTextMateService.ts:246
async function (async)
_getOrCreateGrammarFactory @ abstractTextMateService.ts:235
(anonymous) @ abstractTextMateService.ts:271
_registerDefinitionIfAvailable @ abstractTextMateService.ts:269
(anonymous) @ abstractTextMateService.ts:151
_handle @ extensionsRegistry.ts:142
acceptUsers @ extensionsRegistry.ts:133
_handleExtensionPoint @ abstractExtensionService.ts:382
_doHandleExtensionPoints @ abstractExtensionService.ts:328
_registerAndHandleExtensions @ extensionService.ts:563
_startLocalExtensionHost @ extensionService.ts:553
_scanAndHandleExtensions @ extensionService.ts:548
async function (async)
_scanAndHandleExtensions @ extensionService.ts:445
_initialize @ abstractExtensionService.ts:102
(anonymous) @ extensionService.ts:143
requestIdleCallback (async)
t.runWhenIdle @ async.ts:722
(anonymous) @ extensionService.ts:142
Promise.then (async)
e @ extensionService.ts:140
_createInstance @ instantiationService.ts:111
_createServiceInstance @ instantiationService.ts:210
_createServiceInstanceWithOwner @ instantiationService.ts:199
_createAndCacheServiceInstance @ instantiationService.ts:188
_getOrCreateServiceInstance @ instantiationService.ts:136
get @ instantiationService.ts:54
initLayout @ layout.ts:251
(anonymous) @ workbench.ts:144
invokeFunction @ instantiationService.ts:61
startup @ workbench.ts:137
open @ desktop.main.ts:123
async function (async)
open @ desktop.main.ts:111
t.main @ desktop.main.ts:343
(anonymous) @ workbench.js:33
Promise.then (async)
(anonymous) @ workbench.js:29
(anonymous) @ bootstrap-window.js:130
t._invokeFactory @ loader.js:1043
t.complete @ loader.js:1053
s._onModuleComplete @ loader.js:1674
s._onModuleComplete @ loader.js:1686
s._resolve @ loader.js:1634
s.defineModule @ loader.js:1281
r @ loader.js:1724
c @ loader.js:794
(anonymous) @ workbench.common.main.ts:127
(anonymous) @ fake:1
t._createAndEvalScript @ loader.js:797
(anonymous) @ loader.js:779
u @ loader.js:892
(anonymous) @ loader.js:897
readFileAfterClose @ internal/fs/read_file_context.js:61
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.groovy.
Old grammar file: file:///c%3A/Users/TomasJansson/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/extensions/groovy/syntaxes/groovy.tmLanguage.json.
New grammar file: file:///c%3A/Users/TomasJansson/.vscode-insiders/extensions/naco-siren.gradle-language-0.2.3/syntaxes/groovy.tmLanguage.json
register @ TMScopeRegistry.ts:45
s @ TMGrammarFactory.ts:73
_getOrCreateGrammarFactory @ abstractTextMateService.ts:246
async function (async)
_getOrCreateGrammarFactory @ abstractTextMateService.ts:235
(anonymous) @ abstractTextMateService.ts:271
_registerDefinitionIfAvailable @ abstractTextMateService.ts:269
(anonymous) @ abstractTextMateService.ts:151
_handle @ extensionsRegistry.ts:142
acceptUsers @ extensionsRegistry.ts:133
_handleExtensionPoint @ abstractExtensionService.ts:382
_doHandleExtensionPoints @ abstractExtensionService.ts:328
_registerAndHandleExtensions @ extensionService.ts:563
_startLocalExtensionHost @ extensionService.ts:553
_scanAndHandleExtensions @ extensionService.ts:548
async function (async)
_scanAndHandleExtensions @ extensionService.ts:445
_initialize @ abstractExtensionService.ts:102
(anonymous) @ extensionService.ts:143
requestIdleCallback (async)
t.runWhenIdle @ async.ts:722
(anonymous) @ extensionService.ts:142
Promise.then (async)
e @ extensionService.ts:140
_createInstance @ instantiationService.ts:111
_createServiceInstance @ instantiationService.ts:210
_createServiceInstanceWithOwner @ instantiationService.ts:199
_createAndCacheServiceInstance @ instantiationService.ts:188
_getOrCreateServiceInstance @ instantiationService.ts:136
get @ instantiationService.ts:54
initLayout @ layout.ts:251
(anonymous) @ workbench.ts:144
invokeFunction @ instantiationService.ts:61
startup @ workbench.ts:137
open @ desktop.main.ts:123
async function (async)
open @ desktop.main.ts:111
t.main @ desktop.main.ts:343
(anonymous) @ workbench.js:33
Promise.then (async)
(anonymous) @ workbench.js:29
(anonymous) @ bootstrap-window.js:130
t._invokeFactory @ loader.js:1043
t.complete @ loader.js:1053
s._onModuleComplete @ loader.js:1674
s._onModuleComplete @ loader.js:1686
s._resolve @ loader.js:1634
s.defineModule @ loader.js:1281
r @ loader.js:1724
c @ loader.js:794
(anonymous) @ workbench.common.main.ts:127
(anonymous) @ fake:1
t._createAndEvalScript @ loader.js:797
(anonymous) @ loader.js:779
u @ loader.js:892
(anonymous) @ loader.js:897
readFileAfterClose @ internal/fs/read_file_context.js:61
console.ts:137 [Extension Host] (node:26424) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead. (at writeOut (internal/process/warning.js:27:3))
t.log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:402
_invokeHandler @ rpcProtocol.ts:387
_receiveRequest @ rpcProtocol.ts:303
_receiveOneMessage @ rpcProtocol.ts:230
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:587
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:587
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:203
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:276
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
console.ts:137 [Extension Host] (node:26424) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead. (at writeOut (internal/process/warning.js:27:3))
t.log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:402
_invokeHandler @ rpcProtocol.ts:387
_receiveRequest @ rpcProtocol.ts:303
_receiveOneMessage @ rpcProtocol.ts:230
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:587
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:587
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:203
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:276
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
console.ts:137 [Extension Host] RUNTIME: UserSpecified (NetcoreFdd), MONO: "mono", DOTNET: "C:\\Program Files\\dotnet\\dotnet.exe" (at c:\Users\TomasJansson\.vscode-insiders\extensions\ionide.ionide-fsharp-4.10.0\fsharp.js:2234:17)
console.ts:137 [Extension Host] FSAC (NETCORE): 'c:\Users\TomasJansson\.vscode-insiders\extensions\ionide.ionide-fsharp-4.10.0/bin_netcore/fsautocomplete.dll' (at c:\Users\TomasJansson\.vscode-insiders\extensions\ionide.ionide-fsharp-4.10.0\fsharp.js:2234:17)
console.ts:137 [Extension Host] [LineLens] Activating (at ConsoleAndOutputChannelLogger.Info (c:\Users\TomasJansson\.vscode-insiders\extensions\ionide.ionide-fsharp-4.10.0\fsharp.js:11583:83))
console.ts:137 [Extension Host] [msbuild] Dotnet CLI (.NET Core) found at C:\Program Files\dotnet\dotnet.exe (at ConsoleAndOutputChannelLogger.Info (c:\Users\TomasJansson\.vscode-insiders\extensions\ionide.ionide-fsharp-4.10.0\fsharp.js:11583:83))
console.ts:137 [Extension Host] [msbuild] MSBuild (.NET) found at c:\Windows\Microsoft.NET\Framework\v4.0.30319\MsBuild.exe (at ConsoleAndOutputChannelLogger.Info (c:\Users\TomasJansson\.vscode-insiders\extensions\ionide.ionide-fsharp-4.10.0\fsharp.js:11583:83))
console.ts:137 [Extension Host] [msbuild] Automatic MSBuild detection (at ConsoleAndOutputChannelLogger.Info (c:\Users\TomasJansson\.vscode-insiders\extensions\ionide.ionide-fsharp-4.10.0\fsharp.js:11583:83))
extensionHost.ts:212 Extension Host
extensionHost.ts:213 [LineLens] Config Changed event[LineLens] Installing[LineLens] Installed[GitIngnore] gitignore path: c:\Users\TomasJansson\Desktop\.gitignore
console.ts:137 [Extension Host] Received message which is neither a response nor a notification message:{    "jsonrpc": "2.0",    "id": 6} (at ConsoleLogger.error (c:\Users\TomasJansson\.vscode-insiders\extensions\ionide.ionide-fsharp-4.10.0\fsharp.js:6037:17))
t.log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:402
_invokeHandler @ rpcProtocol.ts:387
_receiveRequest @ rpcProtocol.ts:303
_receiveOneMessage @ rpcProtocol.ts:230
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:587
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:587
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:203
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:276
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: The received response has neither a result nor an error property. (at c:\Users\TomasJansson\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:956:596)
t.log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:402
_invokeHandler @ rpcProtocol.ts:387
_receiveRequest @ rpcProtocol.ts:303
_receiveOneMessage @ rpcProtocol.ts:230
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:587
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:587
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:203
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:276
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
console.ts:137 [Extension Host] stack trace: Error: The received response has neither a result nor an error property.	at handleInvalidMessage (c:\Users\TomasJansson\.vscode-insiders\extensions\ionide.ionide-fsharp-4.10.0\fsharp.js:9081:40)	at processMessageQueue (c:\Users\TomasJansson\.vscode-insiders\extensions\ionide.ionide-fsharp-4.10.0\fsharp.js:8830:17)	at Immediate.<anonymous> (c:\Users\TomasJansson\.vscode-insiders\extensions\ionide.ionide-fsharp-4.10.0\fsharp.js:8811:13)	at processImmediate (internal/timers.js:439:21) (at c:\Users\TomasJansson\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:956:675)
t.log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:402
_invokeHandler @ rpcProtocol.ts:387
_receiveRequest @ rpcProtocol.ts:303
_receiveOneMessage @ rpcProtocol.ts:230
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:587
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:587
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:203
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:276
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
mainThreadExtensionService.ts:65 [[object Object]]The received response has neither a result nor an error property.
$onExtensionRuntimeError @ mainThreadExtensionService.ts:65
_doInvokeHandler @ rpcProtocol.ts:402
_invokeHandler @ rpcProtocol.ts:387
_receiveRequest @ rpcProtocol.ts:303
_receiveOneMessage @ rpcProtocol.ts:230
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:587
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:587
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:203
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:276
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
mainThreadExtensionService.ts:66 Error: The received response has neither a result nor an error property.
	at handleInvalidMessage (c:\Users\TomasJansson\.vscode-insiders\extensions\ionide.ionide-fsharp-4.10.0\fsharp.js:9081:40)
	at processMessageQueue (c:\Users\TomasJansson\.vscode-insiders\extensions\ionide.ionide-fsharp-4.10.0\fsharp.js:8830:17)
	at Immediate.<anonymous> (c:\Users\TomasJansson\.vscode-insiders\extensions\ionide.ionide-fsharp-4.10.0\fsharp.js:8811:13)
	at processImmediate (internal/timers.js:439:21)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:66
_doInvokeHandler @ rpcProtocol.ts:402
_invokeHandler @ rpcProtocol.ts:387
_receiveRequest @ rpcProtocol.ts:303
_receiveOneMessage @ rpcProtocol.ts:230
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:587
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:587
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:203
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:276
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
```

**Comment by akibmaredia** [comment]
I have the same issue.

Created a file hello.tsx typed in 
``` let a = 10 ``` 
And when tried to hover over a got this message in the  output console.

```
  [Error - 12:02:38 AM] Request textDocument/hover failed.
  Message: Cached typecheck results not yet available
  Code: -32603 
```

**Comment by nhirschey** [comment]
@akibmaredia, no guarantees, but maybe check here? https://github.com/ionide/ionide-vscode-fsharp/issues/1381
