### ISSUE TITLE
Opening project on Ionide corrupts it and stops running

### ISSUE THREAD

**Issue by mixedCase** [ionide/ionide-vscode-fsharp#1293]
**Describe the bug**
Testing Avalonia.FuncUI I discovered that opening a project created from the funcui.full template with Ionide corrupts something in obj that makes it stop running (until I close VSCode, delete obj and run it from terminal).

Running dotnet run before opening the project works fine and the UI appears and performs perfectly. After merely opening the project in VSCode with Ionide this exception appears when trying to run `dotnet run` after opening Ionide:

```
Unhandled exception. System.IO.FileNotFoundException: The resource avares://Test/Styles.xaml could not be found.
   at Avalonia.Shared.PlatformSupport.AssetLoader.OpenAndGetAssembly(Uri uri, Uri baseUri)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Uri uri, Uri baseUri)
   at Avalonia.Markup.Xaml.Styling.StyleInclude.get_Loaded()
   at Avalonia.Markup.Xaml.Styling.StyleInclude.Avalonia.Controls.ISetResourceParent.ParentResourcesChanged(ResourcesChangedEventArgs e)
   at Avalonia.Styling.Styles.<.ctor>b__4_0(IStyle x)
   at Avalonia.Collections.AvaloniaListExtensions.<>c__DisplayClass0_0`1.<ForEachItem>b__0(Int32 _, T i)
   at Avalonia.Collections.AvaloniaListExtensions.<>c__DisplayClass1_0`1.<ForEachItem>g__Add|0(Int32 index, IList items)
   at Avalonia.Collections.AvaloniaListExtensions.<>c__DisplayClass1_0`1.<ForEachItem>b__2(Object _, NotifyCollectionChangedEventArgs e)
   at Avalonia.Collections.AvaloniaList`1.NotifyAdd(T item, Int32 index)
   at Avalonia.Collections.AvaloniaList`1.Add(T item)
   at Avalonia.Styling.Styles.Add(IStyle item)
   at Test.App.Initialize() in /mnt/DataHDD/code/sw/Test/Program.fs:line 31
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at Test.Program.main(String[] args) in /mnt/DataHDD/code/sw/Test/Program.fs:line 43
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Install the templates with `dotnet new --install JaggerJo.Avalonia.FuncUI.Templates`
2. Instantiate a new project with `dotnet new funcui.full -n Test`
3. Update Avalonia.Desktop, since an Avalonia bug in an older version used for the template makes it crash in some distros. Done with `dotnet add package Avalonia.Desktop -v 0.9.2`
4. Exec `dotnet run`, and watch the example app work.
5. Open it in Ionide.
6. Exec `dotnet run` again, it will throw the previously mentioned exception.

**Expected behaviour**
Not touching the obj folder, or at least not corrupting it to the point the project doesn't run anymore.

**Environment (please complete the following information):**
 - OS: Arch Linux
 - Ionide version: 4.5.0
 - VSCode version: 1.41.1
 - dotnet SDK version: 3.1.100
 - mono / .Net Framework version: Mono JIT compiler version 6.4.0

**Additional context**

Before I open the project in Ionide, I copied the project folder to keep a "clean" one for comparison, and running diff -r on obj returns the following changes:

```
$ diff -r obj ../Test2/obj
Binary files obj/Debug/netcoreapp3.0/Avalonia/resources and ../Test2/obj/Debug/netcoreapp3.0/Avalonia/resources differ
Binary files obj/Debug/netcoreapp3.0/Test.assets.cache and ../Test2/obj/Debug/netcoreapp3.0/Test.assets.cache differ
Only in obj: fsac.cache
```

**Comment by baronfel** [comment]
I can't verify this on OSX with SDK 3.1.100, but after working with @mixedCase a bit we have some discoveries:

* The cause of the issue _seems_ to be some path metadata in the [Avalonia Resource Index](https://github.com/AvaloniaUI/Avalonia/blob/9910610573e11a7b91ea9094faad88462f9a2bb9/src/Avalonia.Base/Utilities/AvaloniaResourcesIndex.cs) getting corrupted during a build.  The paths that are generated that work are well-formed, but the poorly formed paths have very deep nesting structures.
* The issue seems to be that the resource index asset is regenerated when ionide does it's diagnostic build. I verified this by having @mixedCase run the manual command line build that I got from running `dotnet proj` on his projects.
* The builds report no changes to the file, yet the `run` command results in this failure at runtime as described above.

The generation target is [here](https://github.com/AvaloniaUI/Avalonia/blob/61340acf4b86e1e9dd5e7e769c6b7438cb9104dd/packages/Avalonia/AvaloniaBuildTasks.targets#L31) and there's not a nice boolean to turn it off.

The code for the task being run is [here](https://github.com/AvaloniaUI/Avalonia/blob/6d8b0ce7d6cab00241d464aa9125d0d28127aaed/src/Avalonia.Build.Tasks/GenerateAvaloniaResourcesTask.cs)

**Comment by mixedCase** [comment]
Reproduction steps have been updated as the bug has been narrowed down a bit.
