### ISSUE TITLE
Send selection on Windows

### ISSUE THREAD

**Issue by falfaddaghi** [ionide/ionide-vscode-fsharp#13]
I get the following error when i try to send to FSI. I did add "C:\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0" to the path variable.

 [E] 2015-11-24T08:58:18.3874669Z: request failed [Suave.Web.defaultErrorHandler] exn:
Microsoft.FSharp.Compiler.ErrorLogger+WrappedError: Exception of type 'Microsoft.FSharp.Compiler.ErrorLogger+WrappedError' was thrown.
   at Microsoft.FSharp.Compiler.Lexhelp.reusingLexbufForParsing[a](LexBuffer`1 lexbuf, FSharpFunc`2 f)
   at Microsoft.FSharp.Compiler.Lexhelp.usingLexbufForParsing[a](LexBuffer`1 lexbuf, String filename, FSharpFunc`2 f)
   at Microsoft.FSharp.Compiler.SourceCodeServices.Parser.ParseOneFile(String source, Boolean matchBracesOnly, Boolean reportErrors, String mainInputFileName, FSharpList`1 projectSourceFiles, TcConfig tcConfig)
   at <StartupCode$FSharp-Compiler-Service>.$Service.ParseAndCheckFileInProject@2470.Invoke(CancellationToken _ct)
   at <StartupCode$FSharp-Compiler-Service>.$Reactor.EnqueueAndAwaitOpAsync@136-2.Invoke(Unit unitVar0)

**Comment by slang25** [comment]
I'm having the exact same issue

**Comment by falfaddaghi** [comment]
@slang25 The problem seemed to fixed after the newest update to VSCode and a restart of my machine.

**Comment by rdoubleui** [comment]
@slang25 Also, the path to Fsi.exe has to be declared within the PATH variable. Otherwise VS Code will give a warning, stating that the send has failed (`Running the contributed command:'fsi.SendSelection' failed.`)
