### ISSUE TITLE
Intellisense only works when "Ctrl + Space" is pressed

### ISSUE THREAD

**Issue by ronaldschlenker** [ionide/ionide-vscode-fsharp#1320]
Given a quite simple FSX with this content:

```fsharp
type Player = { name: string; age: int }

let createPlayer name age = { name = name; age = age }
```

As you can see in the screenshot, the expected IntelliSense content doesn't show up (expected the 'createPlayer' symbol). Instead, I can see an error in the log (complete log is attached):

```
[10:31:51 INF] [LSP] TextDocumentCompletion triggered with {"Value": {"triggerKind": "Invoked", "triggerCharacter": null, "$type": "CompletionContext"}, "$type": "Some"}
[Error - 10:31:51] Request textDocument/completion failed.
  Message: System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at FsAutoComplete.Lsp.TextDocumentCompletion@571.Invoke(Unit unitVar) in D:\Programowanie\ionide\paket-files\github.com\fsharp\FsAutoComplete\src\FsAutoComplete\FsAutoComplete.Lsp.fs:line 584
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 398
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 109
  Code: -32603 
[10:31:51 VRB] [Checker] Current Queue Length is 0
[10:31:51 INF] [Checker] GetDeclarations - c:\temp\IonideTest\someStuff.fsx
```

Now when I press ESC (to close the AutoComplete suggestion popup) and press CTRL+Space (to open it again), I can see the correct symbol in the AutoComplete popup.

I've tried this (in all permutations)

* on 2 machines
* Both net and netcore as FSAC runtime
* enableBackgroundServices with true and false

It doesn't matter wether the scripts are trivial or complex.

Environment:
 - OS: Windows 10 Pro
 - Ionide version: 4.6.3 (but happens also with older versions)
 - VSCode version: 1.42.1 (user setup)
 - dotnet SDK version: see below
 - mono / .Net Framework version: basically every .Net FW until 4.7.2

![2020-03-08_10h32_12](https://user-images.githubusercontent.com/472222/76160327-7e601180-6129-11ea-8c5e-c617a6d63e9c.gif)

![image](https://user-images.githubusercontent.com/472222/76160317-6daf9b80-6129-11ea-8cf8-9ccc9a1e89ca.png)

![image](https://user-images.githubusercontent.com/472222/76160288-2d501d80-6129-11ea-8c1a-bbbf553d4104.png)

[ionideLogs.txt](https://github.com/ionide/ionide-vscode-fsharp/files/4303052/ionideLogs.txt)

**Comment by ronaldschlenker** [comment]
P.S.:
* I looked at #1314 and disabled the analyzers - no effect (issue still occurs).
* I also deleted the .ionide folder: issue still occurs

My fsharp settings:

```
{
    "FSharp.saveOnSendLastSelection": true,
    "FSharp.enableReferenceCodeLens": false,
    "FSharp.msbuildAutoshow": true,
    "FSharp.showExplorerOnStartup": false,
    "FSharp.msbuildHost": ".net",
    "FSharp.smartIndent": true,
    "FSharp.verboseLogging": true,
    "FSharp.enableAnalyzers": false
    // "FSharp.useSdkScripts": true
}
```

AND, please forgive me: My bug seems to be a duplicate of #1289 and #1281

**Comment by ronaldschlenker** [comment]
I'll close in favor of #1289
