### ISSUE TITLE
Formatting Broken

### ISSUE THREAD

**Issue by quicksnap** [ionide/ionide-vscode-fsharp#1324]
**Describe the bug**
Seems that formatting isn't working for me within a basic project.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a basic project via `dotnet new console -lang "F#" -o FirstIonideProject`
2. Try formatting!

**Expected behaviour**
Formating works

**Environment (please complete the following information):**
 - OS: OSX 10.15.3
 - Ionide version: 4.7.0
 - VSCode version: 1.43.0
 - dotnet SDK version: 3.1.102
 - mono / .Net Framework version: Mono JIT compiler version 6.6.0.166 (2019-08/d9001b5ae70 Wed Feb 12 19:20:16 EST 2020)

**Additional context**
Logs from VSCode:

```
[19:31:25 ERR] [Fantomas] Error while parsing the configuration files at /Users/dan/projects/sandbox/FirstIonideProject. Using default configuration
System.Exception: No configuration files were found for /Users/dan/projects/sandbox/FirstIonideProject
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1637.Invoke(String message) in E:\A\_work\130\s\src\fsharp\FSharp.Core\printf.fs:line 1637
   at Fantomas.CodeFormatterImpl.readConfiguration(String fileOrFolder)
[Error - 7:31:25 PM] Request textDocument/formatting failed.
  Message: Fantomas.FormatConfig+FormatException: Parsing failed with errors: [|/Users/dan/projects/sandbox/FirstIonideProject/Program.fs (3,1)-(4,1) parse error Files in libraries or multiple-file applications must begin with a namespace or module declaration, e.g. 'namespace SomeNamespace.SubNamespace' or 'module SomeNamespace.SomeModule'. Only the last source file of an application may omit such a declaration.|]
And options: { SourceFiles =
               [|"/Users/dan/projects/sandbox/FirstIonideProject/obj/Debug/netcoreapp3.1/FirstIonideProject.AssemblyInfo.fs";
                 "/Users/dan/projects/sandbox/FirstIonideProject/Program.fs"|]
  ConditionalCompilationDefines = []
  ErrorSeverityOptions = { WarnLevel = 3
                           GlobalWarnAsError = false
                           WarnOff = []
                           WarnOn = []
                           WarnAsError = []
                           WarnAsWarn = [] }
  IsInteractive = false
  LightSyntax = None
  CompilingFsLib = false
  IsExe = false }
   at Fantomas.CodeFormatterImpl.parse@61-2.Invoke(FSharpParseFileResults _arg2)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 417
   at <StartupCode$FSharp-Compiler-Service>.$Service.ParseFile@418-4.Invoke(AsyncActivation`1 ctxt)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 109
  Code: -32603
 ```

**Comment by quicksnap** [comment]
I'm not sure if this warrants closing the ticket, but having the first line of my program be `module Main` seems to get it working!

Seems bad that this could snag newbies like myself, though.

**Comment by seangwright** [comment]
@quicksnap I was experiencing the same issue...

Having the file start with `module Main` at least got the formatting working.

However, VS Code is throwing errors constantly in the developer tools console:

```
Error: Cannot find ident
	at handleResponse (c:\Users\sean\.vscode\extensions\ionide.ionide-fsharp-4.7.0\fsharp.js:5412:48)
	at processMessageQueue (c:\Users\sean\.vscode\extensions\ionide.ionide-fsharp-4.7.0\fsharp.js:5239:17)
	at Immediate.<anonymous> (c:\Users\sean\.vscode\extensions\ionide.ionide-fsharp-4.7.0\fsharp.js:5223:13)
	at processImmediate (internal/timers.js:439:21)
```

This error is displayed 8 times if I save an `.fs` file.

In addition to this error, there is another that appears whenever I save my `/.vscode/settings.json` file:

```
TypeError: Cannot read property 'subscriptions' of undefined
	at setLanguageConfiguration (c:\Users\sean\.vscode\extensions\ionide.ionide-fsharp-4.7.0\fsharp.js:37314:13)
	at Object.onDidChangeConfiguration (c:\Users\sean\.vscode\extensions\ionide.ionide-fsharp-4.7.0\fsharp.js:37318:5)
	at l.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:865)
	at w.$acceptConfigurationChanged (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:711:811)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:711:69
```

And finally, when switching back to a `.fs` file from another file type (ex: `.fsproj`), I see this error immediately (just by focusing the file):

```
Error: Cached typecheck results not yet available
	at handleResponse (c:\Users\sean\.vscode\extensions\ionide.ionide-fsharp-4.7.0\fsharp.js:5412:48)
	at processMessageQueue (c:\Users\sean\.vscode\extensions\ionide.ionide-fsharp-4.7.0\fsharp.js:5239:17)
	at Immediate.<anonymous> (c:\Users\sean\.vscode\extensions\ionide.ionide-fsharp-4.7.0\fsharp.js:5223:13)
	at processImmediate (internal/timers.js:439:21)
```

**Comment by Krzysztof-Cieslak** [comment]
@quicksnap - can you please report the error in the Fantomas (F# formatter) repo - https://github.com/fsprojects/fantomas.

Thanks.

**Comment by Krzysztof-Cieslak** [comment]
Closing as this an issue of the dependency, we can't fix it here.
