### ISSUE TITLE
Moving source file removes project properties

### ISSUE THREAD

**Issue by vilinski** [ionide/ionide-vscode-fsharp#1363]
**Describe the bug**
Using arrows in F# project view results in removed project properties

**To Reproduce**
Steps to reproduce the behaviour:
1. `dotnet new project -lang f#`
2. Add following to project file:
4. Add more than one source file
3. Go to `F#` view and use down or up arrows to change project file order
4. See the difference in the `PropertyGroup` node:

```diff
-- <Project Sdk="Microsoft.NET.Sdk">
++ <Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
      <OutputType>Exe</OutputType>
      <TargetFramework>netcoreapp3.1</TargetFramework>
--    <GenerateProgramFile>false</GenerateProgramFile>
--    <ServerGarbageCollection>true</ServerGarbageCollection>
--    <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
  </PropertyGroup>
++  <ItemGroup>
++    <ProjectReference Include="..\..\src\OtherProject\OtherProject.fsproj" />
++  </ItemGroup>
  <ItemGroup>
--    <Compile Include="SourceFileOne.fs" />
    <Compile Include="SourceFileTwo.fs" />
++    <Compile Include="SourceFileOne.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>
--  <ItemGroup>
--    <ProjectReference Include="..\..\src\OtherProject\OtherProject.fsproj" />
--  </ItemGroup>
    <Import Project="..\..\.paket\Paket.Restore.targets" />
  </Project>
```

Source file is moved correctly. But nodes `GenerateProgramFile`, `ServerGarbageCollection`, `ConcurrentGarbageCollection` are deleted, which changes the project behavior.
ProjectReference placement is surely not important. Added to diff anyway for completeness.

**Expected behaviour**
No other changes than the order of source files

**Environment (please complete the following information):**
 - OS: macOs catalina
 - Ionide version: 4.11.0
 - VSCode version: 1.45.0
 - dotnet SDK version: 3.1.201
 - mono / .Net Framework version: none

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed with 5.0

**Comment by vilinski** [comment]
Now getting an error with ionide 5.0 using reorder arrows.
Upgraded from preview 03 to 5.0, did "F#: Clear project cache" and "Reload Window":

```
Error running command fsharp.explorer.moveUp: System.NullReferenceException: Object reference not set to an instance of an object.
   at FsAutoComplete.FsProjEditor.moveFileUp(String fsprojPath, String file) in D:\Programowanie\ionide\paket-files\github.com\fsharp\FsAutoComplete\src\FsAutoComplete.Core\FsprojEdit.fs:line 11
   at <StartupCode$FsAutoComplete-Core>.$Commands.FsProjMoveFileUp@363.Invoke(Unit unitVar) in D:\Programowanie\ionide\paket-files\github.com\fsharp\FsAutoComplete\src\FsAutoComplete.Core\Commands.fs:line 363
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 386
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 104. This is likely caused by the extension that contributes fsharp.explorer.moveUp.
```

**Comment by Krzysztof-Cieslak** [comment]
Can you open a new issue, please?

**Comment by vilinski** [comment]
yep, will do
