### ISSUE TITLE
Cache seems to get out of sync quickly

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fsharp#1365]
Since the last releases, I have noticed that the type cache seems to quickly get out of sync, especially when changing branches. Code will appear correct in the editor but will not compile, or vice versa. I have to remove the cache and completely restart VSCode before it fixes itself.

**Comment by Krzysztof-Cieslak** [comment]
That's not really actionable error report 🙃

**Comment by nirvinm** [comment]
I'm also having similar issue from the last release. Ionide stops working after a while. No error checking or intellisense available. I have to restart VSCode to make it work again. Also noted that this error logs appears in the F# output console around the time it stops working.

    [Error - 8:48:48 pm] Request textDocument/completion failed.
    Message: System.ArgumentOutOfRangeException: Index and length must refer to a location within the string. (Parameter 'length')
    at System.String.Substring(Int32 startIndex, Int32 length)
    at FsAutoComplete.Lsp.TextDocumentCompletion@627.Invoke(Unit unitVar) in D:\Programowanie\ionide\paket-files\github.com\fsharp\FsAutoComplete\src\FsAutoComplete\FsAutoComplete.Lsp.fs:line 640
    at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 398
    at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 109
    Code: -32603 
    [20:48:49.271 WRN] [LSP] ParseFile - Workspace not ready
    [20:48:50.071 WRN] [LSP] ParseFile - Workspace not ready
    [20:48:51.497 WRN] [LSP] ParseFile - Workspace not ready
    [20:48:53.394 WRN] [LSP] ParseFile - Workspace not ready
    [20:48:54.470 WRN] [LSP] ParseFile - Workspace not ready
    [20:48:56.256 WRN] [LSP] ParseFile - Workspace not ready
    [20:48:57.506 WRN] [LSP] ParseFile - Workspace not ready

**Comment by Krzysztof-Cieslak** [comment]
This is not an actionable problem report, and a lot of things have changed regarding handling project files in the 5.0 version, so I'm closing this one.

In case of any problems, please create an issue with specific descriptions and reproductions.
