### ISSUE TITLE
Selecting F# as "Language Mode" does not start autocomplete

### ISSUE THREAD

**Issue by jbeeko** [ionide/ionide-vscode-fsharp#1375]
**Describe the bug**
After creating a new file in VSCode and selecting F# as the language mode the code is colonized but AutoComplete, tool-tips etc are not working. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a new file with "Command-N
2. Set language mode to F#
3. Type in `let foo = 4'

Notice that while the code is colonized as soon as F# mode is select no other editor support lights up. 

**Expected behaviour**
The code should be colonized AND tool-tips, line lens, IntelliSense etc should be active.

**Screenshots**
Get this 
<img width="225" alt="image" src="https://user-images.githubusercontent.com/4968704/83808966-810bcd80-a66a-11ea-8a53-211e90e53024.png">

But expect this: 
<img width="170" alt="image" src="https://user-images.githubusercontent.com/4968704/83809021-9bde4200-a66a-11ea-8fbd-782debad3f86.png">

**Environment (please complete the following information):**
 - OS: OSX
 - Ionide version: 4.11.1
 - VSCode version: 1.45.1
 - dotnet SDK version: 5.0 preview 4
 - mono / .Net Framework version: N/A

**Additional context**
The F# output shows exceptions the first two of which appear as soon as `let` is typed. 

```
[Error - 1:54:38 PM] Request textDocument/completion failed.
  Message: System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at FsAutoComplete.Lsp.TextDocumentCompletion@624.Invoke(Unit unitVar) in D:\Programowanie\ionide\paket-files\github.com\fsharp\FsAutoComplete\src\FsAutoComplete\FsAutoComplete.Lsp.fs:line 637
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 398
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 109
  Code: -32603 
[Error - 1:54:38 PM] Request textDocument/completion failed.
  Message: System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at FsAutoComplete.Lsp.TextDocumentCompletion@624.Invoke(Unit unitVar) in D:\Programowanie\ionide\paket-files\github.com\fsharp\FsAutoComplete\src\FsAutoComplete\FsAutoComplete.Lsp.fs:line 637
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 398
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 109
  Code: -32603 
[Error - 1:54:50 PM] Request textDocument/completion failed.
  Message: System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at FsAutoComplete.Lsp.TextDocumentCompletion@624.Invoke(Unit unitVar) in D:\Programowanie\ionide\paket-files\github.com\fsharp\FsAutoComplete\src\FsAutoComplete\FsAutoComplete.Lsp.fs:line 637
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 398
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 109
  Code: -32603 
[Error - 1:54:50 PM] Request textDocument/completion failed.
  Message: System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at FsAutoComplete.Lsp.TextDocumentCompletion@624.Invoke(Unit unitVar) in D:\Programowanie\ionide\paket-files\github.com\fsharp\FsAutoComplete\src\FsAutoComplete\FsAutoComplete.Lsp.fs:line 637
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 398
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 109
  Code: -32603 
[Error - 1:54:50 PM] Request textDocument/completion failed.
  Message: System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at FsAutoComplete.Lsp.TextDocumentCompletion@624.Invoke(Unit unitVar) in D:\Programowanie\ionide\paket-files\github.com\fsharp\FsAutoComplete\src\FsAutoComplete\FsAutoComplete.Lsp.fs:line 637
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 398
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 109
  Code: -32603 
```

If the code is typed in first and then the mode is changed the output looks like this. The excption is logged after starting to edit. 

```
[Error - 1:56:27 PM] Request textDocument/hover failed.
  Message: Cached typecheck results not yet available
  Code: -32603 
[Error - 1:56:28 PM] Request textDocument/hover failed.
  Message: Cached typecheck results not yet available
  Code: -32603 
[Error - 1:56:34 PM] Request textDocument/completion failed.
  Message: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at FsAutoComplete.Lsp.TextDocumentCompletion@624.Invoke(Unit unitVar) in D:\Programowanie\ionide\paket-files\github.com\fsharp\FsAutoComplete\src\FsAutoComplete\FsAutoComplete.Lsp.fs:line 624
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 398
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 109
  Code: -32603 
```

And finally if the file is auto-opened by VSCode after a restart the output looks like this:

```
[Error - 3:59:45 PM] Request textDocument/foldingRange failed.
  Message: File '/Untitled-1.fsx' not parsed
  Code: -32603 
```

**Comment by jbeeko** [comment]
And finally probably the same bug. If you configure the setting files.defaultLanguage to fsharp and open a new file then.


First the empty file opens and you see this in the output:
```
[Error - 7:16:34 PM] Request textDocument/foldingRange failed.
  Message: File '/Untitled-1.fsx' not parsed
  Code: -32603 
```

Then as soon as you start typing in the editor you get the following in the output:
```
[Error - 7:16:49 PM] Request textDocument/completion failed.
  Message: System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at FsAutoComplete.Lsp.TextDocumentCompletion@624.Invoke(Unit unitVar) in D:\Programowanie\ionide\paket-files\github.com\fsharp\FsAutoComplete\src\FsAutoComplete\FsAutoComplete.Lsp.fs:line 637
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 398
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 109
  Code: -32603 
[Error - 7:16:49 PM] Request textDocument/completion failed.
  Message: System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at FsAutoComplete.Lsp.TextDocumentCompletion@624.Invoke(Unit unitVar) in D:\Programowanie\ionide\paket-files\github.com\fsharp\FsAutoComplete\src\FsAutoComplete\FsAutoComplete.Lsp.fs:line 637
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 398
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 109
  Code: -32603 
[Error - 7:16:50 PM] Request textDocument/completion failed.
  Message: System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at FsAutoComplete.Lsp.TextDocumentCompletion@624.Invoke(Unit unitVar) in D:\Programowanie\ionide\paket-files\github.com\fsharp\FsAutoComplete\src\FsAutoComplete\FsAutoComplete.Lsp.fs:line 637
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 398
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 109
  Code: -32603 
[Error - 7:16:50 PM] Request textDocument/completion failed.
  Message: System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at FsAutoComplete.Lsp.TextDocumentCompletion@624.Invoke(Unit unitVar) in D:\Programowanie\ionide\paket-files\github.com\fsharp\FsAutoComplete\src\FsAutoComplete\FsAutoComplete.Lsp.fs:line 637
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 398
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 109
  Code: -32603 
[Error - 7:16:50 PM] Request textDocument/completion failed.
  Message: System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at FsAutoComplete.Lsp.TextDocumentCompletion@624.Invoke(Unit unitVar) in D:\Programowanie\ionide\paket-files\github.com\fsharp\FsAutoComplete\src\FsAutoComplete\FsAutoComplete.Lsp.fs:line 637
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 398
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 109
  Code: -32603 
```

**Comment by Krzysztof-Cieslak** [comment]
This works just fine for me. As I've mentioned in another issue - you need to have folder opened anyway, Ionide won't work at all with scenario without any folder opened

![image](https://user-images.githubusercontent.com/5427083/84389634-a19dcf80-abf6-11ea-8b05-89980520849e.png)

**Comment by jbeeko** [comment]
Yah, as I mentioned in #1381 this issue is probably a manifestation of not having a folder open and I'm happy to have this issue closed
