### ISSUE TITLE
 4.15.0 crashes when I open a project

### ISSUE THREAD

**Issue by OnurGumus** [ionide/ionide-vscode-fsharp#1404]
**Describe the bug**
When I open my project extension host crashes.
It specifically happens with 4.15.0. Previous version doesn't have the problem

**To Reproduce**
Steps to reproduce the behaviour:
Just open a project I hav

**Expected behaviour**
Should not crash

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows/WSL
 - Ionide version: 4.15.0
 - VSCode version: Latest as of now
 - dotnet SDK version: Latest as of now
 - mono / .Net Framework version:

**Additional context**
I can see the below error

[TypeError: Cannot read property 'toString' of undefined
	at ReadFileContext.callback (c:\Users\onur\.vscode\extensions\ionide.ionide-fsharp-4.15.0\fsharp.js:19378:27)
	at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:246:13)]

**Comment by OnurGumus** [comment]
Found the culprit. If you have the live sass compiler extension installed the above problem happens
