### ISSUE TITLE
Intermittent in Github Codespaces

### ISSUE THREAD

**Issue by joshspicer** [ionide/ionide-vscode-fsharp#1450]
**Describe the bug**
I am trying to use the vscode extension in [GitHub Codespaces](http://github.com/features/codespaces), where the extensions run natively on a vscode server. Extension works intermittently.  

**To Reproduce**
Upon first launching the codespace I get code suggestions and code lens. After closing the file and for every subsequent time the in editor features of the extension don't work.  I see these logs:

```
[Error - 6:37:03 PM] Request textDocument/hover failed.
  Message: Cached typecheck results not yet available
  Code: -32603 
[Error - 6:37:03 PM] Request textDocument/documentHighlight failed.
  Message: Cached typecheck results not yet available
  Code: -32603 
[Error - 6:37:14 PM] Request textDocument/hover failed.
  Message: Cached typecheck results not yet available
  Code: -32603 
[Error - 6:42:07 PM] Request textDocument/documentHighlight failed.
  Message: Cached typecheck results not yet available
  Code: -32603 
[Error - 6:43:01 PM] Request textDocument/completion failed.
  Message: no type check results
  Code: -32603 
[Error - 6:43:02 PM] Request textDocument/completion failed.
  Message: no type check results
  Code: -32603 
[Error - 6:43:02 PM] Request textDocument/completion failed.
  Message: no type check results
  Code: -32603 
[Error - 6:43:03 PM] Request textDocument/completion failed.
  Message: no type check results
  Code: -32603 
[Error - 6:43:03 PM] Request textDocument/completion failed.
  Message: no type check results
  Code: -32603 
[Error - 6:43:03 PM] Request textDocument/completion failed.
  Message: no type check results
  Code: -32603 
[Error - 6:43:03 PM] Request textDocument/completion failed.
  Message: no type check results
  Code: -32603 
[Error - 6:43:04 PM] Request textDocument/completion failed.
  Message: no type check results
  Code: -32603 
[Error - 6:43:04 PM] Request textDocument/completion failed.
  Message: no type check results
  Code: -32603 
[Error - 6:43:04 PM] Request textDocument/completion failed.
  Message: System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at FsAutoComplete.Lsp.TextDocumentCompletion@659.Invoke(Unit unitVar) in D:\Programowanie\ionide\paket-files\github.com\fsharp\FsAutoComplete\src\FsAutoComplete\FsAutoComplete.Lsp.fs:line 672
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 398
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 109
  Code: -32603 
[Error - 6:43:05 PM] Request textDocument/completion failed.
  Message: no type check results
  Code: -32603 
[Error - 6:43:06 PM] Request textDocument/completion failed.
  Message: no type check results
  Code: -32603 
[Error - 6:43:06 PM] Request textDocument/completion failed.
  Message: System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at FsAutoComplete.Lsp.TextDocumentCompletion@659.Invoke(Unit unitVar) in D:\Programowanie\ionide\paket-files\github.com\fsharp\FsAutoComplete\src\FsAutoComplete\FsAutoComplete.Lsp.fs:line 672
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 398
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 109
  Code: -32603 
[Error - 6:43:06 PM] Request textDocument/completion failed.
  Message: no type check results
  Code: -32603 
[Error - 6:43:07 PM] Request textDocument/completion failed.
  Message: no type check results
  Code: -32603 
[Error - 6:43:09 PM] Request textDocument/completion failed.
  Message: no type check results
  Code: -32603 
[Error - 6:43:10 PM] Request textDocument/completion failed.
  Message: no type check results
  Code: -32603 
[Error - 6:43:13 PM] Request textDocument/completion failed.
  Message: no type check results
  Code: -32603 
[Error - 6:43:20 PM] Request textDocument/hover failed.
  Message: Cached typecheck results not yet available
  Code: -32603 
[Error - 6:43:21 PM] Request textDocument/hover failed.
  Message: Cached typecheck results not yet available
  Code: -32603 
[Error - 6:43:54 PM] Request textDocument/completion failed.
  Message: no type check results
  Code: -32603 
[Error - 6:44:05 PM] Request textDocument/completion failed.
  Message: no type check results
  Code: -32603 
[Error - 6:44:07 PM] Request textDocument/completion failed.
  Message: no type check results
  Code: -32603 
[Error - 6:44:09 PM] Request textDocument/completion failed.
  Message: no type check results
  Code: -32603 
[Error - 6:46:56 PM] Request textDocument/documentHighlight failed.
  Message: Cached typecheck results not yet available
  Code: -32603 
[Error - 6:47:08 PM] Request textDocument/hover failed.
  Message: Cached typecheck results not yet available
  Code: -32603 
[Error - 6:54:09 PM] Request textDocument/hover failed.
  Message: Cached typecheck results not yet available
  Code: -32603 
[Error - 6:54:26 PM] Request textDocument/hover failed.
  Message: Cached typecheck results not yet available
  Code: -32603 
[Error - 6:54:26 PM] Request textDocument/hover failed.
  Message: Cached typecheck results not yet available
  Code: -32603 
[Error - 6:54:42 PM] Request textDocument/hover failed.
  Message: Cached typecheck results not yet available
  Code: -32603 
```

Upon a full stop/resume of the codespace I see:
```
[Error - 7:04:22 PM] Request textDocument/documentSymbol failed.
  Message: File '/home/codespace/workspace/adventofcode2020/10/solution.fsx' not parsed
  Code: -32603 
[Error - 7:04:44 PM] Request textDocument/hover failed.
  Message: Cached typecheck results not yet available
  Code: -32603 
[Error - 7:04:47 PM] Request textDocument/hover failed.
  Message: Cached typecheck results not yet available
  Code: -32603 
[Error - 7:04:47 PM] Request textDocument/hover failed.
  Message: Cached typecheck results not yet available
  Code: -32603 

```

Note i'm trying to write an F# `.fsx` script.   My dotnet sdk is the default provided by codespaces, which at moment is 
```
$ dotnet --version
5.0.100
```

**Expected behaviour**
document highlighting and completions should work

**Environment (please complete the following information):**
 - OS: Linux Codespaces (ubuntu 20.04)
```
$ /.codespaces/bin/codespaces -v
Command-line interface for Visual Studio Codespaces
1.0.3343
```
 - Ionide version: 4.17.0
 - VSCode version: 
```
$ code -v
1.52.0-insider
532ba43c78c82b24bdf94f9edde30cdf9b9bfa12
x64
```
 - dotnet SDK version: 5.0.100
 - mono / .Net Framework version: 

**Additional context**

You can try to repro with [my repo](http://github.com/joshspicer/adventofcode2020) and going to the `9` folder.  There will be an F# script.

**Comment by joshspicer** [comment]
I'm able to get all the ionide features to work when connecting to a Codespace via the VSCode client on Mac:

1. Deleting the `.ionide` folder
2. Suspending the codespace
3. Reconnecting to the codespace and opening an fsx file

The `.ionide` folder gets regenerated and the codelens, etc work until the next time I close/open the file.

**Comment by Krzysztof-Cieslak** [comment]
We don't provide any extra support for running Ionide in GitHub Codespaces. The extension is working fine in VSCode, using Remote Docker (in VSCode) or in editors emulating VSCode APIs like GitPod.

If it's not working in GitHub Codespaces than it's a problem with GitHub Codepsaces, not with Ionide.
