### ISSUE TITLE
ionide 5.0 - error by moving F# files in F# view

### ISSUE THREAD

**Issue by vilinski** [ionide/ionide-vscode-fsharp#1456]
**Describe the bug**

Can't reorder F# source files in the F# project view using arrows

```
Error running command fsharp.explorer.moveUp: System.NullReferenceException: Object reference not set to an instance of an object.
   at FsAutoComplete.FsProjEditor.moveFileUp(String fsprojPath, String file) in D:\Programowanie\ionide\paket-files\github.com\fsharp\FsAutoComplete\src\FsAutoComplete.Core\FsprojEdit.fs:line 11
   at <StartupCode$FsAutoComplete-Core>.$Commands.FsProjMoveFileUp@363.Invoke(Unit unitVar) in D:\Programowanie\ionide\paket-files\github.com\fsharp\FsAutoComplete\src\FsAutoComplete.Core\Commands.fs:line 363
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 386
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 104. This is likely caused by the extension that contributes fsharp.explorer.moveUp.
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to F# project view with opened F# project with more than one source file
2. Click on reorder arrow - up or down
3. See error

**Expected behaviour**
The F# source file is moved withing project files order.

**Environment (please complete the following information):**
 - OS: MacOS Big SUR
 - Ionide version: 5.0
 - VSCode version: 1.52.1
 - dotnet SDK version: 5.0.100
 - mono / .Net Framework version: none

**Additional context**
Dunno whether important - upgraded from 5.0 preview 03, cleared project cache, reloaded vscode window. Can't move files

**Comment by Krzysztof-Cieslak** [comment]
Are the files you try to move in a folder by any chance?

**Comment by vilinski** [comment]
Yes! Just tried again - it works if filesa are flat in a project root, but not in subfolders.
An also usual constellation with Shared folder where files are shared between Client and Server projects throws NPE

**Comment by rodsfreitas** [comment]
I'm having a possible related issue, when trying to add a new file from F# Explorer. 

Same environment here as in the main topic.

VS Code shows the following message: 

```
Error running command fsharp.explorer.addAbove: Object reference not set to an instance of an object.. This is likely caused by the extension that contributes fsharp.explorer.addAbove.
```

<img width="461" alt="image" src="https://user-images.githubusercontent.com/5301435/102943461-facfa100-446c-11eb-832f-fa66edebcd97.png">

**Comment by Krzysztof-Cieslak** [comment]
This has been fixed a while ago.
