### ISSUE TITLE
Ionide does not handle sending file paths with accents to fsi

### ISSUE THREAD

**Issue by nhirschey** [ionide/ionide-vscode-fsharp#1498]
### Describe the bug**
When there is an accent in a file path, Ionide does not seem to handle it correctly. This creates issues if you have a folder on the path with an accent (e.g., your name is Tomás) and then you try to use something like `System.IO.Directory.SetCurrentDirectory(__SOURCE_DIRECTORY__)` where the path contains Tomás.

In contrast, running the same code from that folder in VS 2019 or dotnet fsi from the command line produces no error. Since it works in dotnet fsi and vs19, it does not look like the same bugs as https://github.com/dotnet/fsharp/issues/7733 or https://github.com/dotnet/fsharp/issues/8261.  

Ionide result:

```fsharp

Microsoft (R) F# Interactive version 11.0.0.0 for F# 5.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> # silentCd @"c:\temp\test\Tom�s";;

  # silentCd @"c:\temp\test\Tom�s";;
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

stdin(1,1): error FS2302: Directory 'c:\temp\test\Tom�s' doesn't exist

> # 1 @"c:\temp\test\Tom�s\test.fsx"
- ;;
> System.IO.Directory.SetCurrentDirectory(__SOURCE_DIRECTORY__);;
System.IO.DirectoryNotFoundException: Could not find a part of the path 'c:\temp\test\Tom�s'.
   at System.Environment.set_CurrentDirectoryCore(String value)
   at System.Environment.set_CurrentDirectory(String value)
   at System.IO.Directory.SetCurrentDirectory(String path)
   at <StartupCode$FSI_0002>.$FSI_0002.main@()
Stopped due to error
>
```

### Steps to reproduce

1. create the problem folder:
```
mkdir c:/temp/test/Tomás
cd c:/temp/test/Tomás
code c:/temp/test/Tomás
```

2. open a file there called 'test.fsx'
3. Execute `System.IO.Directory.SetCurrentDirectory(__SOURCE_DIRECTORY__)` in the script using alt+enter

### Expected behaviour
Same result as visual studio or dotnet fsi, it should set the directory without an error.

### Screenshots
1. Ionide ![image](https://user-images.githubusercontent.com/5226115/107790261-7dc4f780-6d4a-11eb-9f85-8319aa9a731a.png)
2. dotnet fsi 
![image](https://user-images.githubusercontent.com/5226115/107790444-abaa3c00-6d4a-11eb-9a49-abb9228f8397.png)

## Machine info
Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

 - .NET SDK version: 5.0.102
 - Ionide version: 5.3.2

**Comment by nhirschey** [comment]
It appears that the fsiExtraParameters described here fixes this: https://github.com/ionide/ionide-vscode-fsharp/issues/1236#issuecomment-725891973
