### ISSUE TITLE
Creation of a new project fails on Windows with a non-English setup

### ISSUE THREAD

**Issue by jmiven** [ionide/ionide-vscode-fsharp#1569]
### Describe the bug
When the `dotnet` CLI tool is localized to another language than English, the "New Project" command fail with the following exception: 

```
[2021-08-23 04:12:12.563] [exthost] [error] Error: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at FsAutoComplete.DotnetNewTemplate.parseTemplateOutput@46(String x) in D:\a\ionide-vscode-fsharp\ionide-vscode-fsharp\paket-files\github.com\fsharp\FsAutoComplete\src\FsAutoComplete.Core\DotnetNewTemplate.fs:line 47
   at FsAutoComplete.DotnetNewTemplate.installedTemplates() in D:\a\ionide-vscode-fsharp\ionide-vscode-fsharp\paket-files\github.com\fsharp\FsAutoComplete\src\FsAutoComplete.Core\DotnetNewTemplate.fs:line 66
   at <StartupCode$FsAutoComplete-Core>.$Commands.DotnetNewList@436.Invoke(Unit unitVar) in D:\a\ionide-vscode-fsharp\ionide-vscode-fsharp\paket-files\github.com\fsharp\FsAutoComplete\src\FsAutoComplete.Core\Commands.fs:line 436
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 386
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 104
	at c:\Users\Vivien\.vscode\extensions\ionide.ionide-fsharp-5.7.1\fsharp.js:2:159705
	at c:\Users\Vivien\.vscode\extensions\ionide.ionide-fsharp-5.7.1\fsharp.js:2:159999
	at Immediate.<anonymous> (c:\Users\Vivien\.vscode\extensions\ionide.ionide-fsharp-5.7.1\fsharp.js:2:160362)
	at processImmediate (internal/timers.js:461:21) fsharp.NewProject
```

### Steps to reproduce
- Set the display language in Windows to a language other than English (e.g. French) and logout
- [Install .NET 5](https://dotnet.microsoft.com/download)
- Open in VSCode/Ionide a F# solution created with the `dotnet` CLI tool
- Launch the `F#: New Project` command

### Machine info
 - OS: **Windows 10 21H1**
 - .NET SDK version: **5.0.400**
 - Ionide version: **5.7.1**

### How to work around it
To list the available templates, FsAutoComplete [parses directly the output](https://github.com/fsharp/FsAutoComplete/blob/6d0d1fd17cc85830a954b23e6246a5ce22e2d088/src/FsAutoComplete.Core/DotnetNewTemplate.fs#L30) of `dotnet new --list -lang F#` and searches for english words. 
Setting the **`DOTNET_CLI_UI_LANGUAGE` environment variable to `en-us`** forces the `dotnet` tool to print its output in english ([source](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-environment-variables#dotnet_cli_ui_language)).

**Comment by baronfel** [comment]
I agree completely with your assessment, nice digging! Would you be interested in contributing a fix to FSAC?

**Comment by jmiven** [comment]
Sure!

**Comment by baronfel** [comment]
Great! You'd want to be looking at [this function](https://github.com/fsharp/FsAutoComplete/blob/master/src/FsAutoComplete.Core/DotnetNewTemplate.fs#L31-L44) I think, and make sure to hard-code this environment variable in the process start info there.
