### ISSUE TITLE
Command "Clear Cache" and "Logs" not working & producing same error

### ISSUE THREAD

**Issue by carere** [ionide/ionide-vscode-fsharp#1586]
First of all, i would like to thank you for this amazing extension 😃

### Describe the bug

Output of the `Clear Cache` command 🔽 
```
[2021-09-22 23:57:14.365] [exthost] [error] TypeError: Invalid attempt to spread non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
	at e.exports (/home/carere/.vscode/extensions/ionide.ionide-fsharp-5.7.3/fsharp.js:2:125259)
	at e.exports (/home/carere/.vscode/extensions/ionide.ionide-fsharp-5.7.3/fsharp.js:1:65285)
	at fo (/home/carere/.vscode/extensions/ionide.ionide-fsharp-5.7.3/fsharp.js:2:390442)
	at /home/carere/.vscode/extensions/ionide.ionide-fsharp-5.7.3/fsharp.js:2:453454
	at _executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:110879)
	at _.$executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:111317)
	at i._doInvokeHandler (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:13543)
	at i._invokeHandler (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:13227)
	at i._receiveRequest (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:11889)
	at i._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:10567)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:8663
	at c.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
	at l.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:15781)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:30187
	at c.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
	at l.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:15781)
	at r._receiveMessage (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:21051)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:17929
	at c.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
	at v.acceptChunk (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:13142)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:12490
	at Socket.w (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:13350)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23) fsharp.explorer.clearCache
```
Output of `F#: Get Ionide Logs` command 🔽 

```
[2021-09-23 00:00:13.140] [exthost] [error] TypeError: Invalid attempt to spread non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
	at e.exports (/home/carere/.vscode/extensions/ionide.ionide-fsharp-5.7.3/fsharp.js:2:125259)
	at e.exports (/home/carere/.vscode/extensions/ionide.ionide-fsharp-5.7.3/fsharp.js:1:65285)
	at /home/carere/.vscode/extensions/ionide.ionide-fsharp-5.7.3/fsharp.js:2:468957
	at /home/carere/.vscode/extensions/ionide.ionide-fsharp-5.7.3/fsharp.js:1:40460
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async _executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:110871) fsharp.diagnostics.getIonideLogs
```

### Steps to reproduce
- Fresh install of Vscode + Ionide extension for F#
- Install .NET sdk 5.0
- Open a F# project (mine is a solution with 2 F# project, App & Tests, i aslo using paket)

### Expected behaviour
Working  `Clear cache` & `Logs` commands ? 😄
I see other issues with the same error, maybe fixing this error could fix other issues, like Vscode not loading project on startup (sometimes)

## Machine info
 - OS: Linux, Elementary OS 6 (Ubuntu 20.04)
 - .NET SDK version: 5.0.401
 - Ionide version: 5.7.3

**Comment by aggieben** [comment]
I am experiencing a similar problem on macOS Monterrey, Ionide 5.10.2.

**Comment by sonicbhoc** [comment]
I'm experiencing the same issue. I also can't get the Solution Explorer to refresh when I change the fsproj file.

**Comment by subhashgorasiya** [comment]
Getting same error while trying to clear F# project cache.

![image](https://user-images.githubusercontent.com/9932402/148018028-bf911ce8-aea5-43e6-9d52-80a3811c8593.png)

**Comment by leilapearson** [comment]
Seeing the same error. Workaround was to restart vscode. Was also seeing build errors reported in ionide but not with `dotnet build`.

**Comment by Krzysztof-Cieslak** [comment]
I cannot reproduce it anymore.
