### ISSUE TITLE
Command fsharp.NewProject fails when no project is loaded

### ISSUE THREAD

**Issue by Happypig375** [ionide/ionide-vscode-fsharp#1587]
### Describe the bug**
Command fsharp.NewProject fails when no project is loaded.

### Steps to reproduce
View > Command Palette > F#: New Project

In contrast, after opening a folder containing an F# project, the same command could run successfully and ask for inputs.

### Link to sample reproduction
N/A

### Expected behaviour
Projects can be created when existing projects are not loaded.

### Screenshots
![image](https://user-images.githubusercontent.com/19922066/133872653-b0d9fea8-a163-4a19-84a1-a484db562f16.png)

## Machine info
 - OS: Windows
 - .NET SDK version: 5.0.400
 - Ionide version: 5.7.3

### Additional context
N/A

**Comment by Happypig375** [comment]
```

[2021-09-18 12:45:45.941] [exthost] [info] ExtensionService#_doActivateExtension Ionide.Ionide-fsharp {"startup":false,"extensionId":{"value":"Ionide.Ionide-fsharp","_lower":"ionide.ionide-fsharp"},"activationEvent":"onCommand:fsharp.NewProject"}
[2021-09-18 12:45:45.941] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/hadri/.vscode/extensions/ionide.ionide-fsharp-5.7.3/fsharp
[2021-09-18 12:45:50.865] [exthost] [warning] [Ionide.Ionide-fsharp] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for '[fsharp]', provide the URI of a resource or 'null' for any resource.
[2021-09-18 12:45:52.645] [exthost] [error] TypeError: Invalid attempt to spread non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
	at e.exports (c:\Users\hadri\.vscode\extensions\ionide.ionide-fsharp-5.7.3\fsharp.js:2:125259)
	at e.exports (c:\Users\hadri\.vscode\extensions\ionide.ionide-fsharp-5.7.3\fsharp.js:1:65285)
	at c:\Users\hadri\.vscode\extensions\ionide.ionide-fsharp-5.7.3\fsharp.js:2:451380
	at async _executeContributedCommand (c:\Users\hadri\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:94:110871) fsharp.NewProject
```
