### ISSUE TITLE
LangServer crashes often (at "AddMissingFunKeyword")

### ISSUE THREAD

**Issue by RonaldSchlenker** [ionide/ionide-vscode-fsharp#1785]
As suggested in #1758 , here's the bug report of crashing language server.

The issue occurs on

* Windows 11
* dotnet SDK 6.0.304
* VSCode + Ionode 7.2.0 - 24.08.2022 (BTW - I guess the date in the changelog is wrong; should propably be 24.09.2022)

**Reproduce**

Open a VSCode workspace with a single .fsx file in it, create some types, aliases, functions. Here's the code just before the crash:

```fsharp
open System.Threading

type Step<'a> = unit -> 'a

let bind (m: Step<'a>) (f: 'a -> Step<'b>) : Step<'b> =
    let evt = new ManualResetEvent(false)
    let mutable mRes = Choice1Of3
    do
        fun _ ->
            try
                mRes <- m() |> Choice2Of3
``` 

This is the trace:

```
[20:34:29.519 ERR] [Startup] Start - LSP mode crashed
System.AggregateException: One or more errors occurred. (Index and length must refer to a location within the string. (Parameter 'length'))
 ---> System.ArgumentOutOfRangeException: Index and length must refer to a location within the string. (Parameter 'length')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at FsAutoComplete.NamedText.GetText(Range m) in /home/runner/work/FsAutoComplete/FsAutoComplete/src/FsAutoComplete.Core/FileSystem.fs:line 134
   at FsAutoComplete.Lsp.getLineText@915.Invoke(NamedText lines, Range range) in /home/runner/work/FsAutoComplete/FsAutoComplete/src/FsAutoComplete/FsAutoComplete.Lsp.fs:line 915
   at FsAutoComplete.CodeFix.AddMissingFunKeyword.binder@1-2(FSharpFunc`2 getLineText, Diagnostic diagnostic, CodeActionParams codeActionParams, NamedText lines) in /home/runner/work/FsAutoComplete/FsAutoComplete/src/FsAutoComplete/CodeFixes/AddMissingFunKeyword.fs:line 19
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, b result1, FSharpFunc`2 userCode) in D:\a\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 465
   at Microsoft.FSharp.Control.AsyncActivation`1.Success(AsyncActivation`1 ctxt, T result) in D:\a\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 324
   at FsToolkit.ErrorHandling.AsyncResult.retn@39.Invoke(AsyncActivation`1 ctxt)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 104
   --- End of inner exception stack trace ---
   at Ionide.LanguageServerProtocol.Server.startWithSetup[client](FSharpFunc`2 setupRequestHandlings, Stream input, Stream output, FSharpFunc`2 clientCreator, FSharpFunc`2 customizeRpc) in /_//src/LanguageServerProtocol.fs:line 179
   at Ionide.LanguageServerProtocol.Server.start@268-2.Invoke(FSharpFunc`2 customizeRpc) in /_//src/LanguageServerProtocol.fs:line 268
   at FsAutoComplete.Lsp.startCore(ToolsPath toolsPath, DirectoryInfo stateStorageDir, FSharpFunc`2 workspaceLoaderFactory) in /home/runner/work/FsAutoComplete/FsAutoComplete/src/FsAutoComplete/FsAutoComplete.Lsp.fs:line 2947
   at FsAutoComplete.Lsp.start(ToolsPath toolsPath, DirectoryInfo stateStorageDir, FSharpFunc`2 workspaceLoaderFactory) in /home/runner/work/FsAutoComplete/FsAutoComplete/src/FsAutoComplete/FsAutoComplete.Lsp.fs:line 2959
[Error - 20:34:29] The F# server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

Thank you for your effort and your time.

**Comment by OnurGumus** [comment]
Same here with macos and 6.0.400

**Comment by baronfel** [comment]
I see a few steps to fixing this for real:
* quick fix is try/catch all codefixes [here](https://github.com/fsharp/FsAutoComplete/blob/main/src/FsAutoComplete/FsAutoComplete.Lsp.fs#L1865-L1868)
* next step is extending the settings for FSAC to make each codefix individually toggleable on/off via settings and plumbing those settings through to the individual codefixes. We have [something like this](https://github.com/fsharp/FsAutoComplete/blob/main/src/FsAutoComplete/FsAutoComplete.Lsp.fs#L949) already, but should systematize it. Something like `"fsharp.codeFixes.<name>.enabled": true`, and so forth.
* final step is making each codefix instead of just try/catch _log_ its name and state when failing.

I'm put in a hotfix for the first step now-ish and we can leave this open to represent the work for the remaining steps

**Comment by baronfel** [comment]
Hotfix 7.2.1 is released with the hotfix portion of these steps.

**Comment by RonaldSchlenker** [comment]
22:29 is a thumbs-up time for a hotfix… I’ll check tomorrow. Thank you @baronfel :)
