### ISSUE TITLE
Error on cracking projects and load code lense 

### ISSUE THREAD

**Issue by JohnnyFasching** [ionide/ionide-vscode-fsharp#1799]
### Describe the bug
Code lens and auto complete not working when loading F# projects 

``` Parsing xxx
Failed to build xxx.fsproj: Object reference not set to an instance of an object.
   at ProjectCracker.parseProjectAssets(FileInfo projectAssetsJson) in /Users/george/Documents/fsharp-language-server/src/ProjectCracker/ProjectCracker.fs:line 197
   at ProjectCracker.crack(FileInfo fsproj) in /Users/george/Documents/fsharp-language-server/src/ProjectCracker/ProjectCracker.fs:line 559

xxx.fsproj: 
  ProjectFileName: "xxx"
  SourceFiles: [||]
  ReferencedProjects: []
  OtherOptions: [|"--noframework"|]
  LoadTime: 27/10/2022 09:31:23
  ExtraProjectInfo: <null>
  IsIncompleteTypeCheckEnvironment: false
  OriginalLoadReferences: []
  ExtraProjectInfo: <null>
  Stamp: <null>
  UnresolvedReferences: <null>
  UseScriptResolutionRules: false

Failed to create code lens because project options failed to load: [{ range = { start = { line = 0
                       character = 0 }
             end = { line = 0
                     character = 1 } }
   severity = Some Error
   code = None
   source = None
   message =
            "No .fsproj or .fsx file references c:\xxx\xxx.fs" }]
```

## Machine info
 - OS: Windows
 - .NET SDK version: 6.0.402
 - Ionide version: v7.3.1

**Comment by TheAngryByrd** [comment]
👋 Hey there.  That error is for another project over at https://github.com/fsprojects/fsharp-language-server.
