### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'subscriptions')

### ISSUE THREAD

**Issue by vain0x** [ionide/ionide-vscode-fsharp#1814]
### Describe the bug

When some of F# configurations change, unexpected error is reported in developer tools console.
This itself isn't a problem but confusing.

(Note: I hope this isn't a duplicated issue because the error is mentioned in other issues but this isn't the main problem there.)

### Steps to reproduce

- Open an F# file
- Open workspace settings of VSCode and change `FSharp.smartIndent` value
- Open developer tools console to see the error

### Expected behaviour

No error happens.

### Screenshots

![subscriptions-undefined-screenshot](https://user-images.githubusercontent.com/6957032/210260140-15f5fb40-082d-4b50-8b7a-f3c9a53751ea.png)

## Machine info

* Operating system: **Linux**
* Arch: **x64**
* VSCode: **1.74.2**
* UI Kind: **Desktop**
* Ionide: **7.4.0**
* Runtime: **netcore**
* Dotnet version: **6.0.302**

### Additional context

<details>
<summary>Error messages</summary>
<div>

```
[[object Object]]Cannot read properties of undefined (reading 'subscriptions')
$onExtensionRuntimeError @ workbench.desktop.main.js:2155
N @ workbench.desktop.main.js:1690
M @ workbench.desktop.main.js:1690
H @ workbench.desktop.main.js:1690
G @ workbench.desktop.main.js:1690
(anonymous) @ workbench.desktop.main.js:1690
invoke @ workbench.desktop.main.js:85
deliver @ workbench.desktop.main.js:85
fire @ workbench.desktop.main.js:85
fire @ workbench.desktop.main.js:550
y @ workbench.desktop.main.js:550
(anonymous) @ workbench.desktop.main.js:550
invoke @ workbench.desktop.main.js:85
deliver @ workbench.desktop.main.js:85
fire @ workbench.desktop.main.js:85
acceptChunk @ workbench.desktop.main.js:550
(anonymous) @ workbench.desktop.main.js:550
k @ workbench.desktop.main.js:550
emit @ node:events:526
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:190
workbench.desktop.main.js:2155 TypeError: Cannot read properties of undefined (reading 'subscriptions')
	at kd (vscode-file://vscode-app/home/owner/.vscode/extensions/ionide.ionide-fsharp-7.4.0/fsharp.js:2:782676)
	at vscode-file://vscode-app/home/owner/.vscode/extensions/ionide.ionide-fsharp-7.4.0/fsharp.js:2:822133
	at Object.<anonymous> (vscode-file://vscode-app/home/owner/.vscode/extensions/ionide.ionide-fsharp-7.4.0/fsharp.js:2:822184)
	at d.invoke (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at w.deliver (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
	at g.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
	at s.$acceptConfigurationChanged (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:105:23866)
	at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:105:23350
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)

```

</details>

### Cause

In this function, `context` argument is undefined. (I added a debug log and saw it was undefined.)

https://github.com/ionide/ionide-vscode-fsharp/blob/7.4.0/src/Components/LanguageConfiguration.fs#L20

That is called from: https://github.com/ionide/ionide-vscode-fsharp/blob/7.4.0/src/Components/LanguageConfiguration.fs#L73-L74

(Note: `context` is passed in `workspace.onDidChangeConfiguration`, not in the function above.)

### Suggestion

`context` parameter is used only here:

https://github.com/ionide/ionide-vscode-fsharp/blob/7.4.0/src/Components/LanguageConfiguration.fs#L65

However, the line is unnecessary because `disp` is held by `reference` and gets disposed on the next call to the function.
I think it's okay to remove `context` parameter and the line.

I want to make a PR to fix this if the way is okay.

**Comment by wiredsister** [comment]
Seeing uncaught error `Cannot read properties of undefined (reading 'subscriptions')` on version 7.4.2 running in WSL. 

```sh
gina@SurfaceBaby:~/Repositories/CultureAmped$ code --version
1.75.1
441438abd1ac652551dbe4d408dfcec8a499b8bf
x64
```

```sh
gina@SurfaceBaby:~/Repositories/CultureAmped$ code --list-extensions 
Extensions installed on WSL: Debian:
eamodio.gitlens
GitHub.vscode-pull-request-github
Ionide.Ionide-fsharp
ms-azuretools.vscode-docker
ms-dotnettools.csharp
ms-vsliveshare.vsliveshare
tomoki1207.pdf
yzhang.markdown-all-in-one
```

```
gina@SurfaceBaby:~/Repositories/CultureAmped$ dotnet --info
.NET SDK:
 Version:   7.0.201
 Commit:    68f2d7e7a3

Runtime Environment:
 OS Name:     debian
 OS Version:  11
 OS Platform: Linux
 RID:         debian.11-x64
 Base Path:   /usr/share/dotnet/sdk/7.0.201/

Host:
  Version:      7.0.3
  Architecture: x64
  Commit:       0a2bda10e8

.NET SDKs installed:
  6.0.406 [/usr/share/dotnet/sdk]
  7.0.201 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.14 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.14 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
  ```

I'm pretty sure this closed out issues fixes it, just wanted to paste here that I'm seeing it. Thanks for your work.
