### ISSUE TITLE
When building the project, the `YarnIntall` step fails

### ISSUE THREAD

**Issue by mrakgr** [ionide/ionide-vscode-fsharp#1820]
### Steps to reproduce

I am just running the build.cmd file from the command file after cloning the repo. Here is the output of what happens. I'll try to deal with this on my own if possible, but anybody knows what to do I'd like hear it. Maybe there are some JS libraries I need to install separately from this?

```
E:\ionide-vscode-fsharp>dotnet tool restore

Welcome to .NET 6.0!
---------------------
SDK Version: 6.0.405

Telemetry
---------
The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
Tool 'paket' (version '7.0.2') was restored. Available commands: paket
Tool 'fable' (version '3.7.11') was restored. Available commands: fable
Tool 'fantomas' (version '5.1.4') was restored. Available commands: fantomas

Restore was successful.
```

```
E:\ionide-vscode-fsharp>dotnet run --project build --
run Default
Building project with version: LocalBuild
Shortened DependencyGraph for Target Default:
<== Default
   <== CopySchemas
      <== CopyGrammar
         <== RunScript
            <== YarnInstall
            <== DotNetRestore
            <== Format
               <== Clean
         <== CopyFSACNetcore
            <== CopyDocs

The running order is:
Group - 1
  - Clean
  - DotNetRestore
  - YarnInstall
Group - 2
  - Format
Group - 3
  - RunScript
Group - 4
  - CopyDocs
Group - 5
  - CopyFSACNetcore
Group - 6
  - CopyGrammar
Group - 7
  - CopySchemas
Group - 8
  - Default
Starting target 'Clean'
Finished (Success) 'Clean' in 00:00:00.0179061
Starting target 'DotNetRestore'
Starting task 'DotNet:restore': src
E:\ionide-vscode-fsharp> "dotnet.exe"  msbuild /version /nologo (In: false, Out: true, Err: true)
17.3.2.46306
E:\ionide-vscode-fsharp> "dotnet.exe"  restore src /nodeReuse:False "/bl:C:\Users\Marko\AppData\Local\Temp\tmpC902.tmp.binlog" (In: false, Out: false, Err: false)
C:\Program Files\dotnet\sdk\6.0.405\MSBuild.dll -nologo -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,C:\Program Files\dotnet\sdk\6.0.405\dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,C:\Program Files\dotnet\sdk\6.0.405\dotnet.dll -maxcpucount -target:Restore -verbosity:m /bl:C:\Users\Marko\AppData\Local\Temp\tmpC902.tmp.binlog /nodeReuse:False src\Ionide.FSharp.fsproj
  Determining projects to restore...
  Restored E:\ionide-vscode-fsharp\src\Ionide.FSharp.fsproj (in 144 ms).
Finished (Success) 'DotNet:restore' in 00:00:01.8255672
Finished (Success) 'DotNetRestore' in 00:00:01.9470313
Starting target 'YarnInstall'
.> "E:\ionide-vscode-fsharp\packages\Yarnpkg.js\tools\yarn.cmd" install (In: false, Out: false, Err: false)
Finished (Failed) 'YarnInstall' in 00:00:00.0639637

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target            Duration
------            --------
Clean             00:00:00.0149790
DotNetRestore     00:00:01.9466756
YarnInstall       00:00:00.0634731   (Start of process 'E:\ionide-vscode-fsharp\packages\Yarnpkg.js\tools\yarn.cmd' failed.)
Format            00:00:00           (skipped)
RunScript         00:00:00           (skipped)
CopyDocs          00:00:00           (skipped)
CopyFSACNetcore   00:00:00           (skipped)
CopyGrammar       00:00:00           (skipped)
CopySchemas       00:00:00           (skipped)
Default           00:00:00           (skipped)
Total:            00:00:02.1127804
Status:           Failure
---------------------------------------------------------------------
Unhandled exception. Fake.Core.BuildFailedException: Target 'YarnInstall' failed.
 ---> System.AggregateException: One or more errors occurred. (Start of process 'E:\ionide-vscode-fsharp\packages\Yarnpkg.js\tools\yarn.cmd' failed.)
 ---> System.Exception: Start of process 'E:\ionide-vscode-fsharp\packages\Yarnpkg.js\tools\yarn.cmd' failed.
 ---> System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'E:\ionide-vscode-fsharp\packages\Yarnpkg.js\tools\yarn.cmd' with working directory '.'. The system cannot find the file specified.       
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Fake.Core.Process.processStarter@415.Invoke(RawCreateProcess c, Process p)
   --- End of inner exception stack trace ---
   at Fake.Core.Process.processStarter@415.Invoke(RawCreateProcess c, Process p)
   at Fake.Core.RawProc.start@209(FSharpFunc`2 startProcessRaw, RawCreateProcess c, ProcessStartInfo p, StreamSpecs streamSpec, Process toolProcess, CancellationTokenSource tok, FSharpRef`1 isStarted, FSharpRef`1 readOutputTask, FSharpRef`1 readErrorTask, FSharpRef`1 redirectStdInTask, Unit unitVar0)
   at Fake.Core.RawProc.syncStart@270.Invoke(Unit unitVar0)
--- End of stack trace from previous location ---
   at Microsoft.FSharp.Control.AsyncResult`1.Commit() in D:\a\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 393
   at Microsoft.FSharp.Control.AsyncPrimitives.QueueAsyncAndWaitForResultSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout) in D:\a\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 1045
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken cancellationToken, FSharpAsync`1 computation, FSharpOption`1 timeout) in D:\a\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 1071
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken) in D:\a\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 1366
   at Fake.Core.Proc.run[a](CreateProcess`1 c)
   at Fake.JavaScript.Yarn.run(YarnParams yarnParams, YarnCommand command)
   at Fake.JavaScript.Yarn.install(FSharpFunc`2 setParams)
   at Program.initTargets@279-1.Invoke(TargetParameter _arg2) in E:\ionide-vscode-fsharp\build\Program.fs:line 279
   at Fake.Core.TargetModule.runSimpleInternal(TargetContext context, Target target)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at Fake.Core.TargetModule.raiseIfError(OptionalTargetContext context)
   at Fake.Core.TargetModule.runOrDefaultWithArguments(String defaultTarget)
   at Program.main(String[] argv) in E:\ionide-vscode-fsharp\build\Program.fs:line 425
```

## Machine info
 - OS: Windows 10
 - .NET SDK version: v6.0.405
 - Ionide version: commit (master branch): 2ac08f0702cbd756266ce1ddc785aac0af514cda

**Comment by mrakgr** [comment]
I am looking at the `e:\ionide-vscode-fsharp\packages ` where I'd expect `Yarnpkg.js` to be, but only `fsac` is there. So it is no wonder that it cannot run `.> "E:\ionide-vscode-fsharp\packages\Yarnpkg.js\tools\yarn.cmd" install (In: false, Out: false, Err: false)`.

**Comment by baronfel** [comment]
We have a prerequisite to have yarn installed and in your systems path, I believe the path you're seeing in the error message is the final fallback location in FAKE's tool probing logic when it can't resolve a tool from your path.

**Comment by mrakgr** [comment]
Hmmm...I installed it using `npm install --global yarn`, but the above step still fails. When I try running yarn from the terminal just to check if it works, it does seem to have in path, but I get the following error:

```
PS E:\ionide-vscode-fsharp> yarn            
yarn install v1.22.19
error An unexpected error occurred: "Invalid value type 247:0 in E:\\ionide-vscode-fsharp\\yarn.lock".
info If you think this is a bug, please open a bug report with the information provided in "E:\\ionide-vscode-fsharp\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

In a different folder it creates a `yarn.lock` file without error.

**Comment by mrakgr** [comment]
When I run `.build` I see the error is different than last time.

```
E:\ionide-vscode-fsharp>dotnet tool restore
Tool 'paket' (version '7.0.2') was restored. Available commands: paket      
Tool 'fable' (version '3.7.11') was restored. Available commands: fable     
Tool 'fantomas' (version '5.1.4') was restored. Available commands: fantomas

Restore was successful.

E:\ionide-vscode-fsharp>dotnet run --project build --  
run Default
Building project with version: LocalBuild
Shortened DependencyGraph for Target Default:
<== Default
   <== CopySchemas
      <== CopyGrammar
         <== RunScript
            <== YarnInstall
            <== DotNetRestore
            <== Format
               <== Clean
         <== CopyFSACNetcore
            <== CopyDocs

The running order is:
Group - 1
  - Clean
  - DotNetRestore
  - YarnInstall
Group - 2
  - Format
Group - 3
  - RunScript
Group - 4
  - CopyDocs
Group - 5
  - CopyFSACNetcore
Group - 6
  - CopyGrammar
Group - 7
  - CopySchemas
Group - 8
  - Default
Starting target 'Clean'
Finished (Success) 'Clean' in 00:00:00.0059438
Starting target 'DotNetRestore'
Starting task 'DotNet:restore': src
E:\ionide-vscode-fsharp> "dotnet.exe"  msbuild /version /nologo (In: false, Out: true, Err: true)
17.3.2.46306
E:\ionide-vscode-fsharp> "dotnet.exe"  restore src /nodeReuse:False "/bl:C:\Users\Marko\AppData\Local\Temp\tmp25B4.tmp.binlog" (In: false, Out: false, Err: false)
C:\Program Files\dotnet\sdk\6.0.405\MSBuild.dll -nologo -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,C:\Program Files\dotnet\sdk\6.0.405\dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,C:\Program Files\dotnet\sdk\6.0.405\dotnet.dll -maxcpucount -target:Restore -verbosity:m /bl:C:\Users\Marko\AppData\Local\Temp\tmp25B4.tmp.binlog /nodeReuse:False src\Ionide.FSharp.fsproj
  Determining projects to restore...
  All projects are up-to-date for restore.
Finished (Success) 'DotNet:restore' in 00:00:01.1343827
Finished (Success) 'DotNetRestore' in 00:00:01.1375143
Starting target 'YarnInstall'
.> "C:\Users\Marko\AppData\Roaming\npm\yarn.CMD" install (In: false, Out: false, Err: false)
yarn install v1.22.19
error An unexpected error occurred: "Invalid value type 247:0 in E:\\ionide-vscode-fsharp\\yarn.lock".
info If you think this is a bug, please open a bug report with the information provided in "E:\\ionide-vscode-fsharp\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Finished (Failed) 'YarnInstall' in 00:00:00.7808961

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target            Duration
------            --------
Clean             00:00:00.0035557
DotNetRestore     00:00:01.1370413
YarnInstall       00:00:00.7788739   ('yarn install' task failed)
Format            00:00:00           (skipped)
RunScript         00:00:00           (skipped)
CopyDocs          00:00:00           (skipped)
CopyFSACNetcore   00:00:00           (skipped)
CopyGrammar       00:00:00           (skipped)
CopySchemas       00:00:00           (skipped)
Default           00:00:00           (skipped)
Total:            00:00:02.0054646
Status:           Failure
---------------------------------------------------------------------
Unhandled exception. Fake.Core.BuildFailedException: Target 'YarnInstall' failed.
 ---> System.AggregateException: One or more errors occurred. ('yarn install' task failed)
 ---> System.Exception: 'yarn install' task failed
   at Fake.Core.CreateProcess.ensureExitCodeWithMessage@592.Invoke(a data, Int32 exitCode)
   at Fake.Core.CreateProcess.addOnExited@584-5.Invoke(RawProcessResult e)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, b result1, FSharpFunc`2 userCode) in D:\a\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 465
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 104
--- End of stack trace from previous location ---
   at Microsoft.FSharp.Control.AsyncResult`1.Commit() in D:\a\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 393
   at Microsoft.FSharp.Control.AsyncPrimitives.QueueAsyncAndWaitForResultSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout) in D:\a\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 1045   
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken cancellationToken, FSharpAsync`1 computation, FSharpOption`1 timeout) in D:\a\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 1071
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken) in D:\a\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 1366
   at Fake.Core.Proc.run[a](CreateProcess`1 c)
   at Fake.JavaScript.Yarn.run(YarnParams yarnParams, YarnCommand command)
   at Fake.JavaScript.Yarn.install(FSharpFunc`2 setParams)
   at Program.initTargets@279-1.Invoke(TargetParameter _arg2) in E:\ionide-vscode-fsharp\build\Program.fs:line 279
   at Fake.Core.TargetModule.runSimpleInternal(TargetContext context, Target target)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at Fake.Core.TargetModule.raiseIfError(OptionalTargetContext context)
   at Fake.Core.TargetModule.runOrDefaultWithArguments(String defaultTarget)
   at Program.main(String[] argv) in E:\ionide-vscode-fsharp\build\Program.fs:line 425
```

**Comment by mrakgr** [comment]
I figured it out. It seems running `npm install` changed the `yarn.lock` file. I reverted it to how it was in the commit and now it is building.

**Comment by mrakgr** [comment]
It built fine, thanks.
