### ISSUE TITLE
Ionide crashes at startup from v7.8.3 onwards

### ISSUE THREAD

**Issue by philipcraig** [ionide/ionide-vscode-fsharp#1899]
### Describe the bug

Hard crash on startup

### Steps to reproduce

Open Visual Studio Code with Ionide installed
Have an `.fs` file present

### Expected behaviour

It shouldn't crash. Versions earlier than v7.8.3 are ok. Specifically v.7.8.2 is ok

## Machine info

 - OS: Windows 10 Enterprise. Build 19044.3208 Version 21H2
 - Visual Studio Code: 1.80.1
 - Ionide version: v7.8.2 and v7.8.3
 - in a RHEL 7.9 docker container in WSL
- `dotnet --version` 6.0.410

### Additional context

The startup stack-trace is:

```
[Error - 10:58:40 AM] Client F#: connection to server is erroring. Shutting down server.
[Error - 10:58:40 AM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: starting
	at _.shutdown (/home/pcraig30/.vscode-server/extensions/ionide.ionide-fsharp-7.8.3/fsharp.js:2:232281)
	at _.stop (/home/pcraig30/.vscode-server/extensions/ionide.ionide-fsharp-7.8.3/fsharp.js:2:231862)
	at _.stop (/home/pcraig30/.vscode-server/extensions/ionide.ionide-fsharp-7.8.3/fsharp.js:2:391809)
	at _.handleConnectionError (/home/pcraig30/.vscode-server/extensions/ionide.ionide-fsharp-7.8.3/fsharp.js:2:237825)
	at /home/pcraig30/.vscode-server/extensions/ionide.ionide-fsharp-7.8.3/fsharp.js:2:236652
	at /home/pcraig30/.vscode-server/extensions/ionide.ionide-fsharp-7.8.3/fsharp.js:2:235818
	at o.invoke (/home/pcraig30/.vscode-server/extensions/ionide.ionide-fsharp-7.8.3/fsharp.js:2:186644)
	at i.fire (/home/pcraig30/.vscode-server/extensions/ionide.ionide-fsharp-7.8.3/fsharp.js:2:187409)
	at /home/pcraig30/.vscode-server/extensions/ionide.ionide-fsharp-7.8.3/fsharp.js:2:179023
	at o.invoke (/home/pcraig30/.vscode-server/extensions/ionide.ionide-fsharp-7.8.3/fsharp.js:2:186644)
	at i.fire (/home/pcraig30/.vscode-server/extensions/ionide.ionide-fsharp-7.8.3/fsharp.js:2:187409)
	at g.fireError (/home/pcraig30/.vscode-server/extensions/ionide.ionide-fsharp-7.8.3/fsharp.js:2:198643)
	at Socket.<anonymous> (/home/pcraig30/.vscode-server/extensions/ionide.ionide-fsharp-7.8.3/fsharp.js:2:199429)
	at Socket.emit (node:events:513:28)
	at emitErrorNT (node:internal/streams/destroy:157:8)
	at emitErrorCloseNT (node:internal/streams/destroy:122:3)
	at processTicksAndRejections (node:internal/process/task_queues:83:21)
[Info  - 10:58:40 AM] Connection to server got closed. Server will restart.
[Error - 10:58:40 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:58:40 AM] F# client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:58:40 AM] Sending request fsharp/workspacePeek failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 10:58:41 AM] Connection to server got closed. Server will restart.
[Error - 10:58:41 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:58:41 AM] F# client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 10:58:41 AM] Connection to server got closed. Server will restart.
[Error - 10:58:41 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:58:41 AM] F# client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:58:41 AM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 10:58:41 AM] Connection to server got closed. Server will restart.
[Error - 10:58:41 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:58:41 AM] F# client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:58:41 AM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:58:41 AM] The F# server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 10:58:41 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:58:41 AM] F# client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:58:41 AM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
```

**Comment by mtrsk** [comment]
@philipcraig I can confirm this has been an issue for me (in both `v7.8.3` and `v7.8.4`), it's also breaking inside devcontainers. Reverting to v7.8.2 fixes the issue for now.

**Comment by TheAngryByrd** [comment]
Can you create a succinct reproduction? I cannot reproduce this on intel/Windows 11, intel/macOS or devcontainers.

**Comment by rjra100** [comment]
We're running Docker under WSL2, so genuinely succinct may be tricky. The gist of it was basically a matter of install a standard Ubuntu 20 WSL2 distro, `apt install docker.io`, and start `dockerd`, but there may be a bunch of additional setup in there to get it working.
With a working docker setup, though, something like this does it. I imagine that more-or-less any base image will behave this way - I've reproduced the problem with RHEL7 and an Ubuntu 20 base image. In case it matters, though, both will be using the same kernel; in my case 5.10.16.3-microsoft-standard-WSL2.

.devcontainer/Devcontainer.json
```json
{
    "name": "test",
    "image": "ubuntu20-openjdk17"
}
```

Do Open Folder in Container, wait for the container to start up. Now, in a (root) terminal in the container:

```sh
apt update
apt install -y wget
wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
dpkg -i packages-microsoft-prod.deb
apt update
apt install -y dotnet-sdk-6.0
```
Now install Ionide, and create a .fs file. It's not necessary to create a project, etc - the existence of a .fs file is sufficient to trigger the failure. Look at the F# pane in the Output (in this case with all the verbosity options I can find turned on):
```
[Trace - 6:02:39 PM] Sending request 'initialize - (0)'.
Params: {
    "processId": 3980,
    "clientInfo": {
        "name": "Visual Studio Code",
        "version": "1.80.1"
    },
    "locale": "en",
    "rootPath": "/workspaces/test",
    "rootUri": "file:///workspaces/test",
    "capabilities": {
        "workspace": {
            "applyEdit": true,
            "workspaceEdit": {
                "documentChanges": true,
                "resourceOperations": [
                    "create",
                    "rename",
                    "delete"
                ],
                "failureHandling": "textOnlyTransactional",
                "normalizesLineEndings": true,
                "changeAnnotationSupport": {
                    "groupsOnLabel": true
                }
            },
            "configuration": true,
            "didChangeWatchedFiles": {
                "dynamicRegistration": true,
                "relativePatternSupport": true
            },
            "symbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                },
                "tagSupport": {
                    "valueSet": [
                        1
                    ]
                },
                "resolveSupport": {
                    "properties": [
                        "location.range"
                    ]
                }
            },
            "codeLens": {
                "refreshSupport": true
            },
            "executeCommand": {
                "dynamicRegistration": true
            },
            "didChangeConfiguration": {
                "dynamicRegistration": true
            },
            "workspaceFolders": true,
            "semanticTokens": {
                "refreshSupport": true
            },
            "fileOperations": {
                "dynamicRegistration": true,
                "didCreate": true,
                "didRename": true,
                "didDelete": true,
                "willCreate": true,
                "willRename": true,
                "willDelete": true
            },
            "inlineValue": {
                "refreshSupport": true
            },
            "inlayHint": {
                "refreshSupport": true
            },
            "diagnostics": {
                "refreshSupport": true
            }
        },
        "textDocument": {
            "publishDiagnostics": {
                "relatedInformation": true,
                "versionSupport": false,
                "tagSupport": {
                    "valueSet": [
                        1,
                        2
                    ]
                },
                "codeDescriptionSupport": true,
                "dataSupport": true
            },
            "synchronization": {
                "dynamicRegistration": true,
                "willSave": true,
                "willSaveWaitUntil": true,
                "didSave": true
            },
            "completion": {
                "dynamicRegistration": true,
                "contextSupport": true,
                "completionItem": {
                    "snippetSupport": true,
                    "commitCharactersSupport": true,
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ],
                    "deprecatedSupport": true,
                    "preselectSupport": true,
                    "tagSupport": {
                        "valueSet": [
                            1
                        ]
                    },
                    "insertReplaceSupport": true,
                    "resolveSupport": {
                        "properties": [
                            "documentation",
                            "detail",
                            "additionalTextEdits"
                        ]
                    },
                    "insertTextModeSupport": {
                        "valueSet": [
                            1,
                            2
                        ]
                    },
                    "labelDetailsSupport": true
                },
                "insertTextMode": 2,
                "completionItemKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25
                    ]
                },
                "completionList": {
                    "itemDefaults": [
                        "commitCharacters",
                        "editRange",
                        "insertTextFormat",
                        "insertTextMode"
                    ]
                }
            },
            "hover": {
                "dynamicRegistration": true,
                "contentFormat": [
                    "markdown",
                    "plaintext"
                ]
            },
            "signatureHelp": {
                "dynamicRegistration": true,
                "signatureInformation": {
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ],
                    "parameterInformation": {
                        "labelOffsetSupport": true
                    },
                    "activeParameterSupport": true
                },
                "contextSupport": true
            },
            "definition": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "references": {
                "dynamicRegistration": true
            },
            "documentHighlight": {
                "dynamicRegistration": true
            },
            "documentSymbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                },
                "hierarchicalDocumentSymbolSupport": true,
                "tagSupport": {
                    "valueSet": [
                        1
                    ]
                },
                "labelSupport": true
            },
            "codeAction": {
                "dynamicRegistration": true,
                "isPreferredSupport": true,
                "disabledSupport": true,
                "dataSupport": true,
                "resolveSupport": {
                    "properties": [
                        "edit"
                    ]
                },
                "codeActionLiteralSupport": {
                    "codeActionKind": {
                        "valueSet": [
                            "",
                            "quickfix",
                            "refactor",
                            "refactor.extract",
                            "refactor.inline",
                            "refactor.rewrite",
                            "source",
                            "source.organizeImports"
                        ]
                    }
                },
                "honorsChangeAnnotations": false
            },
            "codeLens": {
                "dynamicRegistration": true
            },
            "formatting": {
                "dynamicRegistration": true
            },
            "rangeFormatting": {
                "dynamicRegistration": true
            },
            "onTypeFormatting": {
                "dynamicRegistration": true
            },
            "rename": {
                "dynamicRegistration": true,
                "prepareSupport": true,
                "prepareSupportDefaultBehavior": 1,
                "honorsChangeAnnotations": true
            },
            "documentLink": {
                "dynamicRegistration": true,
                "tooltipSupport": true
            },
            "typeDefinition": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "implementation": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "colorProvider": {
                "dynamicRegistration": true
            },
            "foldingRange": {
                "dynamicRegistration": true,
                "rangeLimit": 5000,
                "lineFoldingOnly": true,
                "foldingRangeKind": {
                    "valueSet": [
                        "comment",
                        "imports",
                        "region"
                    ]
                },
                "foldingRange": {
                    "collapsedText": false
                }
            },
            "declaration": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "selectionRange": {
                "dynamicRegistration": true
            },
            "callHierarchy": {
                "dynamicRegistration": true
            },
            "semanticTokens": {
                "dynamicRegistration": true,
                "tokenTypes": [
                    "namespace",
                    "type",
                    "class",
                    "enum",
                    "interface",
                    "struct",
                    "typeParameter",
                    "parameter",
                    "variable",
                    "property",
                    "enumMember",
                    "event",
                    "function",
                    "method",
                    "macro",
                    "keyword",
                    "modifier",
                    "comment",
                    "string",
                    "number",
                    "regexp",
                    "operator",
                    "decorator"
                ],
                "tokenModifiers": [
                    "declaration",
                    "definition",
                    "readonly",
                    "static",
                    "deprecated",
                    "abstract",
                    "async",
                    "modification",
                    "documentation",
                    "defaultLibrary"
                ],
                "formats": [
                    "relative"
                ],
                "requests": {
                    "range": true,
                    "full": {
                        "delta": true
                    }
                },
                "multilineTokenSupport": false,
                "overlappingTokenSupport": false,
                "serverCancelSupport": true,
                "augmentsSyntaxTokens": true
            },
            "linkedEditingRange": {
                "dynamicRegistration": true
            },
            "typeHierarchy": {
                "dynamicRegistration": true
            },
            "inlineValue": {
                "dynamicRegistration": true
            },
            "inlayHint": {
                "dynamicRegistration": true,
                "resolveSupport": {
                    "properties": [
                        "tooltip",
                        "textEdits",
                        "label.tooltip",
                        "label.location",
                        "label.command"
                    ]
                }
            },
            "diagnostic": {
                "dynamicRegistration": true,
                "relatedDocumentSupport": false
            }
        },
        "window": {
            "showMessage": {
                "messageActionItem": {
                    "additionalPropertiesSupport": true
                }
            },
            "showDocument": {
                "support": true
            },
            "workDoneProgress": true
        },
        "general": {
            "staleRequestSupport": {
                "cancel": true,
                "retryOnContentModified": [
                    "textDocument/semanticTokens/full",
                    "textDocument/semanticTokens/range",
                    "textDocument/semanticTokens/full/delta"
                ]
            },
            "regularExpressions": {
                "engine": "ECMAScript",
                "version": "ES2020"
            },
            "markdown": {
                "parser": "marked",
                "version": "1.1.0",
                "allowedTags": [
                    "ul",
                    "li",
                    "p",
                    "code",
                    "blockquote",
                    "ol",
                    "h1",
                    "h2",
                    "h3",
                    "h4",
                    "h5",
                    "h6",
                    "hr",
                    "em",
                    "pre",
                    "table",
                    "thead",
                    "tbody",
                    "tr",
                    "th",
                    "td",
                    "div",
                    "del",
                    "a",
                    "strong",
                    "br",
                    "img",
                    "span"
                ]
            },
            "positionEncodings": [
                "utf-16"
            ]
        },
        "notebookDocument": {
            "synchronization": {
                "dynamicRegistration": true,
                "executionSummarySupport": true
            }
        }
    },
    "initializationOptions": {
        "AutomaticWorkspaceInit": false
    },
    "trace": "verbose",
    "workspaceFolders": [
        {
            "uri": "file:///workspaces/test",
            "name": "test"
        }
    ]
}


[Info  - 6:02:39 PM] Connection to server got closed. Server will restart.
[Error - 6:02:39 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 6:02:39 PM] F# client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
...
```
those log messages repeat multiple times before giving up.

**Comment by TheAngryByrd** [comment]
Ugh I think this is another runtime bug with 6 https://github.com/dotnet/runtime/issues/76921#issuecomment-1305655056. 

Setting `DOTNET_GCHeapCount` higher than `1` seems to crash the process. Although I'm having trouble getting actual info out of LSP Client initializing process. @baronfel I tried adding `InitializationFailedHandler` and `ErrorHandler` to `LanguageClientOptions` but I kept getting some copyOfStruct error.

I can't reproduce this on dotnet 7.

**Comment by philipcraig** [comment]
> Ugh I think this is another runtime bug with 6 [dotnet/runtime#76921 (comment)](https://github.com/dotnet/runtime/issues/76921#issuecomment-1305655056).
> 
> Setting `DOTNET_GCHeapCount` higher than `1` seems to crash the process. Although I'm having trouble getting actual info out of LSP Client initializing process. @baronfel I tried adding `InitializationFailedHandler` and `ErrorHandler` to `LanguageClientOptions` but I kept getting some copyOfStruct error.
> 
> I can't reproduce this on dotnet 7.

Thanks. Will you continue to support dotnet 6 (and roll back the change) or will you drop dotnet 6 support?

**Comment by baronfel** [comment]
6 is LTS and supported by MS through 2024, so the reasonable thing for us to do here is to adjust our usage of the flag when on .Net 6.

**Comment by TheAngryByrd** [comment]
> 6 is LTS and supported by MS through 2024, so the reasonable thing for us to do here is to adjust our usage of the flag when on .Net 6.

Yeah we're gonna keep 6 around. I'd have to do more testing and see if it's more than just linux in devcontainers but that's a lot of setup. We'll probably just turn this off for net6 ,unless anyone else has time to see what the impact is and if there's a clever way to detect when we should turn this off. (Maybe some way with the `InitializationFailedHandler` or `ErrorHandler` but I need someone with a higher power level in fable to help me with this)

As a workaround I think you can set the `HeapCount` setting to 1 and it should work until we get another release out.

**Comment by baronfel** [comment]
> turn this off for net6

Totally agree here - by the time we're checking this setting we already have the SemVer for the selected SDK version, so it should be easy to just disregard it if required.  We should also document in the help text for the option that it only applies to .NET SDK 7+.
