### ISSUE TITLE
Typechecking not completing upon build and is preventing intellisense

### ISSUE THREAD

**Issue by sulky-penguin** [ionide/ionide-vscode-fsharp#1915]
### Describe the bug

Typechecking seems to get stuck upon initial build when opening an f# file and is preventing intellisense. Tried restarting vscode, reinstalling ionide, doublechecking the proj file. Can't seem to find a similar issue like this anywhere. Typechecking just continues to load in the screenshot below

### Steps to reproduce

1. Open Project
2. Open an .fs or .fsx file
3. Wait for building to get to typechecking

### Screenshots

<img width="454" alt="image" src="https://github.com/ionide/ionide-vscode-fsharp/assets/32361300/488df21d-353a-44b2-b1c3-76e2edc57cbe">

## Machine info
 - OS: Mac
 - .NET SDK version: 6.0.16
 - Ionide version: 7.9.0

**Comment by dburriss** [comment]
Experiencing the same, also on Mac. Tried the same workarounds. No luck.

**Comment by vanhanenjjv** [comment]
Same here.

**Comment by vanhanenjjv** [comment]
I installed an older version (7.5.4) of the extension and it seems to work fine.

**Comment by sulky-penguin** [comment]
> I installed an older version (7.5.4) of the extension and it seems to work fine.

Thank you! Didn't think to try that. I've downgraded and seems to be working again. Still haven't got to the bottom of why the most recent version isn't working it but happy with the workaround for now!

**Comment by pimbrouwers** [comment]
I can confirm that this is happening on my machine as well. Win 11 x64, dotnet 6.0.107, and vscode 1.82.1.6.

Has anyone tried to see if this is resolved in 7.12.1?

**Comment by baronfel** [comment]
@pimbrouwers can you also try using a more recent SDK? 7.0.4xx or the 8.0.100-rc1 would be ideal here.

**Comment by pimbrouwers** [comment]
Hey @baronfel!

I updated the referenced sdk in global.json to 7.0.100 and Ionide to 7.12.2. 

Happy to report no issues so far. Even with our 35 project monorepo.

**Comment by baronfel** [comment]
Hey, that's great to hear. MS fully supports using more recent SDKs to target older TFMs, so you should feel comfortable doing this - even updating to 8.x!

At the same time, it's mildly concerning that our net6.0 version of FSAC isn't working as expected anymore - we have test coverage but clearly something is going wrong on your system.

**Comment by TheAngryByrd** [comment]
@baronfel we do have a few closed issues about the combination of `arm`  `macos` and `net 6.0` having a lot of issues.

**Comment by pimbrouwers** [comment]
Thanks Chet & Jimmy. 

@baronfel I usually up the version when a new LTS version is released. But there is no reason I can't update the tooling more frequently.

**Comment by dburriss** [comment]
Updated Ionide extension and a restart and seems to be working again. Not sure if this was fixed or because of the act of updating?

**Comment by saykrikan-krap** [comment]
Hey everyone.

So I updated to 8.x rc today and I seem to be getting the same issue.

- OS: Windows 11
- .NET: 8.0.100-rc.1.23463.5
- Ionide: 7.12.5

Seems to be stuck at Typechecking. I tried uninstalling/reinstalling ionide to no avail

Looked at the F# output logs and see:

`Unhandled exception. System.AggregateException: One or more errors occurred. (Assembly: netstandard, full path: System.Collections.Generic.IEnumerable`1)
 ---> FSharp.Compiler.DiagnosticsLogger+UnresolvedPathReferenceNoRange: Assembly: netstandard, full path: System.Collections.Generic.IEnumerable`1
   at FSharp.Compiler.TypedTree.CcuThunk.EnsureDerefable(String[] requiringPath) in D:\a\_work\1\s\src\Compiler\TypedTree\TypedTree.fs:line 5526
   at FSharp.Compiler.TypedTree.NonLocalEntityRef.TryDeref(Boolean canError) in D:\a\_work\1\s\src\Compiler\TypedTree\TypedTree.fs:line 3379
   at FSharp.Compiler.TypedTree.EntityRef.Resolve(Boolean canError) in D:\a\_work\1\s\src\Compiler\TypedTree\TypedTree.fs:line 3462
   at FSharp.Compiler.TypedTree.EntityRef.get_Deref() in D:\a\_work\1\s\src\Compiler\TypedTree\TypedTree.fs:line 3474
   at FSharp.Compiler.CodeAnalysis.ItemKeyStoreBuilder.writeType(Boolean isStandalone, TType ty) in D:\a\_work\1\s\src\Compiler\Service\ItemKey.fs:line 235
   at FSharp.Compiler.CodeAnalysis.ItemKeyStoreBuilder.writeValRef(ValRef vref) in D:\a\_work\1\s\src\Compiler\Service\ItemKey.fs:line 299
   at FSharp.Compiler.CodeAnalysis.ItemKeyStoreBuilder.Write(Range m, Item item) in D:\a\_work\1\s\src\Compiler\Service\ItemKey.fs:line 339
   at <StartupCode$FSharp-Compiler-Service>.$IncrementalBuild.clo@343-478.Invoke(CapturedNameResolution cnr) in D:\a\_work\1\s\src\Compiler\Service\IncrementalBuild.fs:line 346
   at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source) in D:\a\_work\1\s\src\FSharp.Core\seq.fs:line 632
   at <StartupCode$FSharp-Compiler-Service>.$IncrementalBuild.clo@334-477.Invoke(Tuple`5 _arg6) in D:\a\_work\1\s\src\Compiler\Service\IncrementalBuild.fs:line 342
   at FSharp.Compiler.BuildGraph.Bind@61-1.Invoke(T x) in D:\a\_work\1\s\src\Compiler\Facilities\BuildGraph.fs:line 62
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, b result1, FSharpFunc`2 userCode) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 528
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 112
   --- End of inner exception stack trace ---
   at Microsoft.FSharp.Control.AsyncPrimitives.Start@1174-1.Invoke(ExceptionDispatchInfo edi) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 1174
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 112
   at <StartupCode$FSharp-Core>.$Async.clo@193-15.Invoke(Object o) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 195
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()`
