### ISSUE TITLE
2.7.1 Cannot read property 'document' of undefined: TypeError: Cannot read property 'document' of undefined

### ISSUE THREAD

**Issue by ctaggart** [ionide/ionide-vscode-fsharp#217]
I just installed 2.7.1 on my Mac and I'm getting this error:

```
Cannot read property 'document' of undefined: TypeError: Cannot read property 'document' of undefined
    at handlerOpen (/Users/cameron/.vscode/extensions/Ionide.Ionide-fsharp-2.7.1/Components/Linter.js:84:27)
    at /Users/cameron/.vscode/extensions/Ionide.Ionide-fsharp-2.7.1/Components/Linter.js:109:9
    at e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:5:6321)
    at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:5:14643)
    at t.$acceptActiveEditorAndVisibleEditors (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:12:12636)
    at t.$acceptTextEditorRemove (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:12:13041)
    at t.e.handle (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:11:11474)
    at s (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:8:2033)
    at p (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:8:2710)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
```

**Comment by ctaggart** [comment]
Apologies, upgrading Mono seemed to do the trick.

Mono JIT compiler version 4.6.1 (Stable 4.6.1.5/ef43c15 Tue Oct 18 11:06:44 BST 2016)
brew update
brew upgrade
Mono JIT compiler version 4.4.2 (Stable 4.4.2.11/f72fe45 Thu Aug 11 06:03:25 BST 2016)
