### ISSUE TITLE
Ionide in VsCode 2.9.0 stopped working on Windows for UNC path

### ISSUE THREAD

**Issue by stefan-akelius** [ionide/ionide-vscode-fsharp#273]
I use Windows 10 as a VirtualBox guest on a Macbook and and have configured my dev folders as permanent shared folders (They're network folders mapped to drive letters, e.g. `\\vboxsrv\dev` -> `E:\`). Until I upgraded to 2.9.0 Ionide worked fine but now it shows errors in the Developer Tools console in VsCode and does not recover whenever I open a folder on a UNC path. It still works fine for files that are saved in Windows directly, e.g. the Desktop.

```
Conflict detected, command `workbench.action.debug.run` cannot be triggered by ctrl+f5 due to fake.buildDefault
Conflict detected, command `cursorUpSelect` cannot be triggered by ctrl+shift+up due to fsharp.MoveFileUp
Conflict detected, command `cursorDownSelect` cannot be triggered by ctrl+shift+down due to fsharp.MoveFileDown
[File Watcher] System.ComponentModel.Win32Exception (0x80004005): Incorrect function
[Extension Host] Uncaught Exception:  TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
[Extension Host] TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at C:\Users\vs\.vscode\extensions\Ionide.Ionide-fsharp-2.9.0\node_modules\fable-core\fable-core.js:2176:30
    at Object.<anonymous> (C:\Users\vs\.vscode\extensions\Ionide.Ionide-fsharp-2.9.0\node_modules\fable-core\fable-core.js:1689:24)
    at C:\Users\vs\.vscode\extensions\Ionide.Ionide-fsharp-2.9.0\node_modules\fable-core\fable-core.js:1674:39
    at Object.<anonymous> (C:\Users\vs\.vscode\extensions\Ionide.Ionide-fsharp-2.9.0\node_modules\fable-core\fable-core.js:1689:24)
    at C:\Users\vs\.vscode\extensions\Ionide.Ionide-fsharp-2.9.0\node_modules\fable-core\fable-core.js:1674:39
    at Object.<anonymous> (C:\Users\vs\.vscode\extensions\Ionide.Ionide-fsharp-2.9.0\node_modules\fable-core\fable-core.js:1689:24)
    at Function.from (native)
    at mapResult (C:\Users\vs\.vscode\extensions\Ionide.Ionide-fsharp-2.9.0\Components\Errors.js:26:24)
    at C:\Users\vs\.vscode\extensions\Ionide.Ionide-fsharp-2.9.0\Components\Errors.js:114:20
    at Array.map (native)
    at C:\Users\vs\.vscode\extensions\Ionide.Ionide-fsharp-2.9.0\Components\Errors.js:113:22
    at handleNotification (C:\Users\vs\.vscode\extensions\Ionide.Ionide-fsharp-2.9.0\Components\Errors.js:116:7)
    at C:\Users\vs\.vscode\extensions\Ionide.Ionide-fsharp-2.9.0\Components\Errors.js:137:9
    at WebSocket.<anonymous> (C:\Users\vs\.vscode\extensions\Ionide.Ionide-fsharp-2.9.0\Core\LanguageService.js:359:13)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
Cannot read property 'Symbol(Symbol.iterator)' of undefined: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at C:\Users\vs\.vscode\extensions\Ionide.Ionide-fsharp-2.9.0\node_modules\fable-core\fable-core.js:2176:30
    at Object.<anonymous> (C:\Users\vs\.vscode\extensions\Ionide.Ionide-fsharp-2.9.0\node_modules\fable-core\fable-core.js:1689:24)
    at C:\Users\vs\.vscode\extensions\Ionide.Ionide-fsharp-2.9.0\node_modules\fable-core\fable-core.js:1674:39
    at Object.<anonymous> (C:\Users\vs\.vscode\extensions\Ionide.Ionide-fsharp-2.9.0\node_modules\fable-core\fable-core.js:1689:24)
    at C:\Users\vs\.vscode\extensions\Ionide.Ionide-fsharp-2.9.0\node_modules\fable-core\fable-core.js:1674:39
    at Object.<anonymous> (C:\Users\vs\.vscode\extensions\Ionide.Ionide-fsharp-2.9.0\node_modules\fable-core\fable-core.js:1689:24)
    at Function.from (native)
    at mapResult (C:\Users\vs\.vscode\extensions\Ionide.Ionide-fsharp-2.9.0\Components\Errors.js:26:24)
    at C:\Users\vs\.vscode\extensions\Ionide.Ionide-fsharp-2.9.0\Components\Errors.js:114:20
    at Array.map (native)
    at C:\Users\vs\.vscode\extensions\Ionide.Ionide-fsharp-2.9.0\Components\Errors.js:113:22
    at handleNotification (C:\Users\vs\.vscode\extensions\Ionide.Ionide-fsharp-2.9.0\Components\Errors.js:116:7)
    at C:\Users\vs\.vscode\extensions\Ionide.Ionide-fsharp-2.9.0\Components\Errors.js:137:9
    at WebSocket.<anonymous> (C:\Users\vs\.vscode\extensions\Ionide.Ionide-fsharp-2.9.0\Core\LanguageService.js:359:13)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
```

**Comment by Krzysztof-Cieslak** [comment]
Can you check it on `2.9.4` ?

**Comment by stefan-akelius** [comment]
It works again. But simply opening a valid .fsx file results in the following error in the Developer Tools console (but only there):

```
[Extension Host] rejected promise not handled within 1 second
Cannot read property 'Data' of null: TypeError: Cannot read property 'Data' of null
    at C:\Users\vs\.vscode\extensions\Ionide.Ionide-fsharp-2.9.0\Core\Project.js:144:14
    at C:\Users\vs\.vscode\extensions\Ionide.Ionide-fsharp-2.9.0\fable_external\Helpers-729269674.js:63:13
    at process._tickCallback (internal/process/next_tick.js:103:7)
```
