### ISSUE TITLE
Autocomplete does not work in v1.2.1

### ISSUE THREAD

**Issue by rexcfnghk** [ionide/ionide-vscode-fsharp#30]
My environment:

  - Windows 10 64-bit
  - Visual Studio 2015 installed

I did the following:

  1. Fresh install Visual Studio Code
  2. `Ctrl + Shift + P` to install ionide.fsharp
  3. Restart VS Code
  4. Open a new `.fsx` file

Autocomplete doesn't work so I navigate to `\.vscode\extensions\Ionide.Ionide-fsharp-1.2.1\bin` and do some digging myself. I found that when I tried to run `FsAutoComplete.Suave.exe`, it gave the following exception:

```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'FSharp.Core, Version=4.3.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A) ---> System.Security.SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)
   --- End of inner exception stack trace ---
   at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeAssembly assembly, RuntimeType caType)
   at System.Attribute.GetCustomAttributes(Assembly element, Type attributeType, Boolean inherit)
   at System.AppDomain.GetTargetFrameworkName()
```

Not sure if this is a bug or some configuration issue on my side.

**Comment by rexcfnghk** [comment]
I created a PR to bump `FSharp.Core` to `v.4.4.0.0` in #31. Please let me know if this is the correct way to handle this. My rationale is that since my computer does not have `v.4.3.1.0` of `FSharp.Core` installed, I must use a binding redirect to redirect all references to `v.4.4.0.0`.

**Comment by Krzysztof-Cieslak** [comment]
Suggested way is installing F# 3 - https://www.microsoft.com/en-us/download/details.aspx?id=44011. Changing binding reference would result in same error for PCs with only VS2013 / F#3 installed
