### ISSUE TITLE
codelens not working on windows 8.1

### ISSUE THREAD

**Issue by fbehrens** [ionide/ionide-vscode-fsharp#305]
Hi,
unfortunately this wonderful feature doesn't work on my windows 8.1.

Got `fsi` (Microsoft (R) F# Interactive version 14.0.23413.0) and `fsc`(Microsoft (R) F# Compiler version 14.0.23413.0) in `path`.

I deleted my `.vscode` direcory and have `ionide 2.13.0` installed as only extension. 

output from F# language Service 
```
[10:22:35 DEBUG] got FSAC line, is it the started message? true
[10:22:35 DEBUG] FSAC stdout: [I] 2016-12-12T09:22:35.5635322Z: listener started in 23.016 ms with binding 127.0.0.1:8966 [Suave.Tcp.tcpIpServer]

[10:22:35 INFO ] REQ (001) -> {lint}, File = "~\src\parser\parser.fs"
[10:22:35 INFO ] REQ (002) -> {project}, File = "~\src\parser\parser.fsproj"
[10:22:35 ERROR] RES (002) <- {project} ERROR in 28 ms: Error: Request failed with status code 502 Data=undefined
[10:22:35 ERROR] RES (001) <- {lint} ERROR in 33 ms: Error: Request failed with status code 502 Data=undefined
[10:22:36 INFO ] REQ (003) -> {parse}, File = "~\src\parser\parser.fs"
[10:22:36 ERROR] RES (003) <- {parse} ERROR in 14 ms: Error: Request failed with status code 502 Data=undefined
[10:22:46 INFO ] REQ (004) -> {project}, File = "~\src\parser\parser.fsproj"
[10:22:46 INFO ] REQ (005) -> {lint}, File = "~\src\parser\parser.fs"
[10:22:46 ERROR] RES (005) <- {lint} ERROR in 14 ms: Error: Request failed with status code 502 Data=undefined
[10:22:46 ERROR] RES (004) <- {project} ERROR in 16 ms: Error: Request failed with status code 502 Data=undefined
[10:22:46 INFO ] REQ (006) -> {tooltip}, File = "~\src\parser\parser.fs"
[10:22:46 ERROR] RES (006) <- {tooltip} ERROR in 16 ms: Error: Request failed with status code 502 Data=undefined
```

output for developer Console 
```
Conflict detected, command `cursorUpSelect` cannot be triggered by ctrl+shift+up due to fsharp.MoveFileUp
Conflict detected, command `cursorDownSelect` cannot be triggered by ctrl+shift+down due to fsharp.MoveFileDown
[Extension Host] Windows_NT
[Extension Host] [IONIDE-FSAC] got FSAC line, is it the started message? true
[Extension Host] [IONIDE-FSAC] FSAC stdout: [I] 2016-12-12T09:22:35.5635322Z: listener started in 23.016 ms with binding 127.0.0.1:8966 [Suave.Tcp.tcpIpServer]

[Extension Host] [IONIDE-FSAC] REQ (001) -> {lint}, File = "~\src\parser\parser.fs"
[Extension Host] [IONIDE-FSAC] REQ (002) -> {project}, File = "~\src\parser\parser.fsproj"
[Extension Host] [IONIDE-FSAC] RES (002) <- {project} ERROR in 28 ms: Error: Request failed with status code 502 Data=%O
[Extension Host] [IONIDE-FSAC] RES (001) <- {lint} ERROR in 33 ms: Error: Request failed with status code 502 Data=%O
[Extension Host] [IONIDE-FSAC] REQ (003) -> {parse}, File = "~\src\parser\parser.fs"
[Extension Host] [IONIDE-FSAC] RES (003) <- {parse} ERROR in 14 ms: Error: Request failed with status code 502 Data=%O
Request failed with status code 502: Error: Request failed with status code 502
    at createError (C:\Users\IMYNV\.vscode\extensions\Ionide.Ionide-fsharp-2.13.0\node_modules\axios\lib\core\createError.js:15:15)
    at settle (C:\Users\IMYNV\.vscode\extensions\Ionide.Ionide-fsharp-2.13.0\node_modules\axios\lib\core\settle.js:18:12)
    at IncomingMessage.handleStreamEnd (C:\Users\IMYNV\.vscode\extensions\Ionide.Ionide-fsharp-2.13.0\node_modules\axios\lib\adapters\http.js:186:11)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[Extension Host] rejected promise not handled within 1 second
[Extension Host] [IONIDE-FSAC] REQ (004) -> {project}, File = "~\src\parser\parser.fsproj"
[Extension Host] [IONIDE-FSAC] REQ (005) -> {lint}, File = "~\src\parser\parser.fs"
[Extension Host] [IONIDE-FSAC] RES (005) <- {lint} ERROR in 14 ms: Error: Request failed with status code 502 Data=%O
[Extension Host] [IONIDE-FSAC] RES (004) <- {project} ERROR in 16 ms: Error: Request failed with status code 502 Data=%O
[Extension Host] [IONIDE-FSAC] REQ (006) -> {tooltip}, File = "~\src\parser\parser.fs"
[Extension Host] [IONIDE-FSAC] RES (006) <- {tooltip} ERROR in 16 ms: Error: Request failed with status code 502 Data=%O
[Extension Host] rejected promise not handled within 1 second
Request failed with status code 502: Error: Request failed with status code 502
    at createError (C:\Users\IMYNV\.vscode\extensions\Ionide.Ionide-fsharp-2.13.0\node_modules\axios\lib\core\createError.js:15:15)
    at settle (C:\Users\IMYNV\.vscode\extensions\Ionide.Ionide-fsharp-2.13.0\node_modules\axios\lib\core\settle.js:18:12)
    at IncomingMessage.handleStreamEnd (C:\Users\IMYNV\.vscode\extensions\Ionide.Ionide-fsharp-2.13.0\node_modules\axios\lib\adapters\http.js:186:11)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[Extension Host] rejected promise not handled within 1 second
```

**Comment by Krzysztof-Cieslak** [comment]
Do you have `HTTP_PROXY` defined on this machine? It may be duplicate of #272. 

I'm sure FSAC is not returning 502 responses

**Comment by fbehrens** [comment]
Yep, and I can configure it away, :) Thanks 1000 times.
