### ISSUE TITLE
code completion, code lens stopped working

### ISSUE THREAD

**Issue by s952163** [ionide/ionide-vscode-fsharp#307]
This is the output from the developers tools' console:

```
[Extension Host] Windows_NT
extensionHost.ts:255 [Extension Host] vscode-icons is active!
extensionHost.ts:255 [Extension Host] [IONIDE-FSAC] got FSAC line, is it the started message? true
extensionHost.ts:255 [Extension Host] [IONIDE-FSAC] FSAC stdout: [I] 2016-12-12T23:44:05.8535716Z: listener started in 28.003 ms with binding 127.0.0.1:8313 [Suave.Tcp.tcpIpServer]

```

Then if I try to autocomplete or hover over some functions it will try parsing the file but:
 
```
[Extension Host] Error: connect ETIMEDOUT 66.155.9.169:443
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
```
and also this:

```
[Extension Host] [IONIDE-FSAC] RES (006) <- {tooltip} ERROR in 125615 ms: Error: read ECONNRESET Data=%O
3extensionHost.ts:255 [Extension Host] rejected promise not handled within 1 second
shell.ts:440 read ECONNRESET: Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at TCP.onread (net.js:564:26)e.onUnexpectedError @ shell.ts:440(anonymous function) @ shell.ts:353e.onUnexpectedError @ errors.ts:68r @ errors.ts:83t.onUnexpectedExtHostError @ mainThreadErrors.ts:13e.handle @ abstractThreadService.ts:34s @ ipcRemoteCom.ts:269f @ ipcRemoteCom.ts:226_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
extensionHost.ts:255 [Extension Host] [IONIDE-FSAC] RES (007) <- {symboluse} ERROR in 125363 ms: Error: read ECONNRESET Data=%O
extensionHost.ts:255 [Extension Host] [IONIDE-FSAC] RES (008) <- {tooltip} ERROR in 129856 ms: Error: read ECONNRESET Data=%O
extensionHost.ts:255 [Extension Host] [IONIDE-FSAC] RES (009) <- {project} ERROR in 127503 ms: Error: read ECONNRESET Data=%O
extensionHost.ts:255 [Extension Host] [IONIDE-FSAC] RES (010) <- {lint} ERROR in 127502 ms: Error: read ECONNRESET Data=%O
```

**Comment by Krzysztof-Cieslak** [comment]
I'm guessing it's same issue as #272. Closing this as duplicate.

**Comment by s952163** [comment]
yes, correct. unsetting the HTTP and HTTPS variables in the shell brings back codelens.
