### ISSUE TITLE
Doesn't find reference to Hopac/System.Diagnostics

### ISSUE THREAD

**Issue by haf** [ionide/ionide-vscode-fsharp#308]
<img width="1440" alt="screen shot 2016-12-13 at 10 10 32" src="https://cloud.githubusercontent.com/assets/193115/21134255/362f5358-c11d-11e6-955c-36dd17bf3c39.png">

Repro:

 1. Download logary master (2016-12-13)
 2. `bundle exec rake` once to compile it; you can also try with `DEBUG=true` before `rake` to build in Debug mode, but it doesn't change anything afaik.
 3. Open `Common.fs`, see the errors for `Hopac` and `System.Diagnostics`.

```
➜  logary git:(master) mono --version
Mono JIT compiler version 4.6.2 (mono-4.6.0-branch/08fd525 Thu Nov 10 20:28:28 EST 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  x86
	Disabled:      none
	Misc:          softdebug
	LLVM:          yes(3.6.0svn-mono-master/8b1520c)
	GC:            sgen
```

Console log in screenshot is the following:

```
keybindingResolver.ts:190Conflict detected, command `workbench.action.debug.run` cannot be triggered by cmd+f5 due to fake.buildDefault
2016-12-13 10:01:59.474 keybindingResolver.ts:190Conflict detected, command `selectNextSuggestion` cannot be triggered by ctrl+n due to extension.vim_ctrl+n
2016-12-13 10:01:59.474 keybindingResolver.ts:190Conflict detected, command `selectPrevSuggestion` cannot be triggered by ctrl+p due to extension.vim_ctrl+p
2016-12-13 10:03:14.137 extensionHost.ts:255[Extension Host] Uncaught Exception:  TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefinedI.logExtensionHostMessage @ extensionHost.ts:255
2016-12-13 10:03:14.138 extensionHost.ts:255[Extension Host] TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at /Users/h/.vscode/extensions/Ionide.Ionide-fsharp-2.12.2/node_modules/fable-core/fable-core.js:2176:30
    at Object.<anonymous> (/Users/h/.vscode/extensions/Ionide.Ionide-fsharp-2.12.2/node_modules/fable-core/fable-core.js:1689:24)
    at /Users/h/.vscode/extensions/Ionide.Ionide-fsharp-2.12.2/node_modules/fable-core/fable-core.js:1674:39
    at Object.<anonymous> (/Users/h/.vscode/extensions/Ionide.Ionide-fsharp-2.12.2/node_modules/fable-core/fable-core.js:1689:24)
    at /Users/h/.vscode/extensions/Ionide.Ionide-fsharp-2.12.2/node_modules/fable-core/fable-core.js:1674:39
    at Object.<anonymous> (/Users/h/.vscode/extensions/Ionide.Ionide-fsharp-2.12.2/node_modules/fable-core/fable-core.js:1689:24)
    at Function.from (native)
    at mapResult (/Users/h/.vscode/extensions/Ionide.Ionide-fsharp-2.12.2/Components/Errors.js:24:24)
    at /Users/h/.vscode/extensions/Ionide.Ionide-fsharp-2.12.2/Components/Errors.js:133:20
    at Array.map (native)
    at /Users/h/.vscode/extensions/Ionide.Ionide-fsharp-2.12.2/Components/Errors.js:132:22
    at handleNotification (/Users/h/.vscode/extensions/Ionide.Ionide-fsharp-2.12.2/Components/Errors.js:135:7)
    at /Users/h/.vscode/extensions/Ionide.Ionide-fsharp-2.12.2/Components/Errors.js:158:9
    at WebSocket.<anonymous> (/Users/h/.vscode/extensions/Ionide.Ionide-fsharp-2.12.2/Core/LanguageService.js:364:13)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)I.logExtensionHostMessage @ extensionHost.ts:255
2016-12-13 10:03:14.138 shell.ts:440Cannot read property 'Symbol(Symbol.iterator)' of undefined: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at /Users/h/.vscode/extensions/Ionide.Ionide-fsharp-2.12.2/node_modules/fable-core/fable-core.js:2176:30
    at Object.<anonymous> (/Users/h/.vscode/extensions/Ionide.Ionide-fsharp-2.12.2/node_modules/fable-core/fable-core.js:1689:24)
    at /Users/h/.vscode/extensions/Ionide.Ionide-fsharp-2.12.2/node_modules/fable-core/fable-core.js:1674:39
    at Object.<anonymous> (/Users/h/.vscode/extensions/Ionide.Ionide-fsharp-2.12.2/node_modules/fable-core/fable-core.js:1689:24)
    at /Users/h/.vscode/extensions/Ionide.Ionide-fsharp-2.12.2/node_modules/fable-core/fable-core.js:1674:39
    at Object.<anonymous> (/Users/h/.vscode/extensions/Ionide.Ionide-fsharp-2.12.2/node_modules/fable-core/fable-core.js:1689:24)
    at Function.from (native)
    at mapResult (/Users/h/.vscode/extensions/Ionide.Ionide-fsharp-2.12.2/Components/Errors.js:24:24)
    at /Users/h/.vscode/extensions/Ionide.Ionide-fsharp-2.12.2/Components/Errors.js:133:20
    at Array.map (native)
    at /Users/h/.vscode/extensions/Ionide.Ionide-fsharp-2.12.2/Components/Errors.js:132:22
    at handleNotification (/Users/h/.vscode/extensions/Ionide.Ionide-fsharp-2.12.2/Components/Errors.js:135:7)
    at /Users/h/.vscode/extensions/Ionide.Ionide-fsharp-2.12.2/Components/Errors.js:158:9
    at WebSocket.<anonymous> (/Users/h/.vscode/extensions/Ionide.Ionide-fsharp-2.12.2/Core/LanguageService.js:364:13)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)e.onUnexpectedError @ shell.ts:440
2016-12-13 10:03:16.174 nativeKeymap.ts:316'KeyboardEvent.keyIdentifier' is deprecated and will be removed in M53, around September 2016. See https://www.chromestatus.com/features/5316065118650368 for more details.
2016-12-13 10:05:27.787 shell.ts:440Cannot read property 'Data' of null: TypeError: Cannot read property 'Data' of null
    at /Users/h/.vscode/extensions/Ionide.Ionide-fsharp-2.12.2/Components/CodeLens.js:149:50
    at process._tickCallback (internal/process/next_tick.js:103:7) (2 errors in total)e.onUnexpectedError @ shell.ts:440
2016-12-13 10:05:27.788 winjs.base.js:45WARNING: Promise with no error callback:90
2016-12-13 10:05:27.788 winjs.base.js:46Object
2016-12-13 10:05:42.828 shell.ts:440Cannot read property 'Data' of null: TypeError: Cannot read property 'Data' of null
    at /Users/h/.vscode/extensions/Ionide.Ionide-fsharp-2.12.2/Components/CodeLens.js:149:50
    at process._tickCallback (internal/process/next_tick.js:103:7) (2 errors in total)e.onUnexpectedError @ shell.ts:440
2016-12-13 10:05:42.828 winjs.base.js:45WARNING: Promise with no error callback:99
2016-12-13 10:05:42.828 winjs.base.js:46Object
2016-12-13 10:05:45.145 shell.ts:440Cannot read property 'Data' of null: TypeError: Cannot read property 'Data' of null
    at /Users/h/.vscode/extensions/Ionide.Ionide-fsharp-2.12.2/Components/CodeLens.js:149:50
    at process._tickCallback (internal/process/next_tick.js:103:7) (2 errors in total)e.onUnexpectedError @ shell.ts:440
2016-12-13 10:05:45.146 winjs.base.js:45WARNING: Promise with no error callback:108
2016-12-13 10:05:45.146 winjs.base.js:46Object
2016-12-13 10:05:47.806 shell.ts:440Cannot read property 'Data' of null: TypeError: Cannot read property 'Data' of null
    at /Users/h/.vscode/extensions/Ionide.Ionide-fsharp-2.12.2/Components/CodeLens.js:149:50
    at process._tickCallback (internal/process/next_tick.js:103:7)e.onUnexpectedError @ shell.ts:440
2016-12-13 10:05:47.806 winjs.base.js:45WARNING: Promise with no error callback:113
2016-12-13 10:05:47.806 winjs.base.js:46Object
2016-12-13 10:05:48.717 winjs.base.js:45WARNING: Promise with no error callback:118
2016-12-13 10:05:48.718 winjs.base.js:46Object
2016-12-13 10:05:49.497 shell.ts:440Cannot read property 'Data' of null: TypeError: Cannot read property 'Data' of null
    at /Users/h/.vscode/extensions/Ionide.Ionide-fsharp-2.12.2/Components/CodeLens.js:149:50
    at process._tickCallback (internal/process/next_tick.js:103:7)e.onUnexpectedError @ shell.ts:440
2016-12-13 10:05:49.497 winjs.base.js:45WARNING: Promise with no error callback:123
2016-12-13 10:05:49.497 winjs.base.js:46Object
2016-12-13 10:09:38.660 extensionHost.ts:255[Extension Host] Uncaught Exception:  TypeError: Cannot read property 'document' of nullI.logExtensionHostMessage @ extensionHost.ts:255
2016-12-13 10:09:38.660 extensionHost.ts:255[Extension Host] TypeError: Cannot read property 'document' of null
    at e.get [as document] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:11:15495)
    at /Users/h/.vscode/extensions/Ionide.Ionide-fsharp-2.12.2/Components/QuickInfo.js:20:32
    at handle_ (/Users/h/.vscode/extensions/Ionide.Ionide-fsharp-2.12.2/Components/QuickInfo.js:64:6)
    at Timeout._onTimeout (/Users/h/.vscode/extensions/Ionide.Ionide-fsharp-2.12.2/Components/QuickInfo.js:83:16)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)I.logExtensionHostMessage @ extensionHost.ts:255
2016-12-13 10:09:38.661 shell.ts:440Cannot read property 'document' of null: TypeError: Cannot read property 'document' of null
    at e.get [as document] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:11:15495)
    at /Users/h/.vscode/extensions/Ionide.Ionide-fsharp-2.12.2/Components/QuickInfo.js:20:32
    at handle_ (/Users/h/.vscode/extensions/Ionide.Ionide-fsharp-2.12.2/Components/QuickInfo.js:64:6)
    at Timeout._onTimeout (/Users/h/.vscode/extensions/Ionide.Ionide-fsharp-2.12.2/Components/QuickInfo.js:83:16)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)e.onUnexpectedError @ shell.ts:440
```

**Comment by Krzysztof-Cieslak** [comment]
Can reproduce this.

Looks like something go wrong with cracking `.fsproj` file
![image](https://cloud.githubusercontent.com/assets/5427083/21138473/851b60b8-c12e-11e6-9237-d9b34949a93c.png)

Looks like none of references added by Paket are recognized - FSharp.Core shown on screen is GAC'ed version.

**Comment by Krzysztof-Cieslak** [comment]
Changing https://github.com/logary/logary/blob/master/src/metrics/Logary.Metrics.WinPerfCounters/Logary.Metrics.WinPerfCounters.fsproj#L4 to `<Configuration Condition=" '$(Configuration)' == '' ">Release</Configuration>` fixes problem.

We execute ProjectCracker without providing it any additional variables so default variables are used. In case of your project file `Debug` was used as fallback value. At the same time you haven't got `PropertyGroup` defining `OutputPath`, `DocumentationFile` etc. which would be active when ` '$(Configuration)` was set to `Debug` (since only one you have have `Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ".

It was building because in build script you always execute `Release` task for `MsBuild` / `xbuild`

**Comment by cloudRoutine** [comment]
you can use settings parameterized with properties e.g. 
`<OutputPath>bin\$(Configuration)</OutputPath>`
`<DocumentationFile>bin\$(Configuration)\$(AssemblyName).xml</DocumentationFile>`
outside of conditional blocks to avoid this issue in the future.

**Comment by haf** [comment]
Thank you
