### ISSUE TITLE
Fsx goodies not working after upgrade to 2.23.6

### ISSUE THREAD

**Issue by pmbanka** [ionide/ionide-vscode-fsharp#384]
I have just upgraded Ionide to 2.23.6 and in my fsx scripts stuff like intellisense, tooltips, errors etc. are not showing. Trying to send something to FSI fails with `command 'fsi.SendSelection' not found`.

I tried reinstalling ionide-fsharp, but it didn't change anything.

Opening dev tools reveals an error:

```
[Extension Host] vscode-icons is active!
extensionHost.ts:282[Extension Host] Activating extension `Ionide.Ionide-fsharp` failed: Cannot read property 'extensionPath' of undefined.d.logExtensionHostMessage @ extensionHost.ts:282
extensionHost.ts:282[Extension Host] Activating extension `Ionide.Ionide-fsharp` failed:  Cannot read property 'extensionPath' of undefinedd.logExtensionHostMessage @ extensionHost.ts:282
extensionHost.ts:282[Extension Host] Here is the error stack:  TypeError: Cannot read property 'extensionPath' of undefined
    at Object.getPluginPath (D:\Users\pawel.banka\.vscode\extensions\Ionide.Ionide-fsharp-2.23.6\fable_external\Helpers-1977695102.js:107:15)
    at D:\Users\pawel.banka\.vscode\extensions\Ionide.Ionide-fsharp-2.23.6\Components\Expecto.js:218:47
    at Object.<anonymous> (D:\Users\pawel.banka\.vscode\extensions\Ionide.Ionide-fsharp-2.23.6\Components\Expecto.js:224:2)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Function.o._load (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:15:19228)
    at Module.require (module.js:483:17)
mainThreadExtensionService.ts:110Activating extension `Ionide.Ionide-fsharp` failed: Cannot read property 'extensionPath' of undefined.t.$localShowMessage @ mainThreadExtensionService.ts:110
```

**Comment by pmbanka** [comment]
VSCode is on latest version:

![image](https://cloud.githubusercontent.com/assets/9840334/23530614/c775f4de-ffa2-11e6-98d6-06b0fa01cc08.png)

**Comment by Krzysztof-Cieslak** [comment]
Please try `2.23.7`
