### ISSUE TITLE
Unable to ./build.sh on macOS Sierra

### ISSUE THREAD

**Issue by Danl2620** [ionide/ionide-vscode-fsharp#506]
I can't build ionide currently. I'm on macOS Sierra 10.12.6. Here is the full log:

```
Dans-iMac:ionide-vscode-fsharp danl$ ./build.sh 
Checking Paket version (downloading latest stable)...
Paket.exe 5.89.0 is up to date.
Paket version 5.89.0
Performance:
 - Disk IO: 42 milliseconds
 - Runtime: 1 second
Building project with version: LocalBuild
Shortened DependencyGraph for Target Default:
<== Default
   <== RunScript
      <== Clean

The running order is:
  - Clean
  - RunScript
  - Default
Running build with 1 worker
Starting Target: Clean 
Deleting contents of ./temp
Finished Target: Clean
Starting Target: RunScript (==> Clean, Clean)
npm install
npm run build

> Ionide-fsharp@2.33.2 prebuild /Users/danl/proj/ionide-vscode-fsharp/release
> npm update


> Ionide-fsharp@2.33.2 build /Users/danl/proj/ionide-vscode-fsharp/release
> fable ../src/Ionide.FSharp.fsproj -o ../release -m commonjs --verbose

Fable F# to JS compiler version 0.6.15

PROJECT FILE: /Users/danl/proj/ionide-vscode-fsharp/src/Ionide.FSharp.fsproj
OUTPUT DIR: /Users/danl/proj/ionide-vscode-fsharp/release
WORKING DIR: /Users/danl/proj/ionide-vscode-fsharp/src

FABLE COMMAND: mono /Users/danl/proj/ionide-vscode-fsharp/release/node_modules/fable-compiler/bin/Fable.Client.Node.exe --projFile Ionide.FSharp.fsproj --copyExt true

fable-compiler 0.6.15: Start compilation...

F# COMPILER OPTIONS:
--define:FABLE_COMPILER

ERROR: Build was not evaluated, expected the results to be ready after 'Eval'.
  at Microsoft.FSharp.Compiler.IncrementalBuilder.GetCheckResultsAndImplementationsForProject () [0x0002b] in <57adff7fddab8ea7a74503837fffad57>:0 
  at Microsoft.FSharp.Compiler.SourceCodeServices.BackgroundCompiler.ParseAndCheckProjectImpl (Microsoft.FSharp.Compiler.SourceCodeServices.FSharpProjectOptions options) [0x00045] in <57adff7fddab8ea7a74503837fffad57>:0 
  at <StartupCode$FSharp-Compiler-Service>.$Service+ParseAndCheckProject@2520.Invoke (System.Threading.CancellationToken _ct) [0x00001] in <57adff7fddab8ea7a74503837fffad57>:0 
  at <StartupCode$FSharp-Compiler-Service>.$Reactor+EnqueueAndAwaitOpAsync@139-2[T].Invoke (Microsoft.FSharp.Core.Unit unitVar0) [0x00008] in <57adff7fddab8ea7a74503837fffad57>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <6121bbff18d447c19175abd75faed747>:0 
  at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a] (Microsoft.FSharp.Control.AsyncBuilderImpl+Result`1[T] res) [0x00030] in <561d4e1d904cf4daa74503831d4e1d56>:0 
  at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a] (System.Threading.CancellationToken token, Microsoft.FSharp.Control.FSharpAsync`1[T] computation, Microsoft.FSharp.Core.FSharpOption`1[T] timeout) [0x000a3] in <561d4e1d904cf4daa74503831d4e1d56>:0 
  at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T] (Microsoft.FSharp.Control.FSharpAsync`1[T] computation, Microsoft.FSharp.Core.FSharpOption`1[T] timeout, Microsoft.FSharp.Core.FSharpOption`1[T] cancellationToken) [0x00071] in <561d4e1d904cf4daa74503831d4e1d56>:0 
  at Fable.Client.Node.Main.parseFSharpProject (Fable.ICompiler com, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpChecker checker, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpProjectOptions projOptions) [0x00009] in <57fb981855d8c922a74503831898fb57>:0 
  at Fable.Client.Node.Main.compile (Fable.ICompiler com, Microsoft.FSharp.Compiler.SourceCodeServices.FSharpChecker checker, Fable.FSharp2Fable.Compiler+FSProjectInfo projInfo) [0x000d3] in <57fb981855d8c922a74503831898fb57>:0 

npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! Ionide-fsharp@2.33.2 build: `fable ../src/Ionide.FSharp.fsproj -o ../release -m commonjs --verbose`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Ionide-fsharp@2.33.2 build script 'fable ../src/Ionide.FSharp.fsproj -o ../release -m commonjs --verbose'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Ionide-fsharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     fable ../src/Ionide.FSharp.fsproj -o ../release -m commonjs --verbose
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Ionide-fsharp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Ionide-fsharp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/danl/proj/ionide-vscode-fsharp/release/npm-debug.log
Running build failed.
Error:
System.Exception: Error while running 'npm' with args: run build
  at FSI_0005.Build+run@49-3.Invoke (System.String message) [0x00001] in <a40ce6850e4049f8b87d7ce1e0cc0d30>:0 
  at Microsoft.FSharp.Core.PrintfImpl+StringPrintfEnv`1[TResult].Finalize () [0x00012] in <5893d081904cf4daa745038381d09358>:0 
  at Microsoft.FSharp.Core.PrintfImpl+Final2@235[TState,TResidue,TResult,A,B].Invoke (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] env, A a, B b) [0x0005a] in <5893d081904cf4daa745038381d09358>:0 
  at Microsoft.FSharp.Core.OptimizedClosures+Invoke@3266-1[T2,T3,TResult,T1].Invoke (T2 u, T3 v) [0x00001] in <5893d081904cf4daa745038381d09358>:0 
  at Microsoft.FSharp.Core.OptimizedClosures+Invoke@3253[T2,TResult,T1].Invoke (T2 u) [0x00001] in <5893d081904cf4daa745038381d09358>:0 
  at FSI_0005.Build+run@49-5.Invoke (System.String arg20) [0x00001] in <a40ce6850e4049f8b87d7ce1e0cc0d30>:0 
  at Microsoft.FSharp.Core.FSharpFunc`2[T,TResult].InvokeFast[V] (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] func, T arg1, TResult arg2) [0x0001f] in <5893d081904cf4daa745038381d09358>:0 
  at FSI_0005.Build.run (System.String cmd, System.String args, System.String dir) [0x00068] in <a40ce6850e4049f8b87d7ce1e0cc0d30>:0 
  at FSI_0005.Build+clo@80-1.Invoke (Microsoft.FSharp.Core.Unit _arg2) [0x0001b] in <a40ce6850e4049f8b87d7ce1e0cc0d30>:0 
  at Fake.TargetHelper+targetFromTemplate@209-1[a].Invoke (Microsoft.FSharp.Core.Unit unitVar0) [0x00001] in <597b0a4fccf1c534a74503834f0a7b59>:0 
  at Fake.TargetHelper.runSingleTarget (Fake.TargetHelper+TargetTemplate`1[a] target) [0x0004b] in <597b0a4fccf1c534a74503834f0a7b59>:0 

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target      Duration
------      --------
Clean       00:00:00.0043154
RunScript   Failure
Total:      00:00:05.1001813
---------------------------------------------------------------------
Status:     Failure
---------------------------------------------------------------------
---------------------------------------------------------------------
  1) System.Exception: Error while running 'npm' with args: run build
  at FSI_0005.Build+run@49-3.Invoke (System.String message) [0x00001] in <a40ce6850e4049f8b87d7ce1e0cc0d30>:0 
  at Microsoft.FSharp.Core.PrintfImpl+StringPrintfEnv`1[TResult].Finalize () [0x00012] in <5893d081904cf4daa745038381d09358>:0 
  at Microsoft.FSharp.Core.PrintfImpl+Final2@235[TState,TResidue,TResult,A,B].Invoke (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] env, A a, B b) [0x0005a] in <5893d081904cf4daa745038381d09358>:0 
  at Microsoft.FSharp.Core.OptimizedClosures+Invoke@3266-1[T2,T3,TResult,T1].Invoke (T2 u, T3 v) [0x00001] in <5893d081904cf4daa745038381d09358>:0 
  at Microsoft.FSharp.Core.OptimizedClosures+Invoke@3253[T2,TResult,T1].Invoke (T2 u) [0x00001] in <5893d081904cf4daa745038381d09358>:0 
  at FSI_0005.Build+run@49-5.Invoke (System.String arg20) [0x00001] in <a40ce6850e4049f8b87d7ce1e0cc0d30>:0 
  at Microsoft.FSharp.Core.FSharpFunc`2[T,TResult].InvokeFast[V] (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] func, T arg1, TResult arg2) [0x0001f] in <5893d081904cf4daa745038381d09358>:0 
  at FSI_0005.Build.run (System.String cmd, System.String args, System.String dir) [0x00068] in <a40ce6850e4049f8b87d7ce1e0cc0d30>:0 
  at FSI_0005.Build+clo@80-1.Invoke (Microsoft.FSharp.Core.Unit _arg2) [0x0001b] in <a40ce6850e4049f8b87d7ce1e0cc0d30>:0 
  at Fake.TargetHelper+targetFromTemplate@209-1[a].Invoke (Microsoft.FSharp.Core.Unit unitVar0) [0x00001] in <597b0a4fccf1c534a74503834f0a7b59>:0 
  at Fake.TargetHelper.runSingleTarget (Fake.TargetHelper+TargetTemplate`1[a] target) [0x0004b] in <597b0a4fccf1c534a74503834f0a7b59>:0 
---------------------------------------------------------------------
Dans-iMac:ionide-vscode-fsharp danl$ 
```

And here is the contents of ` /Users/danl/proj/ionide-vscode-fsharp/release/npm-debug.log`:

```
0 info it worked if it ends with ok
1 verbose cli [ '/nix/store/j3z060vwl83gapvjqpsnmyffhdcjj0ms-nodejs-6.11.1/bin/node',
1 verbose cli   '/Users/danl/.nix-profile/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.10.10
3 info using node@v6.11.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle Ionide-fsharp@2.33.2~prebuild: Ionide-fsharp@2.33.2
6 verbose lifecycle Ionide-fsharp@2.33.2~prebuild: unsafe-perm in lifecycle true
7 verbose lifecycle Ionide-fsharp@2.33.2~prebuild: PATH: /nix/store/j3z060vwl83gapvjqpsnmyffhdcjj0ms-nodejs-6.11.1/lib/node_modules/npm/bin/node-gyp-bin:/Users/danl/proj/ionide-vscode-fsharp/release/node_modules/.bin:/nix/store/j3z060vwl83gapvjqpsnmyffhdcjj0ms-nodejs-6.11.1/bin:/Users/danl/.opam/system/bin:/Users/danl/.nix-profile/bin:/Users/danl/.nix-profile/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands
8 verbose lifecycle Ionide-fsharp@2.33.2~prebuild: CWD: /Users/danl/proj/ionide-vscode-fsharp/release
9 silly lifecycle Ionide-fsharp@2.33.2~prebuild: Args: [ '-c', 'npm update' ]
10 silly lifecycle Ionide-fsharp@2.33.2~prebuild: Returned: code: 0  signal: null
11 info lifecycle Ionide-fsharp@2.33.2~build: Ionide-fsharp@2.33.2
12 verbose lifecycle Ionide-fsharp@2.33.2~build: unsafe-perm in lifecycle true
13 verbose lifecycle Ionide-fsharp@2.33.2~build: PATH: /nix/store/j3z060vwl83gapvjqpsnmyffhdcjj0ms-nodejs-6.11.1/lib/node_modules/npm/bin/node-gyp-bin:/Users/danl/proj/ionide-vscode-fsharp/release/node_modules/.bin:/nix/store/j3z060vwl83gapvjqpsnmyffhdcjj0ms-nodejs-6.11.1/bin:/Users/danl/.opam/system/bin:/Users/danl/.nix-profile/bin:/Users/danl/.nix-profile/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands
14 verbose lifecycle Ionide-fsharp@2.33.2~build: CWD: /Users/danl/proj/ionide-vscode-fsharp/release
15 silly lifecycle Ionide-fsharp@2.33.2~build: Args: [ '-c',
15 silly lifecycle   'fable ../src/Ionide.FSharp.fsproj -o ../release -m commonjs --verbose' ]
16 silly lifecycle Ionide-fsharp@2.33.2~build: Returned: code: 1  signal: null
17 info lifecycle Ionide-fsharp@2.33.2~build: Failed to exec build script
18 verbose stack Error: Ionide-fsharp@2.33.2 build: `fable ../src/Ionide.FSharp.fsproj -o ../release -m commonjs --verbose`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (/nix/store/j3z060vwl83gapvjqpsnmyffhdcjj0ms-nodejs-6.11.1/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
18 verbose stack     at emitTwo (events.js:106:13)
18 verbose stack     at EventEmitter.emit (events.js:191:7)
18 verbose stack     at ChildProcess.<anonymous> (/nix/store/j3z060vwl83gapvjqpsnmyffhdcjj0ms-nodejs-6.11.1/lib/node_modules/npm/lib/utils/spawn.js:40:14)
18 verbose stack     at emitTwo (events.js:106:13)
18 verbose stack     at ChildProcess.emit (events.js:191:7)
18 verbose stack     at maybeClose (internal/child_process.js:891:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
19 verbose pkgid Ionide-fsharp@2.33.2
20 verbose cwd /Users/danl/proj/ionide-vscode-fsharp/release
21 error Darwin 16.7.0
22 error argv "/nix/store/j3z060vwl83gapvjqpsnmyffhdcjj0ms-nodejs-6.11.1/bin/node" "/Users/danl/.nix-profile/bin/npm" "run" "build"
23 error node v6.11.1
24 error npm  v3.10.10
25 error code ELIFECYCLE
26 error Ionide-fsharp@2.33.2 build: `fable ../src/Ionide.FSharp.fsproj -o ../release -m commonjs --verbose`
26 error Exit status 1
27 error Failed at the Ionide-fsharp@2.33.2 build script 'fable ../src/Ionide.FSharp.fsproj -o ../release -m commonjs --verbose'.
27 error Make sure you have the latest version of node.js and npm installed.
27 error If you do, this is most likely a problem with the Ionide-fsharp package,
27 error not with npm itself.
27 error Tell the author that this fails on your system:
27 error     fable ../src/Ionide.FSharp.fsproj -o ../release -m commonjs --verbose
27 error You can get information on how to open an issue for this project with:
27 error     npm bugs Ionide-fsharp
27 error Or if that isn't available, you can get their info via:
27 error     npm owner ls Ionide-fsharp
27 error There is likely additional logging output above.
28 verbose exit [ 1, true ]
```

Likely has something to do with my Nix version of nodejs/npm.

**Comment by Krzysztof-Cieslak** [comment]
Please post also `npm-debug.log`

**Comment by Danl2620** [comment]
Ah, yes here it is:

`0 info it worked if it ends with ok
1 verbose cli [ '/nix/store/j3z060vwl83gapvjqpsnmyffhdcjj0ms-nodejs-6.11.1/bin/node',
1 verbose cli   '/Users/danl/.nix-profile/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.10.10
3 info using node@v6.11.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle Ionide-fsharp@2.33.2~prebuild: Ionide-fsharp@2.33.2
6 verbose lifecycle Ionide-fsharp@2.33.2~prebuild: unsafe-perm in lifecycle true
7 verbose lifecycle Ionide-fsharp@2.33.2~prebuild: PATH: /nix/store/j3z060vwl83gapvjqpsnmyffhdcjj0ms-nodejs-6.11.1/lib/node_modules/npm/bin/node-gyp-bin:/Users/danl/proj/ionide-vscode-fsharp/release/node_modules/.bin:/nix/store/j3z060vwl83gapvjqpsnmyffhdcjj0ms-nodejs-6.11.1/bin:/Users/danl/.opam/system/bin:/Users/danl/.nix-profile/bin:/Users/danl/.nix-profile/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands
8 verbose lifecycle Ionide-fsharp@2.33.2~prebuild: CWD: /Users/danl/proj/ionide-vscode-fsharp/release
9 silly lifecycle Ionide-fsharp@2.33.2~prebuild: Args: [ '-c', 'npm update' ]
10 silly lifecycle Ionide-fsharp@2.33.2~prebuild: Returned: code: 0  signal: null
11 info lifecycle Ionide-fsharp@2.33.2~build: Ionide-fsharp@2.33.2
12 verbose lifecycle Ionide-fsharp@2.33.2~build: unsafe-perm in lifecycle true
13 verbose lifecycle Ionide-fsharp@2.33.2~build: PATH: /nix/store/j3z060vwl83gapvjqpsnmyffhdcjj0ms-nodejs-6.11.1/lib/node_modules/npm/bin/node-gyp-bin:/Users/danl/proj/ionide-vscode-fsharp/release/node_modules/.bin:/nix/store/j3z060vwl83gapvjqpsnmyffhdcjj0ms-nodejs-6.11.1/bin:/Users/danl/.opam/system/bin:/Users/danl/.nix-profile/bin:/Users/danl/.nix-profile/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands
14 verbose lifecycle Ionide-fsharp@2.33.2~build: CWD: /Users/danl/proj/ionide-vscode-fsharp/release
15 silly lifecycle Ionide-fsharp@2.33.2~build: Args: [ '-c',
15 silly lifecycle   'fable ../src/Ionide.FSharp.fsproj -o ../release -m commonjs --verbose' ]
16 silly lifecycle Ionide-fsharp@2.33.2~build: Returned: code: 1  signal: null
17 info lifecycle Ionide-fsharp@2.33.2~build: Failed to exec build script
18 verbose stack Error: Ionide-fsharp@2.33.2 build: `fable ../src/Ionide.FSharp.fsproj -o ../release -m commonjs --verbose`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (/nix/store/j3z060vwl83gapvjqpsnmyffhdcjj0ms-nodejs-6.11.1/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
18 verbose stack     at emitTwo (events.js:106:13)
18 verbose stack     at EventEmitter.emit (events.js:191:7)
18 verbose stack     at ChildProcess.<anonymous> (/nix/store/j3z060vwl83gapvjqpsnmyffhdcjj0ms-nodejs-6.11.1/lib/node_modules/npm/lib/utils/spawn.js:40:14)
18 verbose stack     at emitTwo (events.js:106:13)
18 verbose stack     at ChildProcess.emit (events.js:191:7)
18 verbose stack     at maybeClose (internal/child_process.js:891:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
19 verbose pkgid Ionide-fsharp@2.33.2
20 verbose cwd /Users/danl/proj/ionide-vscode-fsharp/release
21 error Darwin 16.7.0
22 error argv "/nix/store/j3z060vwl83gapvjqpsnmyffhdcjj0ms-nodejs-6.11.1/bin/node" "/Users/danl/.nix-profile/bin/npm" "run" "build"
23 error node v6.11.1
24 error npm  v3.10.10
25 error code ELIFECYCLE
26 error Ionide-fsharp@2.33.2 build: `fable ../src/Ionide.FSharp.fsproj -o ../release -m commonjs --verbose`
26 error Exit status 1
27 error Failed at the Ionide-fsharp@2.33.2 build script 'fable ../src/Ionide.FSharp.fsproj -o ../release -m commonjs --verbose'.
27 error Make sure you have the latest version of node.js and npm installed.
27 error If you do, this is most likely a problem with the Ionide-fsharp package,
27 error not with npm itself.
27 error Tell the author that this fails on your system:
27 error     fable ../src/Ionide.FSharp.fsproj -o ../release -m commonjs --verbose
27 error You can get information on how to open an issue for this project with:
27 error     npm bugs Ionide-fsharp
27 error Or if that isn't available, you can get their info via:
27 error     npm owner ls Ionide-fsharp
27 error There is likely additional logging output above.
28 verbose exit [ 1, true ]
`

Probably something to do with npm/nodejs under nix.

**Comment by Danl2620** [comment]
Ah, yes... updated the comment.

**Comment by Krzysztof-Cieslak** [comment]
I know absolutely nothing about Nix ^_^

**Comment by enricosada** [comment]
@Danl2620 `mono --version`? seems `fable` fails.

can you repro just the `fable` command line to check the fable error? but probably fails the project parsing

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed after we've moved to latest Fable
