### ISSUE TITLE
v2.33.2 – Cannot read property `isEqual` of undefined

### ISSUE THREAD

**Issue by haf** [ionide/ionide-vscode-fsharp#515]
```
TypeError: Cannot read property 'isEqual' of undefined
    at ModeHandler.<anonymous> (/Users/h/.vscode/extensions/vscodevim.vim-0.9.0/out/src/mode/modeHandler.js:500:58)
    at Generator.next (<anonymous>)
    at /Users/h/.vscode/extensions/vscodevim.vim-0.9.0/out/src/mode/modeHandler.js:7:71
    at __awaiter (/Users/h/.vscode/extensions/vscodevim.vim-0.9.0/out/src/mode/modeHandler.js:3:12)
    at ModeHandler.handleSelectionChange (/Users/h/.vscode/extensions/vscodevim.vim-0.9.0/out/src/mode/modeHandler.js:454:16)
    at Object.promise (/Users/h/.vscode/extensions/vscodevim.vim-0.9.0/out/src/mode/modeHandler.js:409:37)
    at TaskQueue.<anonymous> (/Users/h/.vscode/extensions/vscodevim.vim-0.9.0/out/src/taskQueue.js:27:32)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/h/.vscode/extensions/vscodevim.vim-0.9.0/out/src/taskQueue.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

After going through the manual process of downgrading.

No output from the language server window.

**Comment by Krzysztof-Cieslak** [comment]
`.../extensions/vscodevim.vim-0.9.0/...` it looks like a problem in some other extension.

**Comment by haf** [comment]
Ok, true. CLosing.
