### ISSUE TITLE
TypeError: Cannot read property 'document' of null 

### ISSUE THREAD

**Issue by jrieken** [ionide/ionide-vscode-fsharp#52]
our error telemetry reports this

```
TypeError: Cannot read property 'document' of null 
at e.Object.defineProperty.get [as document] (/out/vs/workbench/node/pluginHostProcess.js:19:10563) 
at QuickInfo__handle_$ (/Ionide.Ionide-fsharp-1.6.0/fsharp.js:3185:34) 
at null._onTimeout (/Ionide.Ionide-fsharp-1.6.0/fsharp.js:3180:14) 
at Timer.listOnTimeout (timers.js:89:15) 
```

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in `1.6.1`
