### ISSUE TITLE
TypeError: Cannot read property 'document' of null 

### ISSUE THREAD

**Issue by jrieken** [ionide/ionide-vscode-fsharp#53]
```
TypeError: Cannot read property 'document' of null 
at Linter__handlerOpen$ (/Ionide.Ionide-fsharp-1.6.0/fsharp.js:2046:37) 
at _f (/Ionide.Ionide-fsharp-1.6.0/fsharp.js:1974:14) 
at e.invoke (/out/vs/workbench/node/pluginHostProcess.js:7:14035) 
at e.fire (/out/vs/workbench/node/pluginHostProcess.js:7:15488) 
at e._acceptActiveEditorAndVisibleEditors (/out/vs/workbench/node/pluginHostProcess.js:19:8107) 
at t.e.handle (/out/vs/workbench/node/pluginHostProcess.js:15:12835) 
at c (/out/vs/workbench/node/pluginHostProcess.js:11:16222) 
at h (/out/vs/workbench/node/pluginHostProcess.js:11:16882) 
at doNTCallback0 (node.js:420:9) 
at process._tickCallback (node.js:349:13) 
```

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in `1.6.1`
