### ISSUE TITLE
Cannot read property 'document' of null 

### ISSUE THREAD

**Issue by dbaeumer** [ionide/ionide-vscode-fsharp#54]
Issue Id: b69492db-3cc4-2c53-d056-ead1327be4a4

Versions 
- 1.0.0-insider
-  fa6d0f0 
Stack 
TypeError: Cannot read property 'document' of null
 at e.Object.defineProperty.get as document 
 at QuickInfo__handle_$ (\Ionide.Ionide-fsharp-1.6.0\fsharp.js:3185:34) 
 at null._onTimeout (\Ionide.Ionide-fsharp-1.6.0\fsharp.js:3180:14) 
 at Timer.listOnTimeout (timers.js:89:15)

Reported via VSCode telemetry. See https://github.com/Microsoft/vscode/issues/5480

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in `1.6.1`
