### ISSUE TITLE
Target "Build" fails with "error MSB4057: The target "Restore" does not exist in the project."

### ISSUE THREAD

**Issue by EHotwagner** [ionide/ionide-vscode-fsharp#540]
Since the buildsystem upgraded to dotnetcore compiling every new project with `Fake->Build->Build` fails with:

`System.Exception: dotnet build failed
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1379.Invoke(String message)
   at FSI_0005.Build.runDotnet(String workingDir, String args) in d:\Projects\test\build.fsx:line 40
   at FSI_0005.Build.clo@64-6.Invoke(String p) in d:\Projects\test\build.fsx:line 66
   at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source)
   at FSI_0005.Build.clo@62-5.Invoke(Unit _arg4) in d:\Projects\test\build.fsx:line 64
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in D:\code\FAKE\src\app\FakeLib\TargetHelper.fs:line 626` 

Running `dotnet restore` works but then `dotnet build` fails with: `error MSB6006: "fsc.dll" exited with code -532462766.`

**Comment by Paracelsus77** [comment]
I can't even run dotnet restore on new projects. It seems that something is broken somewhere.

**Comment by EHotwagner** [comment]
This seems to be issue with [forge](https://github.com/fsharp-editing/Forge/issues/87)

**Comment by EHotwagner** [comment]
Is it better to leave this issue open since it affects ionide or closed since it is already documented at the forge repo?

**Comment by Krzysztof-Cieslak** [comment]
Refreshing templates should solve the problem.

**Comment by mastoj** [comment]
how do you refresh templates @Krzysztof-Cieslak ?

**Comment by Krzysztof-Cieslak** [comment]
There is `F#: Refresh Project Templates` command.
