### ISSUE TITLE
Everything is broken after updating to version 3.1.0

### ISSUE THREAD

**Issue by vasily-kirichenko** [ionide/ionide-vscode-fsharp#548]
```
Resolving startup promise because FSAC printed the 'listener started' message
[I] 2017-09-18T10:33:33.4430076Z: listener started in 27.500 ms with binding 127.0.0.1:8895 [Suave.Tcp.tcpIpServer]
Unhandled error - Object reference not set to an instance of an object. 
    at FsAutoComplete.CommandResponse.project(FSharpFunc`2 serialize, String projectFileName, FSharpList`1 projectFiles, FSharpOption`1 outFileOpt, FSharpList`1 references, FSharpMap`2 logMap, ExtraProjectInfoData extra, FSharpMap`2 additionals)
   at <StartupCode$FsAutoComplete-Core>.$Commands.Project@103.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@851.Invoke(AsyncParams`1 args)
Unhandled error - Object reference not set to an instance of an object. 
    at FsAutoComplete.CommandResponse.project(FSharpFunc`2 serialize, String projectFileName, FSharpList`1 projectFiles, FSharpOption`1 outFileOpt, FSharpList`1 references, FSharpMap`2 logMap, ExtraProjectInfoData extra, FSharpMap`2 additionals)
   at <StartupCode$FsAutoComplete-Core>.$Commands.Project@103.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@851.Invoke(AsyncParams`1 args)
Unhandled error - Object reference not set to an instance of an object. 
    at FsAutoComplete.CommandResponse.project(FSharpFunc`2 serialize, String projectFileName, FSharpList`1 projectFiles, FSharpOption`1 outFileOpt, FSharpList`1 references, FSharpMap`2 logMap, ExtraProjectInfoData extra, FSharpMap`2 additionals)
   at <StartupCode$FsAutoComplete-Core>.$Commands.Project@103.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@851.Invoke(AsyncParams`1 args)
Unhandled error - Object reference not set to an instance of an object. 
    at FsAutoComplete.CommandResponse.project(FSharpFunc`2 serialize, String projectFileName, FSharpList`1 projectFiles, FSharpOption`1 outFileOpt, FSharpList`1 references, FSharpMap`2 logMap, ExtraProjectInfoData extra, FSharpMap`2 additionals)
   at <StartupCode$FsAutoComplete-Core>.$Commands.Project@103.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@851.Invoke(AsyncParams`1 args)
Unhandled error - Object reference not set to an instance of an object. 
    at FsAutoComplete.CommandResponse.project(FSharpFunc`2 serialize, String projectFileName, FSharpList`1 projectFiles, FSharpOption`1 outFileOpt, FSharpList`1 references, FSharpMap`2 logMap, ExtraProjectInfoData extra, FSharpMap`2 additionals)
   at <StartupCode$FsAutoComplete-Core>.$Commands.Project@103.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@851.Invoke(AsyncParams`1 args)
Unhandled error - Object reference not set to an instance of an object. 
    at FsAutoComplete.CommandResponse.project(FSharpFunc`2 serialize, String projectFileName, FSharpList`1 projectFiles, FSharpOption`1 outFileOpt, FSharpList`1 references, FSharpMap`2 logMap, ExtraProjectInfoData extra, FSharpMap`2 additionals)
   at <StartupCode$FsAutoComplete-Core>.$Commands.Project@103.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@851.Invoke(AsyncParams`1 args)
Unhandled error - Object reference not set to an instance of an object. 
    at FsAutoComplete.CommandResponse.project(FSharpFunc`2 serialize, String projectFileName, FSharpList`1 projectFiles, FSharpOption`1 outFileOpt, FSharpList`1 references, FSharpMap`2 logMap, ExtraProjectInfoData extra, FSharpMap`2 additionals)
   at <StartupCode$FsAutoComplete-Core>.$Commands.Project@103.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@851.Invoke(AsyncParams`1 args)

...........
```

**Comment by Krzysztof-Cieslak** [comment]
Try running `F#: Clear cache` and then restart editor

**Comment by vasily-kirichenko** [comment]
It's helped, thanks!
