### ISSUE TITLE
Build failure - cannot find yarn.cmd

### ISSUE THREAD

**Issue by lambdakris** [ionide/ionide-vscode-fsharp#559]
I am on Windows 7 and have prereqs listed in [CONTRIBUTING](https://github.com/ionide/ionide-vscode-fsharp/blob/master/CONTRIBUTING.md) installed, including Yarn. (well, .NET Fx instead of Mono)

When I run build.cmd Build, the result is the following:
```
$ ./build.cmd Build

Checking Paket version (downloading latest stable)...
Paket.exe 5.100.2 is up to date.
Paket version 5.100.2
Last restore is still up to date.
Performance:
 - Runtime: 2 seconds
Building project with version: LocalBuild
Shortened DependencyGraph for Target Build:
<== Build
   <== CopySchemas
      <== CopyGrammar
         <== CopyForge
            <== CopyFSAC
               <== RunScript
                  <== Clean
                  <=? YarnInstall
                  <=? DotNetRestore

The running order is:
  - Clean
  - YarnInstall
  - DotNetRestore
  - RunScript
  - CopyFSAC
  - CopyForge
  - CopyGrammar
  - CopySchemas
  - Build
Running build with 1 worker
Starting Target: Clean
Deleting contents of ./temp
Finished Target: Clean
Starting Target: YarnInstall
C:\Users\{omitted}\Code\ionide-vscode-fsharp\packages\Yarnpkg.js\tools\yarn.cmd install
Running build failed.
Error:
System.Exception: Start of process C:\Users\{omitted}\Code\ionide-vscode-fsharp\packages\Yarnpkg.js\tools\yarn.cmd failed. The system cannot find the file specified
   at Fake.ProcessHelper.ExecProcessWithLambdas@103-16.Invoke(String message) in D:\code\FAKE\src\app\FakeLib\ProcessHelper.fs:line 103
   at Fake.ProcessHelper.ExecProcessWithLambdas(FSharpFunc`2 configProcessStartInfoF, TimeSpan timeOut, Boolean silent, FSharpFunc`2 errorF, FSharpFunc`2 messageF) in D:\code\FAKE\src\app\FakeLib\ProcessHelper.fs:line 103
   at Fake.YarnHelper.run(YarnParams yarnParams) in D:\code\FAKE\src\app\FakeLib\YarnHelper.fs:line 84
   at FSI_0005.Build.clo@78-1.Invoke(Unit unitVar0) in C:\Users\{omitted}\Code\ionide-vscode-fsharp\build.fsx:line 79
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in D:\code\FAKE\src\app\FakeLib\TargetHelper.fs:line 626

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target        Duration
------        --------
Clean         00:00:00.0091094
YarnInstall   Failure
Total:        00:00:00.0626963
---------------------------------------------------------------------
Status:       Failure
---------------------------------------------------------------------
---------------------------------------------------------------------
  1) System.Exception: Start of process C:\Users\{omitted}\Code\ionide-vscode-fsharp\packages\Yarnpkg.js\tools\yarn.cmd failed. The system cannot find the file specified
   at Fake.ProcessHelper.ExecProcessWithLambdas@103-16.Invoke(String message) in D:\code\FAKE\src\app\FakeLib\ProcessHelper.fs:line 103
   at Fake.ProcessHelper.ExecProcessWithLambdas(FSharpFunc`2 configProcessStartInfoF, TimeSpan timeOut, Boolean silent, FSharpFunc`2 errorF, FSharpFunc`2 messageF) in D:\code\FAKE\src\app\FakeLib\ProcessHelper.fs:line 103
   at Fake.YarnHelper.run(YarnParams yarnParams) in D:\code\FAKE\src\app\FakeLib\YarnHelper.fs:line 84
   at FSI_0005.Build.clo@78-1.Invoke(Unit unitVar0) in C:\Users\{omitted}\Code\ionide-vscode-fsharp\build.fsx:line 79
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in D:\code\FAKE\src\app\FakeLib\TargetHelper.fs:line 626
---------------------------------------------------------------------

```

**Comment by lambdakris** [comment]
Well, I guess a restart was necessary after installing Yarn. From the error message, it is clear that at first the FAKE Yarn helper was looking under the packages folder, which meant that according to the [source of the helper](https://github.com/fsharp/FAKE/blob/d29d342e7602ea8b1fa252eb78926f284bec6791/src/app/FakeLib/YarnHelper.fs#L10-L18) it was not finding Yarn in the path. However, after some fiddling and finally restarting, Yarn is being found in the path and getting set as the YarnFilePath of the FAKE Yarn helper and the YarnInstall target is running successfully.
