### ISSUE TITLE
F# Languace Service Error

### ISSUE THREAD

**Issue by mraxani** [ionide/ionide-vscode-fsharp#560]
Default installation on a Ubuntu-based system.

**F# Language Service (server)** prints this:
>Resolving startup promise because FSAC printed the 'listener started' message
[I] 2017-09-23T20:09:28.5012480Z: listener started in 67.424 ms with binding 127.0.0.1:8775 [Suave.Tcp.tcpIpServer]
Unhandled error - Value cannot be null.
Parameter name: path 
   at System.IO.DirectoryInfo.CheckPath (System.String path) [0x00003] in <77c9551943624fd18301ba6f78a841e5>:0 
  at System.IO.DirectoryInfo..ctor (System.String path, System.Boolean simpleOriginalPath) [0x00006] in <77c9551943624fd18301ba6f78a841e5>:0 
  at System.IO.DirectoryInfo..ctor (System.String path) [0x00000] in <77c9551943624fd18301ba6f78a841e5>:0 
  at (wrapper remoting-invoke-with-check) System.IO.DirectoryInfo:.ctor (string)
  at FsAutoComplete.WorkspacePeek.peek (System.String rootDir, System.Int32 deep, Microsoft.FSharp.Collections.FSharpList\`1[T] excludedDirs) [0x00001] in <59b91e86b98589b7a7450383861eb959>:0 
  at <StartupCode$FsAutoComplete-Core>.$Commands+WorkspacePeek@404.Invoke (Microsoft.FSharp.Core.Unit unitVar) [0x00001] in <59b91e86b98589b7a7450383861eb959>:0 
  at Microsoft.FSharp.Control.AsyncBuilderImpl+callA@851[b,a].Invoke (Microsoft.FSharp.Control.AsyncParams`1[T] args) [0x00047] in <5584aad2904cf4daa7450383d2aa8455>:0 

While **F# Language Service** prints this:
>[22:09:29 ERROR] Cannot execute declarations, File '/home/user/test/webbrowser.fsx' not parsed 
[22:09:29 ERROR] RES (001) <- {workspacePeek} ERROR in 536 ms: {stack: Error: Request failed with status code 500
	at createError (/home/user/.vscode/extensions/Ionide.ionide-fsharp-3.1.0/fsharp.js:11581:15)
	at settle (/home/user/.vscode/extensions/Ionide.ionide-fsharp-3.1.0/fsharp.js:16206:12)
	at IncomingMessage.handleStreamEnd (/home/user/.vscode/extensions/Ionide.ionide-fsharp-3.1.0/fsharp.js:21948:11)
	at emitNone (events.js:91:20)
	at IncomingMessage.emit (events.js:188:7)
	at endReadableNT (_stream_readable.js:975:12)
	at _combinedTickCallback (internal/process/next_tick.js:80:11)
	at process._tickCallback (internal/process/next_tick.js:104:9), message: Request failed with status code 500, config: [object Object], request: [object Object], response: [object Object]} Data=undefined
[22:09:29 ERROR] Cannot execute lint, File '/home/user/test/webbrowser.fsx' not parsed 
[22:09:40 ERROR] Cannot execute tooltip, File '/home/user/test/webbrowser.fsx' not parsed 
[22:09:46 ERROR] Cannot execute tooltip, File '/home/user/test/webbrowser.fsx' not parsed 

What could be the problem?

**Comment by Krzysztof-Cieslak** [comment]
CC: @enricosada

**Comment by enricosada** [comment]
I'll check. 
Meanwhile you can workaround using `ionideSearch` in settings (see https://github.com/ionide/ionide-vscode-fsharp/wiki/Version-3.0.0#sln-support ) to enable old behaviour

**Comment by enricosada** [comment]
Closing, the workaround should avoid the error.

The fix of this bug is tracked in https://github.com/fsharp/FsAutoComplete/issues/222
