### ISSUE TITLE
Referencing DLL causes terminal to crash

### ISSUE THREAD

**Issue by SoftwareApe** [ionide/ionide-vscode-fsharp#613]
Hi,

I'm having a problem currently with Ionide-fsharp 3.8.2. Everything works fine (intellisense and alt+enter for executing scripts), but as soon as I reference a DLL the terminal crashes with the following error message appearing for half a second:

> \># silentCd @"c:\works
> \- pace\Scripts\AddressCalculator\
> error FS0193: Could not load file or assembly 'Microsoft.Build.Utilities.Core, Version=14.0.0.0, Culture=neutral, Public KeyToken=b03d5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.d
> \- w

Then it dissappears and says Terminal exited with error code 1.

I'm on Windows 7 using F# 4.1 and VSCode 1.17.2. It works when I reference the DLL in a separate FSI.

**Comment by enricosada** [comment]
@SoftwareApe Hi. what version of VS or F# sdk have you installed?

can you check you have the requirements for windows ( https://github.com/ionide/ionide-vscode-fsharp#windows ) ?

**Comment by SoftwareApe** [comment]
@enricosada As I posted above, I'm using VSCode 1.17.2 and F# 4.1. I have installed the MS Build tools.

Also because I can execute this script in fsi.exe and fsiAnyCpu.exe in terminal, I strongly suspect there's something happening on the Ionide side here. The broken error message (line break in the middle of the silentCd command), might be also part of this.

**Comment by richardjharding** [comment]
I'm seeing the same or at least similar issue with fsx files

If I create a new fsx file and start typing say 
```
System. 
```

At the point I type the "." the intellisense kicks in and starts offering suggestions

If however I open another fsx file which has a #r reference to a nuget dll (added via packet) then
when I get as far as typeing "Sy" the intellisense crashes and the code lens decorations disappear

I have single dll ref - from paket

```
source https://www.nuget.org/api/v2
nuget SolidSoils.Arduino.Client
```

typing the following results in the crash

```
#r "packages/SolidSoils.Arduino.Client/lib/net45/Solid.Arduino.dll"

open Solid.Arduino

let conn = SerialConnection.FindSerialConnection()


Sy
```

This is on Win10 with F# 4.1 and dotnet --version reports 2.0.3  with vscode 1.18.1

looks like something causes the lang service to return 500, I've pasted the log from the output window below - are there notes somewhere on how I might go about debugging this?

```
[15:09:41 ERROR] RES (027) <- {completion} ERROR in 1125 ms: {__zone_symbol__error: Error: Request failed with status code 500, stack: Error: Request failed with status code 500
	at AppInsightsAsyncCorrelatedErrorWrapper (C:\Users\richa\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.3.7\node_modules\applicationinsights\out\AutoCollection\CorrelationContextManager.js:172:18)
	at createError (C:\Users\richa\.vscode\extensions\Ionide.ionide-fsharp-3.12.4\fsharp.js:12156:15)
	at settle (C:\Users\richa\.vscode\extensions\Ionide.ionide-fsharp-3.12.4\fsharp.js:16747:12)
	at IncomingMessage.handleStreamEnd (C:\Users\richa\.vscode\extensions\Ionide.ionide-fsharp-3.12.4\fsharp.js:24258:11)
	at ZoneDelegate.invokeTask (C:\Users\richa\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.3.7\node_modules\zone.js\dist\zone-node.js:275:35)
	at Zone.runTask (C:\Users\richa\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.3.7\node_modules\zone.js\dist\zone-node.js:151:47)
	at IncomingMessage.ZoneTask.invoke (C:\Users\richa\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.3.7\node_modules\zone.js\dist\zone-node.js:345:33)
	at emitNone (events.js:91:20)
	at IncomingMessage.emit (events.js:188:7)
	at endReadableNT (_stream_readable.js:975:12)
	at ZoneDelegate.invokeTask (C:\Users\richa\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.3.7\node_modules\zone.js\dist\zone-node.js:275:35)
	at Zone.runTask (C:\Users\richa\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.3.7\node_modules\zone.js\dist\zone-node.js:151:47)
	at ZoneTask.invoke (C:\Users\richa\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.3.7\node_modules\zone.js\dist\zone-node.js:345:33)
	at args.(anonymous function) (C:\Users\richa\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.3.7\node_modules\zone.js\dist\zone-node.js:1497:25)
	at _combinedTickCallback (internal/process/next_tick.js:80:11)
	at process._tickCallback (internal/process/next_tick.js:104:9), name: Error, message: Request failed with status code 500, originalStack: Error: Request failed with status code 500
	at AppInsightsAsyncCorrelatedErrorWrapper (C:\Users\richa\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.3.7\node_modules\applicationinsights\out\AutoCollection\CorrelationContextManager.js:172:18)
	at createError (C:\Users\richa\.vscode\extensions\Ionide.ionide-fsharp-3.12.4\fsharp.js:12156:15)
	at settle (C:\Users\richa\.vscode\extensions\Ionide.ionide-fsharp-3.12.4\fsharp.js:16747:12)
	at IncomingMessage.handleStreamEnd (C:\Users\richa\.vscode\extensions\Ionide.ionide-fsharp-3.12.4\fsharp.js:24258:11)
	at ZoneDelegate.invokeTask (C:\Users\richa\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.3.7\node_modules\zone.js\dist\zone-node.js:275:35)
	at Zone.runTask (C:\Users\richa\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.3.7\node_modules\zone.js\dist\zone-node.js:151:47)
	at IncomingMessage.ZoneTask.invoke (C:\Users\richa\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.3.7\node_modules\zone.js\dist\zone-node.js:345:33)
	at emitNone (events.js:91:20)
	at IncomingMessage.emit (events.js:188:7)
	at endReadableNT (_stream_readable.js:975:12)
	at ZoneDelegate.invokeTask (C:\Users\richa\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.3.7\node_modules\zone.js\dist\zone-node.js:275:35)
	at Zone.runTask (C:\Users\richa\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.3.7\node_modules\zone.js\dist\zone-node.js:151:47)
	at ZoneTask.invoke (C:\Users\richa\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.3.7\node_modules\zone.js\dist\zone-node.js:345:33)
	at args.(anonymous function) (C:\Users\richa\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.3.7\node_modules\zone.js\dist\zone-node.js:1497:25)
	at _combinedTickCallback (internal/process/next_tick.js:80:11)
	at process._tickCallback (internal/process/next_tick.js:104:9), zoneAwareStack: undefined, toString: function () {
                var error = this[__symbol__('error')];
                var errorMethod = (error && error[key]) || this[key];
                if (errorMethod) {
                    return errorMethod.apply(error, arguments);
                }
            }, toSource: function () {
                var error = this[__symbol__('error')];
                var errorMethod = (error && error[key]) || this[key];
                if (errorMethod) {
                    return errorMethod.apply(error, arguments);
                }
            }, __zone_symbol____zone_symbol__error: undefined, __zone_symbol__stack: Error: Request failed with status code 500
	at AppInsightsAsyncCorrelatedErrorWrapper (C:\Users\richa\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.3.7\node_modules\applicationinsights\out\AutoCollection\CorrelationContextManager.js:172:18)
	at createError (C:\Users\richa\.vscode\extensions\Ionide.ionide-fsharp-3.12.4\fsharp.js:12156:15)
	at settle (C:\Users\richa\.vscode\extensions\Ionide.ionide-fsharp-3.12.4\fsharp.js:16747:12)
	at IncomingMessage.handleStreamEnd (C:\Users\richa\.vscode\extensions\Ionide.ionide-fsharp-3.12.4\fsharp.js:24258:11)
	at ZoneDelegate.invokeTask (C:\Users\richa\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.3.7\node_modules\zone.js\dist\zone-node.js:275:35)
	at Zone.runTask (C:\Users\richa\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.3.7\node_modules\zone.js\dist\zone-node.js:151:47)
	at IncomingMessage.ZoneTask.invoke (C:\Users\richa\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.3.7\node_modules\zone.js\dist\zone-node.js:345:33)
	at emitNone (events.js:91:20)
	at IncomingMessage.emit (events.js:188:7)
	at endReadableNT (_stream_readable.js:975:12)
	at ZoneDelegate.invokeTask (C:\Users\richa\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.3.7\node_modules\zone.js\dist\zone-node.js:275:35)
	at Zone.runTask (C:\Users\richa\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.3.7\node_modules\zone.js\dist\zone-node.js:151:47)
	at ZoneTask.invoke (C:\Users\richa\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.3.7\node_modules\zone.js\dist\zone-node.js:345:33)
	at args.(anonymous function) (C:\Users\richa\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.3.7\node_modules\zone.js\dist\zone-node.js:1497:25)
	at _combinedTickCallback (internal/process/next_tick.js:80:11)
	at process._tickCallback (internal/process/next_tick.js:104:9), __zone_symbol__name: Error, __zone_symbol__message: Request failed with status code 500, __zone_symbol__originalStack: Error: Request failed with status code 500
	at AppInsightsAsyncCorrelatedErrorWrapper (C:\Users\richa\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.3.7\node_modules\applicationinsights\out\AutoCollection\CorrelationContextManager.js:172:18)
	at createError (C:\Users\richa\.vscode\extensions\Ionide.ionide-fsharp-3.12.4\fsharp.js:12156:15)
	at settle (C:\Users\richa\.vscode\extensions\Ionide.ionide-fsharp-3.12.4\fsharp.js:16747:12)
	at IncomingMessage.handleStreamEnd (C:\Users\richa\.vscode\extensions\Ionide.ionide-fsharp-3.12.4\fsharp.js:24258:11)
	at ZoneDelegate.invokeTask (C:\Users\richa\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.3.7\node_modules\zone.js\dist\zone-node.js:275:35)
	at Zone.runTask (C:\Users\richa\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.3.7\node_modules\zone.js\dist\zone-node.js:151:47)
	at IncomingMessage.ZoneTask.invoke (C:\Users\richa\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.3.7\node_modules\zone.js\dist\zone-node.js:345:33)
	at emitNone (events.js:91:20)
	at IncomingMessage.emit (events.js:188:7)
	at endReadableNT (_stream_readable.js:975:12)
	at ZoneDelegate.invokeTask (C:\Users\richa\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.3.7\node_modules\zone.js\dist\zone-node.js:275:35)
	at Zone.runTask (C:\Users\richa\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.3.7\node_modules\zone.js\dist\zone-node.js:151:47)
	at ZoneTask.invoke (C:\Users\richa\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.3.7\node_modules\zone.js\dist\zone-node.js:345:33)
	at args.(anonymous function) (C:\Users\richa\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.3.7\node_modules\zone.js\dist\zone-node.js:1497:25)
	at _combinedTickCallback (internal/process/next_tick.js:80:11)
	at process._tickCallback (internal/process/next_tick.js:104:9), __zone_symbol__zoneAwareStack: undefined, __zone_symbol__toString: undefined, __zone_symbol__toSource: undefined, config: [object Object], request: [object Object], response: [object Object]} Data=undefined
```

**Comment by Krzysztof-Cieslak** [comment]
I strongly suspect that it's wrong MsBuild version - Ionide requires MsBuild 14.0 (2015) which is not distributed with VS2017. You can download it from https://www.microsoft.com/en-us/download/details.aspx?id=48159
