### ISSUE TITLE
Use fsharp docker container instead of native mono package

### ISSUE THREAD

**Issue by ideaflare** [ionide/ionide-vscode-fsharp#633]
Is it possible to use the `fsharp docker container` for language services ?

I can get VSCode to call
```
fsautocomplete.exe --mode http --port 8743 --hostPID=1258
```
and the output for F# language service (server) happily prompts:

```
[I] 2017-11-07T20:17:42.3312580Z: tracking host PID 17434 [FsAutoComplete]
Resolving startup promise because FSAC printed the 'listener started' message
[I] 2017-11-07T20:17:42.3772820Z: listener started in 28.742 ms with binding 127.0.0.1:8240 [Suave.Tcp.tcpIpServer]
```

But the output for F# language service has a few of these:

```
[22:13:28 ERROR] RES (005) <- {workspacePeek} ERROR in 7 ms: {stack: Error: socket hang up
	at createHangUpError (_http_client.js:302:15)
	at Socket.socketOnEnd (_http_client.js:394:23)
	at emitNone (events.js:91:20)
	at Socket.emit (events.js:188:7)
	at endReadableNT (_stream_readable.js:975:12)
	at _combinedTickCallback (internal/process/next_tick.js:80:11)
	at process._tickCallback (internal/process/next_tick.js:104:9), message: socket hang up, code: ECONNRESET, config: [object Object], request: [object Object], response: undefined} Data=undefined
```

To get this far, I changed the settings in VSCode to:
```
{
    "FSharp.monoPath": "/home/myName/Code/fs.sh",
    "FSharp.logLanguageServiceRequestsOutputWindowLevel": "DEBUG",
    "FSharp.logLanguageServiceRequests": "both"
}
```

and created the script `/home/myName/Code/fs.sh` (with ```chmod +x fs.sh``` to make it executable)
```
MONO_ARGS="$@"
IONIDE_PATH=$(locate fsautocomplete.exe.config | xargs -r0 dirname)
IONIDE_PORT=$(echo $MONO_ARGS | awk '{print $5}')
docker run --rm --pid=host -p $IONIDE_PORT:$IONIDE_PORT --volume /home/myName/Code:/home/myName/Code --volume $IONIDE_PATH:$IONIDE_PATH fsharp bash -c "mono $MONO_ARGS"
```

**Comment by nojaf** [comment]
Would this be easier with Windows containers? I'd like to give a Fable workshop to my colleagues and provide a docker image that includes all the tools they would need. So that the only thing they would need is VS Code with the ionide extension. Could it be done?
