### ISSUE TITLE
FSharp.Compiler.Service.ProjectCraker has stopped working

### ISSUE THREAD

**Issue by tebeco** [ionide/ionide-vscode-fsharp#634]
Hi,

Since few day i got annoyig crash everytime i open a folder
the folder is a C# repository containing 1 FAKE build in an fsx file
**All csproj are using Msbuild tool v12 and targeting net462**

## Setup
Win10
Vs2017 Entreprise (so net 4.7.1 in installed)
F# SDK 4.1 by default
VsCode  Insiders :
Version 1.19.0-insider
Commit 0fbdfff167653b233231259ceb3109f0931887ef
Date 2017-11-09T08:13:46.054Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Extensions :
Ionide-fsharp 3.12.1
Ionide-fake 1.2.3
C# / Omnisharp 1.13.0

## First (and bad) guess :
(It worked before without the following)
Ionide F# readme tell this :
`F# 4.0 needs to be installed on your system in order to use Ionide`
`Add MSBUILD_PATH environment variable which points to the home of Microsoft Build Tools, e.g., MSBUILD_PATH = C:\Program Files (x86)\MSBuild\14.0\Bin`

* I had 4.1 installed, so i installed side by side the 4.0 ==> Nothing changed
* for MsBuild i have 12.0 and 15.0 and need both of them depending of the project i use ... what should i do ?
and they do not look alike AT ALL what is the good syntax for v15.0 ?
so i did not create this variable ... since i dont really know what value should i use (and it was working with for month without it)

## Abandining the "Fix it yourself" ship

What can i do more that this :

DevExtension log everytime i click "Close the program"
```
console.ts:123 [Extension Host] [IONIDE-FSAC] RES (004) <- {project} in 10984 ms: Kind={"error"}
Data=Object (at writeDevToolsConsole (C:\Users\MY_NAME\.vscode-insiders\extensions\Ionide.ionide-fsharp-3.12.1\fsharp.js:6513:21))
console.ts:123 [Extension Host] [IONIDE-FSAC] Project loading failed, error parsing ProjectCrackerTool output, stdoutput was:



stderr was:

Process is terminated due to StackOverflowException.

  (at writeDevToolsConsole (C:\Users\MY_NAME\.vscode-insiders\extensions\Ionide.ionide-fsharp-3.12.1\fsharp.js:6497:21))
console.ts:123 [Extension Host] [IONIDE-FSAC] REQ (005) -> {project}, File = "~\tests\MY_APP.IntegrationTests\MY_APP.IntegrationTests.csproj"
Data=Object (at writeDevToolsConsole (C:\Users\MY_NAME\.vscode-insiders\extensions\Ionide.ionide-fsharp-3.12.1\fsharp.js:6509:21))
```

Here is a screen of what it looks like
![fsharp](https://user-images.githubusercontent.com/2266487/32601306-7751f6fe-c542-11e7-8631-b863796ed04a.png)

**Comment by tebeco** [comment]
Bonus :

We also have a pure F# project (.fs file + fsproj)
with an fsx hidden in the middle of it <== not sure this is related

the csproj look like this :

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="12.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <SchemaVersion>2.0</SchemaVersion>
    <ProjectGuid>2095e049-62ab-48a6-8ee5-70bc8db7d97f</ProjectGuid>
    <OutputType>Library</OutputType>
    <RootNamespace>COIN_COIN</RootNamespace>
    <AssemblyName>COIN_COIN</AssemblyName>
    <TargetFrameworkVersion>v4.6.2</TargetFrameworkVersion>
    <TargetFSharpCoreVersion>4.3.1.0</TargetFSharpCoreVersion>
    <Name>COIN_COIN</Name>
    <TargetFrameworkProfile />
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <Tailcalls>false</Tailcalls>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>TRACE;DEBUG</DefineConstants>
    <WarningLevel>3</WarningLevel>
    <DocumentationFile>
    </DocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <Tailcalls>true</Tailcalls>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <WarningLevel>3</WarningLevel>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="mscorlib" />
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Numerics" />
    <Reference Include="System.Xml.Linq" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="COIN_COIN.fs" />
    <Compile Include="COIN_COIN.fs" />
    <Compile Include="COIN_COIN.fs" />
    <Compile Include="COIN_COIN.fs" />
    <Compile Include="COIN_COIN.fs" />
    <Compile Include="COIN_COIN.fs" />
    <Compile Include="COIN_COIN.fs" />
    <Compile Include="COIN_COIN.fs" />
    <Compile Include="COIN_COIN.fs" />
    <Compile Include="COIN_COIN.fs" />
    <Compile Include="COIN_COIN.fs" />
    <Compile Include="COIN_COIN.fs" />
    <Compile Include="COIN_COIN.fs" />
    <Compile Include="COIN_COIN.fs" />
    <None Include="paket.references" />
    <None Include="paket.template" />
  </ItemGroup>
  <PropertyGroup>
    <VisualStudioVersion Condition=" '$(VisualStudioVersion)' == '' ">12.0</VisualStudioVersion>
  </PropertyGroup>
  <PropertyGroup>
    <MinimumVisualStudioVersion Condition="'$(MinimumVisualStudioVersion)' == ''">11</MinimumVisualStudioVersion>
  </PropertyGroup>
  <Choose>
    <When Condition="'$(VisualStudioVersion)' == '11.0'">
      <PropertyGroup Condition="Exists('$(MSBuildExtensionsPath32)\..\Microsoft SDKs\F#\3.0\Framework\v4.0\Microsoft.FSharp.Targets')">
        <FSharpTargetsPath>$(MSBuildExtensionsPath32)\..\Microsoft SDKs\F#\3.0\Framework\v4.0\Microsoft.FSharp.Targets</FSharpTargetsPath>
      </PropertyGroup>
    </When>
    <Otherwise>
      <PropertyGroup Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\FSharp\Microsoft.FSharp.Targets')">
        <FSharpTargetsPath>$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\FSharp\Microsoft.FSharp.Targets</FSharpTargetsPath>
      </PropertyGroup>
    </Otherwise>
  </Choose>
  <Import Project="$(FSharpTargetsPath)" />
  <!-- To modify your build process, add your task inside one of the targets below and uncomment it. 
       Other similar extension points exist, see Microsoft.Common.targets.
  <Target Name="BeforeBuild">
  </Target>
  <Target Name="AfterBuild">
  </Target>
  -->
  <Choose>
    <When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And $(TargetFrameworkVersion) == 'v4.6.2'">
      <ItemGroup>
        <Reference Include="FakeLib">
          <HintPath>..\packages\FAKE.Lib.x64\lib\net451\FakeLib.dll</HintPath>
          <Private>True</Private>
          <Paket>True</Paket>
        </Reference>
      </ItemGroup>
    </When>
  </Choose>
  <Choose>
    <When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And $(TargetFrameworkVersion) == 'v4.6.2'">
      <ItemGroup>
        <Reference Include="FSharp.Core">
          <HintPath>..\packages\FSharp.Core\lib\net45\FSharp.Core.dll</HintPath>
          <Private>True</Private>
          <Paket>True</Paket>
        </Reference>
      </ItemGroup>
    </When>
  </Choose>
  <Choose>
    <When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And $(TargetFrameworkVersion) == 'v4.6.2'">
      <ItemGroup>
        <Reference Include="FSharp.Data">
          <HintPath>..\packages\FSharp.Data\lib\net45\FSharp.Data.dll</HintPath>
          <Private>True</Private>
          <Paket>True</Paket>
        </Reference>
      </ItemGroup>
    </When>
  </Choose>
  <Choose>
    <When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And $(TargetFrameworkVersion) == 'v4.6.2'">
      <ItemGroup>
        <Reference Include="Hopac">
          <HintPath>..\packages\Hopac\lib\net45\Hopac.dll</HintPath>
          <Private>True</Private>
          <Paket>True</Paket>
        </Reference>
        <Reference Include="Hopac.Core">
          <HintPath>..\packages\Hopac\lib\net45\Hopac.Core.dll</HintPath>
          <Private>True</Private>
          <Paket>True</Paket>
        </Reference>
        <Reference Include="Hopac.Platform">
          <HintPath>..\packages\Hopac\lib\net45\Hopac.Platform.dll</HintPath>
          <Private>True</Private>
          <Paket>True</Paket>
        </Reference>
      </ItemGroup>
    </When>
  </Choose>
  <Choose>
    <When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And $(TargetFrameworkVersion) == 'v4.6.2'">
      <ItemGroup>
        <Reference Include="HttpFs">
          <HintPath>..\packages\Http.fs\lib\net40\HttpFs.dll</HintPath>
          <Private>True</Private>
          <Paket>True</Paket>
        </Reference>
      </ItemGroup>
    </When>
  </Choose>
  <ItemGroup>
    <Reference Include="Ionic.Zip.Reduced">
      <HintPath>..\packages\xxxx.dll</HintPath>
      <Private>True</Private>
      <Paket>True</Paket>
    </Reference>
.... 10 like this
  </ItemGroup>
</Project>
```

and i also has the project craker crashing

**Comment by enricosada** [comment]
@tebeco can you check if is just projectcracker the problem?
you can run it from command line like https://github.com/fsharp/FsAutoComplete#old-sdk-project-verbose-fsproj

**Comment by enricosada** [comment]
> console.ts:123 [Extension Host] [IONIDE-FSAC] REQ (005) -> {project}, File = "~\tests\MY_APP.IntegrationTests\MY_APP.IntegrationTests.csproj"

so, project cracker shouldnt try to parse csproj. Dunno if is a supported scenario, if not we should just skip csproj in FSAC for projectcracker.

@tebeco as workaround, you can try to change the workspace loading mode:

```json
    "FSharp.workspaceMode": "ionideSearch"
```

so ionide will try to find just fsproj/fsx. You can set that per repo or per user

**Comment by tebeco** [comment]
will try it today or monday (only got the issue at work)

**Comment by tebeco** [comment]
I did not forgot it, i'm trying to find some time to test it

**Comment by tebeco** [comment]
@enricosada 

Still crashing today (Vs-code insider it up to date and Ionide too)

This workaround does the tricks:
` "FSharp.workspaceMode": "ionideSearch"`

Should i permanently use this settings ?
Before having this issue what was the default value of `FSharp.workspaceMode` ? when i had no settings ?
What does it changes ?

**Comment by tebeco** [comment]
Will close the ticket after having the info BTW ^^

**Comment by tebeco** [comment]
@enricosada ?

**Comment by enricosada** [comment]
sorry for late reply @tebeco , thx for ping.

so, yes `"FSharp.workspaceMode": "ionideSearch"` works, because will parse just fsproj.
default was `"FSharp.workspaceMode": "sln",` (you can see that doing `> Preferences: Open User Settings`)
As a note, you @tebeco can set that setting just for that repository, so `Preferences: Open Workspace Settings`, so default remains "sln"


added https://github.com/fsharp/FsAutoComplete/issues/262 to track the csproj crashing FSAC (it should not)

**Comment by enricosada** [comment]
Closing, because a workaround is ready, and there is an issue tracked in FSAC repo

**Comment by axu2** [comment]
I'm still getting this issue even after changing that setting.
I can't even generate a new project without a (not restored) error.

**Comment by tebeco** [comment]
Re-opening
Seems to bug again since few version, tried all settings for "FSharp.workspaceMode"
