### ISSUE TITLE
No intellisense, code lens or completion when script in sub folder

### ISSUE THREAD

**Issue by colinbull** [ionide/ionide-vscode-fsharp#645]
It seems I get completion if a script (*.fsx) file is in the same folder as a *.fsproj project but none if it is in a sub folder. For example in the following solution I have to identical script files `PowerPeriod.fsx` and `NodatTime.fsx` but I only get intellisense in the latter.

![image](https://user-images.githubusercontent.com/585546/32827532-755b895e-c9e4-11e7-996f-5eb19cba6170.png)

Neither script file is added to the project. For the `PowerPeriod.fsx` the Language service logs report `Cached Typecheck result not yet available` 

      [09:08:27 DEBUG] REQ (689) -> {unusedDeclarations}, File ="~\src\ValueAdd\scripts\PowerPeriod.fsx" Data={"FileName":"d:\\Appdev\\ValueAdd\\src\\ValueAdd\\scripts\\PowerPeriod.fsx"}
      [09:08:27 DEBUG] REQ (690) -> {simplifiedNames}, File = "~\src\ValueAdd\scripts\PowerPeriod.fsx" Data={"FileName":"d:\\Appdev\\ValueAdd\\src\\ValueAdd\\scripts\\PowerPeriod.fsx"}
     [09:08:27 DEBUG] RES (687) <- {tooltip} in 15 ms: Kind={"info"} Data="Cached typecheck results not yet available"
     [09:08:27 DEBUG] RES (690) <- {simplifiedNames} in 12 ms: Kind={"info"} Data="Cached typecheck results not yet available"
     [09:08:27 DEBUG] RES (688) <- {unusedOpens} in 13 ms: Kind={"info"} Data="Cached typecheck results not yet available"
     [09:08:27 DEBUG] RES (689) <- {unusedDeclarations} in 13 ms: Kind={"info"} Data="Cached typecheck results not yet available"
     [09:08:28 DEBUG] REQ (691) -> {declarations}, File = "~\src\ValueAdd\scripts\PowerPeriod.fsx" Data={"FileName":"d:\\Appdev\\ValueAdd\\src\\ValueAdd\\scripts\\PowerPeriod.fsx","Lines":["#I \"C:/Users/C24701/.nuget/packages\"\r","#r \"Newtonsoft.Json/lib/net45/Newtonsoft.Json.dll\"\r","#r \"nodatime/2.2.2/lib/net45/NodaTime.dll\"\r","#load \"../Prelude.fs\"\r","\r","open System\r","open System.Globalization\r","open NodaTime\r","open NodaTime.TimeZones\r","\r","let tz =BclDateTimeZone.FromTimeZoneInfo(TimeZoneInfo.Local)\r","tz.\r",""],"Version":60}
     [09:08:28 DEBUG] RES (691) <- {declarations} in 6 ms: Kind={"declarations"} Data=[{"Declaration"{"UniqueName":"PowerPeriod_1_of_1","Name":"PowerPeriod","Glyph":"Module","GlyphChar":"N","IsTop evel":true,"Range":{"StartColumn":1,"StartLine":1,"EndColumn":1,"EndLine":13},"BodyRange":{"StartColumn":1,"StartLine":1,"EndColumn":62,"EndLine":11},"File":"d:\\Appdev\\ValueAdd\\src\\ValueAdd\\scripts\\PowerPeriod.fsx","EnclosingEntity":"M","IsAbstract":false},"Nested":[{"UniqueName":"PowerPeriod_1_of_1","Name":"tz","Glyph":"Field","GlyphChar":"F","IsTopLevel":false,"Range":{"StartColumn":5,"StartLine":11,"EndColumn":62,"EndLine":11},"BodyRange":{"StartColumn":5,"StartLine":11,"EndColumn":62,"EndLine":11},"File":"d:\\Appdev\\ValueAdd\\src\\ValueAdd\\scripts\\PowerPeriod.fsx","EnclosingEntity":"M","IsAbstract":false}]}]
     [09:08:28 DEBUG] REQ (692) -> {signatureData}, File = "~\src\ValueAdd\scripts\PowerPeriod.fsx" Data={"FileName":"d:\\Appdev\\ValueAdd\\src\\ValueAdd\\scripts\\PowerPeriod.fsx","Line":11,"Column":5,"Filter":""}
      [09:08:28 DEBUG] RES (692) <- {signatureData} in 7 ms: Kind={"info"} Data="Cached typecheck results not yet available"

Apologies if this is a known issue but I had a quick look and could find anything.

I can share the project via e-mail if it helps. 

**Version**
VS Code: 1.18.0
Ionide FSharp: 3.12.2

**Comment by Krzysztof-Cieslak** [comment]
Hmm... I can't reproduce, can you try the latest update? Maybe we've accidentally fixed that.

**Comment by colinbull** [comment]
Closing this issue as it appears that using Postman with the Interceptor turned on prevented the communication between ionide and fsautocomplete.

**Comment by colinbull** [comment]
If it is any additional help, this is the server side error that is captured. 

    [I] 2017-11-17T14:28:06.3495356Z: listener started in 24.000 ms with binding 127.0.0.1:8746 [Suave.Tcp.tcpIpServer] Unhandled error - Index was outside the bounds of the array. 
    at <StartupCode$FsAutoComplete-Core>.$Commands.getLine@348.Invoke(Int32 i)
     at FsAutoComplete.UnopenedNamespacesResolver.ParsedInput.adjustInsertionPoint(FSharpFunc`2 getLineStr, InsertContext ctx)
      at FsAutoComplete.UnopenedNamespacesResolver.ParsedInput.tryFindNearestPointToInsertOpenDeclaration(Int32 currentLine, ParsedInput ast, String[] entity, OpenStatementInsertionPoint insertionPoint, FSharpFunc`2 getLine)
       at <StartupCode$FsAutoComplete-Core>.$Commands.clo@100-19.Invoke(ParsedInput ast)
       at <StartupCode$FsAutoComplete-Core>.$Commands.clo@98-17.Invoke(String n)
       at <StartupCode$FsAutoComplete-Core>.$Commands.Completion@344-1.Invoke(FSharpOption`1 _arg13)
       at Microsoft.FSharp.Control.AsyncBuilderImpl.args@835-1.Invoke(a a) Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
        at <StartupCode$FsAutoComplete-Core>.$Commands.getLine@348.Invoke(Int32 i)
        at FsAutoComplete.UnopenedNamespacesResolver.ParsedInput.adjustInsertionPoint(FSharpFunc`2 getLineStr, InsertContext ctx)
        at FsAutoComplete.UnopenedNamespacesResolver.ParsedInput.tryFindNearestPointToInsertOpenDeclaration(Int32 currentLine, ParsedInput ast, String[] entity, OpenStatementInsertionPoint insertionPoint, FSharpFunc`2 getLine)
       at <StartupCode$FsAutoComplete-Core>.$Commands.clo@100-19.Invoke(ParsedInput ast)
       at <StartupCode$FsAutoComplete-Core>.$Commands.clo@98-17.Invoke(String n)
       at <StartupCode$FsAutoComplete-Core>.$Commands.clo@112-21.Invoke(FSharpDeclarationListItem _arg3)
        at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@851.Invoke(AsyncParams`1 args)
     --- End of stack trace from previous location where exception was thrown ---
        at Microsoft.FSharp.Control.CancellationTokenOps.Start@1268-1.Invoke(ExceptionDispatchInfo edi)
        at <StartupCode$FSharp-Core>.$Control.loop@430-54(Trampoline this, FSharpFunc`2 action)
        at Microsoft.FSharp.Control.Trampoline.ExecuteAction(FSharpFunc`2 firstAction)
        at <StartupCode$FSharp-Core>.$Control.-ctor@516-1.Invoke(Object state)
        at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
        at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
        at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
        at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by psmolkin** [comment]
same problem.
Not sure to how reproduce иut at me it turned out as follows:
- Create two files: Main.fsx, Other.fsx (blank)
-  Main.fsx code:
```
#load "./Other.fsx"

open System

```
After some actions with intellisense it dropped.
Output "F# Language Service"

```
[17:44:30 ERROR] RES (352) <- {parse} ERROR in 1014 ms: {stack: Error: connect ECONNREFUSED 127.0.0.1:8616
	at Object.exports._errnoException (util.js:1050:11)
	at exports._exceptionWithHostPort (util.js:1073:20)
	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14), message: connect ECONNREFUSED 127.0.0.1:8616, code: ECONNREFUSED, errno: ECONNREFUSED, syscall: connect, address: 127.0.0.1, port: 8616, config: [object Object], request: [object Object], response: undefined} Data=undefined
```

**Comment by Krzysztof-Cieslak** [comment]
@colinbull, great, that's helpful, indeed

**Comment by colinbull** [comment]
@psmolkin, make sure you don’t have any proxies like Postman Interceptor or fiddler running or restrict the ports they are listening on as I have found this can cause a very similar error to the one you are seeing.

**Comment by Krzysztof-Cieslak** [comment]
@colinbull , can you try `3.12.5`?

**Comment by colinbull** [comment]
Cool, will try on Monday. Thanks.

**Comment by Krzysztof-Cieslak** [comment]
@colinbull, Not promising anything, can't reproduce so just trying to randomly add `try...with`s ;-)

**Comment by psmolkin** [comment]
@Krzysztof-Cieslak fixed for me, thanks

**Comment by 2moveit** [comment]
Sounds related to this issue https://github.com/ionide/ionide-vscode-fsharp/issues/570
I just tested the it with 3.12.5. Unfortunatly the issue still exists.

**Comment by colinbull** [comment]
Ok, this seems to have fixed the immediate issue, but I can confirm that indeed #570 still exists and I can break the intellense and code lens if you use anything in the `#load` directive other than the a single file name. 

For example 

     #load @"D:\Appdev\foo\bar\FileSystem.fs" //breaks
     #load @"D:/Appdev/foo/bar/FileSystem.fs" //breaks
     #load "./FileSystem.fs" //breaks
     #load "FileSystem.fs" //Works fine as long as the script is at the same level 

I think I'll close this issue and keep an eye on #570 as @2moveit points out it seems to be the same issue.
