### ISSUE TITLE
Unable to build because yarn install fails

### ISSUE THREAD

**Issue by akbcode** [ionide/ionide-vscode-fsharp#831]
I am trying to build this on macOS 10.13. I cloned the repo and ran `yarn install`. I get the following error

```
warning Error running install script for optional dependency: "/Users/a/Projects/ionide-vscode-fsharp/node_modules/fsevents: Command failed.
Exit code: 1
Command: node install
Arguments:
Directory: /Users/a/Projects/ionide-vscode-fsharp/node_modules/fsevents
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.36
node-pre-gyp info using node@10.2.1 | darwin | x64
node-pre-gyp info check checked for \"/Users/a/Projects/ionide-vscode-fsharp/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node\" (not found)
node-pre-gyp http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v64-darwin-x64.tar.gz
node-pre-gyp http 404 https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.2 and node@10.2.1 (node-v64 ABI) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(undefined): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.2 and node@10.2.1 (node-v64 ABI) (falling back to source compile with node-gyp)
node-pre-gyp http Connection closed while downloading tarball file
gypgyp  infoinfo  it worked if it ends withit worked if it ends with ok
 ok
gypgyp  infoinfo  usingusing node-gyp@3.6.2
 node-gyp@3.6.2
gypgyp  infoinfo  usingusing node@10.2.1 | darwin | x64
 node@10.2.1 | darwin | x64
gypgyp  infoinfo  okok

gypgyp  infoinfo  it worked if it ends withit worked if it ends with ok
 ok
gyp info usinggyp node-gyp@3.6.2
gyp  infoinfo  usingusing node@10.2.1 | darwin | x64
 node-gyp@3.6.2
gyp info using node@10.2.1 | darwin | x64
gypgyp  infoinfo  spawnspawn /usr/local/bin/python2
 /usr/local/bin/python2
gypgyp  infoinfo  spawn argsspawn args [ '/usr/local/Cellar/node/10.2.1/libexec/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
 [ '/usr/local/Cellar/node/10.2.1/libexec/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gypgyp  infoinfo  spawn argsspawn args   'binding.gyp',
   'binding.gyp',
gypgyp  infoinfo  spawn argsspawn args   '-f',
   '-f',
gypgyp  infoinfo  spawn argsspawn args   'make',
   'make',
gypgyp  infoinfo  spawn argsspawn args   '-I',
   '-I',
gypgyp  infoinfo  spawn argsspawn args   '/Users/a/Projects/ionide-vscode-fsharp/node_modules/fsevents/build/config.gypi',
   '/Users/a/Projects/ionide-vscode-fsharp/node_modules/fsevents/build/config.gypi',
gypgyp  infoinfo  spawn argsspawn args   '-I',
   '-I',
gypgyp  infoinfo  spawn argsspawn args   '/usr/local/Cellar/node/10.2.1/libexec/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info    '/usr/local/Cellar/node/10.2.1/libexec/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
spawn args   '-I',
gypgyp  info infospawn args    '/Users/a/.node-gyp/10.2.1/include/node/common.gypi',
spawn argsgyp   '-I',
 gypinfo  infospawn args    '-Dlibrary=shared_library',
gypspawn args    '/Users/a/.node-gyp/10.2.1/include/node/common.gypi',
infogyp  spawn argsinfo   '-Dvisibility=default',
 gypspawn args    '-Dlibrary=shared_library',
infogyp  spawn argsinfo   '-Dnode_root_dir=/Users/a/.node-gyp/10.2.1',
 gypspawn args    '-Dvisibility=default',
infogyp  spawn argsinfo   '-Dnode_gyp_dir=/usr/local/Cellar/node/10.2.1/libexec/lib/node_modules/npm/node_modules/node-gyp',
 gypspawn args    '-Dnode_root_dir=/Users/a/.node-gyp/10.2.1',
infogyp  spawn argsinfo   '-Dnode_lib_file=/Users/a/.node-gyp/10.2.1/<(target_arch)/node.lib',
 gypspawn args    '-Dnode_gyp_dir=/usr/local/Cellar/node/10.2.1/libexec/lib/node_modules/npm/node_modules/node-gyp',
infogyp  spawn argsinfo   '-Dmodule_root_dir=/Users/a/Projects/ionide-vscode-fsharp/node_modules/fsevents',
 gypspawn args    '-Dnode_lib_file=/Users/a/.node-gyp/10.2.1/<(target_arch)/node.lib',
info gyp spawn argsinfo   '-Dnode_engine=v8',
 gypspawn args    '-Dmodule_root_dir=/Users/a/Projects/ionide-vscode-fsharp/node_modules/fsevents',
infogyp  spawn argsinfo   '--depth=.',
 gypspawn args    '-Dnode_engine=v8',
infogyp  spawn argsinfo   '--no-parallel',
 gyp spawn argsinfo   '--depth=.',
 gypspawn args    '--generator-output',
infogyp  spawn argsinfo   '--no-parallel',
 gypspawn args    'build',
infogyp  spawn argsinfo   '--generator-output',
 gypspawn args    '-Goutput_dir=.' ]
info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gypgyp  infoinfo  okok

gyp info it worked if it ends with ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@10.2.1 | darwin | x64
gyp info using node-gyp@3.6.2
gyp info using node@10.2.1 | darwin | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h:192:
../../nan/nan_maybe_43_inl.h:112:15: errorIn file included from ../fsevents.cc: :6:
In file included from no member named 'ForceSet' in 'v8::Object'../../nan/nan.h
:192:
../../nan/nan_maybe_43_inl.h:112:15: error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
         ~~~  ^
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
         ~~~  ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:834:18: In file included from ../fsevents.cc:warning: 6'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
:
../../nan/nan.h:834:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]    return node::MakeCallback(

                 ^
    return node::MakeCallback(
                 ^
/Users/a/.node-gyp/10.2.1/include/node/node.h:171:1:/Users/a/.node-gyp/10.2.1/include/node/node.h: 171note:: 1'MakeCallback' has been explicitly marked deprecated here
: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED(\"Use MakeCallback(..., async_context)\",
^
NODE_DEPRECATED(\"Use MakeCallback(..., async_context)\",
/Users/a/.node-gyp/10.2.1/include/node/node.h^:
88:20: note/Users/a/.node-gyp/10.2.1/include/node/node.h: :88:expanded from macro 'NODE_DEPRECATED'20
: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:In file included from ../fsevents.cc:6:
../../nan/nan.h:849:18: warning: 849:18:'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
 warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/a/.node-gyp/10.2.1/include/node/node.h:    return node::MakeCallback(164
:                 ^
1: note/Users/a/.node-gyp/10.2.1/include/node/node.h:164: :'MakeCallback' has been explicitly marked deprecated here
1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED(\"Use MakeCallback(..., async_context)\",
^
/Users/a/.node-gyp/10.2.1/include/node/node.hNODE_DEPRECATED(\"Use MakeCallback(..., async_context)\",:88
:^20
: note: /Users/a/.node-gyp/10.2.1/include/node/node.hexpanded from macro 'NODE_DEPRECATED':
88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:864:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
In file included from ../fsevents.cc    return node::MakeCallback(:
6:
                 ^../../nan/nan.h
:864:18:/Users/a/.node-gyp/10.2.1/include/node/node.h :warning157:1: note: : 'MakeCallback' has been explicitly marked deprecated here
'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(NODE_DEPRECATED(\"Use MakeCallback(..., async_context)\",

^                 ^

/Users/a/.node-gyp/10.2.1/include/node/node.h:/Users/a/.node-gyp/10.2.1/include/node/node.h88::15720::1 :note : noteexpanded from macro 'NODE_DEPRECATED':
'MakeCallback' has been explicitly marked deprecated here
    __attribute__((deprecated(message))) declarator
                   ^NODE_DEPRECATED(\"Use MakeCallback(..., async_context)\",

^
/Users/a/.node-gyp/10.2.1/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:1473:31: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return scope.Escape(node::MakeCallback(
                              ^
/Users/a/.node-gyp/10.2.1/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
In file included from ../fsevents.cc:6:
../../nan/nan.h:1473:31: NODE_DEPRECATED(\"Use MakeCallback(..., async_context)\",
^
warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
/Users/a/.node-gyp/10.2.1/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    return scope.Escape(node::MakeCallback(
                              ^
/Users/a/.node-gyp/10.2.1/include/node/node.h:171    __attribute__((deprecated(message))) declarator:
1                   ^:
 note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED(\"Use MakeCallback(..., async_context)\",
^
/Users/a/.node-gyp/10.2.1/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
4 warnings and 1 error generated.
4 warnings and 1 error generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gypgyp  ERR!ERR!  build errorbuild error

gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/node/10.2.1/libexec/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! gypstack     at ChildProcess.emit (events.js:182:13)
 gypERR!  ERR!stack stack Error: `make` failed with exit code: 2
     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/node/10.2.1/libexec/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 17.5.0
gyp gypERR!  ERR!command System Darwin 17.5.0
 \"/usr/local/Cellar/node/10.2.1/bin/node\" \"/usr/local/Cellar/node/10.2.1/libexec/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"build\" \"--fallback-to-build\" \"--module=/Users/a/Projects/ionide-vscode-fsharp/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node\" \"--module_name=fse\" \"--module_path=/Users/a/Projects/ionide-vscode-fsharp/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64\"
gyp ERR! cwdgyp /Users/a/Projects/ionide-vscode-fsharp/node_modules/fsevents
 gyp ERR!ERR!  commandnode -v v10.2.1
 \"/usr/local/Cellar/node/10.2.1/bin/node\" \"/usr/local/Cellar/node/10.2.1/libexec/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"build\" \"--fallback-to-build\" \"--module=/Users/a/Projects/ionide-vscode-fsharp/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node\" \"--module_name=fse\" \"--module_path=/Users/a/Projects/ionide-vscode-fsharp/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64\"
gyp ERR!gyp  node-gyp -vERR! v3.6.2
 gypcwd  /Users/a/Projects/ionide-vscode-fsharp/node_modules/fsevents
ERR!gyp  not okERR!
 node -v v10.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp build --fallback-to-build --module=/Users/a/Projects/ionide-vscode-fsharp/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/a/Projects/ionide-vscode-fsharp/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/a/Projects/ionide-vscode-fsharp/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
node-pre-gyp ERR! System Darwin 17.5.0
node-pre-gyp ERR! command \"/usr/local/Cellar/node/10.2.1/bin/node\" \"/Users/a/Projects/ionide-vscode-fsharp/node_modules/fsevents/node_modules/.bin/node-pre-gyp\" \"install\" \"--fallback-to-build\"
node-pre-gyp ERR! cwd /Users/a/Projects/ionide-vscode-fsharp/node_modules/fsevents
node-pre-gyp ERR! node -v v10.2.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok
success Saved lockfile.
✨  Done in 8.19s.
```

**Comment by techfano** [comment]
solo borrar yarn.lock

rm yarn.lock
