### ISSUE TITLE
Plugin crashes and can no longer find dependencies

### ISSUE THREAD

**Issue by peterzeller** [ionide/ionide-vscode-fsharp#896]
Just started using the plugin for mode than a single-file project. I have a very simple project with an `.fsproj` file. The only dependency is Avalonia.

Around every 5 minutes the plugin crashes and a lot of errors are shown. In particular it can suddenly no longer find the dependencies.

Currently I cannot say what triggers the problem. It seems to happen when I do two things at the same time, e.g. safe a file and hover my mouse over an identifier to see the type. Please let me know if I can somehow collect more information.

Here is the log (with shortened file paths):

```
[15:48:38 INFO ] Logging to output at level INFO. If you want detailed messages, try level DEBUG.
[15:48:40 INFO ] listening notification on /notify started
[15:48:40 INFO ] listening notification on /notifyWorkspace started
[15:48:40 ERROR] Cannot execute unusedDeclarations, File '.../Blub.fs' not parsed 
[15:48:40 ERROR] Cannot execute lint, File '.../Blub.fs' not parsed 
[15:48:40 ERROR] Cannot execute unusedOpens, File '.../Blub.fs' not parsed 
[15:48:40 ERROR] Cannot execute simplifiedNames, File '.../Blub.fs' not parsed 
[15:54:44 ERROR] Cannot execute methods, Could not find ident at this location 
[15:56:33 ERROR] Cannot execute finddeclaration, Could not find ident at this location 
[15:57:10 ERROR] Cannot execute finddeclaration, Could not find declaration 
[15:57:10 ERROR] Cannot execute finddeclaration, Could not find declaration 
[15:59:37 ERROR] Cannot execute helptext, No help text available for symbol 'member' 
[15:59:39 ERROR] RES (600) <- {completion} ERROR in 46 ms: {"{}"}, Data=undefined
[15:59:55 ERROR] Cannot execute finddeclaration, Could not find declaration 
[16:01:31 ERROR] Cannot execute namespaces, Position is out of range 
[16:01:31 ERROR] Cannot execute namespaces, Position is out of range 
[16:01:32 ERROR] Cannot execute namespaces, Position is out of range 
[16:01:32 ERROR] Cannot execute namespaces, Position is out of range 
[16:01:33 ERROR] RES (928) <- {completion} ERROR in 17 ms: {"{}"}, Data=undefined
[16:01:37 ERROR] Cannot execute namespaces, Position is out of range 
[16:01:37 ERROR] Cannot execute namespaces, Position is out of range 
[16:01:38 ERROR] Cannot execute namespaces, Position is out of range 
[16:01:38 ERROR] Cannot execute namespaces, Position is out of range 
[16:01:39 ERROR] Cannot execute namespaces, Position is out of range 
[16:01:40 ERROR] Cannot execute namespaces, Position is out of range 
[16:01:40 ERROR] Cannot execute namespaces, Position is out of range 
[16:01:41 ERROR] Cannot execute namespaces, Position is out of range 
[16:01:41 ERROR] Cannot execute namespaces, Position is out of range 
[16:01:42 ERROR] Cannot execute namespaces, Position is out of range 
[16:01:42 ERROR] Cannot execute namespaces, Position is out of range 
[16:02:35 ERROR] RES (1222) <- {finddeclaration} ERROR in 1049 ms: {stack: Error: socket hang up
	at createHangUpError (_http_client.js:331:15)
	at Socket.socketOnEnd (_http_client.js:423:23)
	at emitNone (events.js:111:20)
	at Socket.emit (events.js:208:7)
	at endReadableNT (_stream_readable.js:1056:12)
	at _combinedTickCallback (internal/process/next_tick.js:138:11)
	at process._tickCallback (internal/process/next_tick.js:180:9), message: socket hang up, code: ECONNRESET, config: [object Object], request: [object Object], response: undefined} Data=undefined
[16:02:35 INFO ] FSAC killed by outside event, restarting
[16:02:35 ERROR] RES (1224) <- {finddeclaration} ERROR in 2 ms: {stack: Error: connect ECONNREFUSED 127.0.0.1:8844
	at Object._errnoException (util.js:1024:11)
	at _exceptionWithHostPort (util.js:1046:20)
	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14), message: connect ECONNREFUSED 127.0.0.1:8844, code: ECONNREFUSED, errno: ECONNREFUSED, syscall: connect, address: 127.0.0.1, port: 8844, config: [object Object], request: [object Object], response: undefined} Data=undefined
[16:02:36 ERROR] RES (1225) <- {parse} ERROR in 1 ms: {stack: Error: connect ECONNREFUSED 127.0.0.1:8844
	at Object._errnoException (util.js:1024:11)
	at _exceptionWithHostPort (util.js:1046:20)
	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14), message: connect ECONNREFUSED 127.0.0.1:8844, code: ECONNREFUSED, errno: ECONNREFUSED, syscall: connect, address: 127.0.0.1, port: 8844, config: [object Object], request: [object Object], response: undefined} Data=undefined
[16:02:36 ERROR] RES (1226) <- {parse} ERROR in 2 ms: {stack: Error: connect ECONNREFUSED 127.0.0.1:8844
	at Object._errnoException (util.js:1024:11)
	at _exceptionWithHostPort (util.js:1046:20)
	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14), message: connect ECONNREFUSED 127.0.0.1:8844, code: ECONNREFUSED, errno: ECONNREFUSED, syscall: connect, address: 127.0.0.1, port: 8844, config: [object Object], request: [object Object], response: undefined} Data=undefined
[16:02:36 ERROR] Cannot execute finddeclaration, File '.../Blub.fs' not parsed 
[16:02:36 ERROR] Cannot execute signature, File '.../Blub.fs' not parsed 
[16:02:36 ERROR] Cannot execute recordStubGenerator, File '.../Blub.fs' not parsed 
[16:02:36 ERROR] Cannot execute finddeclaration, File '.../Blub.fs' not parsed 
[16:02:37 ERROR] Cannot execute tooltip, File '.../Blub.fs' not parsed 
[16:02:37 ERROR] Cannot execute finddeclaration, File '.../Blub.fs' not parsed 
[16:02:37 ERROR] Cannot execute finddeclaration, File '.../Blub.fs' not parsed 
[16:02:37 ERROR] Cannot execute signature, File '.../Blub.fs' not parsed 
[16:02:37 ERROR] Cannot execute recordStubGenerator, File '.../Blub.fs' not parsed 
[16:02:38 ERROR] Cannot execute tooltip, File '.../Blub.fs' not parsed 
[16:02:40 ERROR] Cannot execute finddeclaration, File '.../Blub.fs' not parsed 
[16:02:40 ERROR] Cannot execute finddeclaration, File '.../Blub.fs' not parsed 
[16:02:40 ERROR] Cannot execute tooltip, File '.../Blub.fs' not parsed 
[16:02:42 ERROR] Cannot execute finddeclaration, File '.../Blub.fs' not parsed
[16:02:42 ERROR] Cannot execute finddeclaration, File '.../Blub.fs' not parsed 
[16:02:43 ERROR] Cannot execute symboluse, File '.../Blub.fs' not parsed 
[16:02:43 ERROR] Cannot execute finddeclaration, File '.../Blub.fs' not parsed 
[16:02:43 ERROR] Cannot execute finddeclaration, File '.../Blub.fs' not parsed 
[16:02:43 ERROR] Cannot execute signature, File '.../Blub.fs' not parsed 
[16:02:43 ERROR] Cannot execute recordStubGenerator, File '.../Blub.fs' not parsed 
[16:02:45 ERROR] Cannot execute tooltip, File '.../Blub.fs' not parsed 
[16:02:46 ERROR] Cannot execute tooltip, File '.../Blub.fs' not parsed 
[16:02:48 ERROR] Cannot execute symboluse, File '.../Blub.fs' not parsed 
[16:02:49 ERROR] Cannot execute signature, File '.../Blub.fs' not parsed 
[16:02:49 ERROR] Cannot execute recordStubGenerator, File '.../Blub.fs' not parsed 
```

Versions: Ionide-fsharp version `3.25.3`, Ubuntu 16.04, dotnet `2.1.401`, mono `5.14.0.177`, fsharpc `4.1`.

**Comment by peterzeller** [comment]
I have now enabled logging in the user settings and with logging it seems to happen less often. Here is an extended log: [plugin.log](https://github.com/ionide/ionide-vscode-fsharp/files/2327649/plugin.log)

Errors start in line 281.

**Comment by peterzeller** [comment]
I tried clearing the cache and removing the obj folder, but the bug still occurs. Is there anything I can do to collect more information so that this problem can be fixed?

**Comment by peterzeller** [comment]
This time it wrote something to the `F# Language Service (server)` log, which might be helpful:
[ionide.log](https://github.com/ionide/ionide-vscode-fsharp/files/2360367/ionide.log)

**Comment by Krzysztof-Cieslak** [comment]
This is probably outdated due to Ionide 4.0 changes
