### ISSUE TITLE
MSBuild Stacktrace on load

### ISSUE THREAD

**Issue by abk-x** [ionide/ionide-vscode-fsharp#962]
When loading projects via ionide, I get the following error, which seems to come from FSAC. 

```
[10:42:50 DEBUG] RES (005) <- {parse} in 191 ms: Kind={"info"}
Data="Request cancelled (exn was System.Exception: MSBuild failed with exitCode 1 Working Directory: '/tmp/tmp2DTMZ4.tmp' Exe Path: 'msbuild' Args: '/tmp/tmp2DTMZ4.tmp/EnvironmentInfo.proj /t:_Inspect_GetProperties /p:_Inspect_GetProperties_OutFile=/tmp/tmpuvdfQZ.tmp.GetProperties.txt /p:CustomAfterMicrosoftCommonTargets=/tmp/tmpEkNZGU.tmp.proj-info.oldsdk-hook.targets /nologo /verbosity:quiet'
Log: 
writing helper target file in '/tmp/tmpEkNZGU.tmp.proj-info.oldsdk-hook.targets'

MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
File name: 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
  at Microsoft.Build.Shared.BuildEnvironmentHelper.get_Instance () [0x00017] in <5effe64a82764e3e8ea68a6e16968fe3>:0 
  at Microsoft.Build.Utilities.Traits.get_Instance () [0x00000] in <5effe64a82764e3e8ea68a6e16968fe3>:0 
  at Microsoft.Build.CommandLine.MSBuildApp.Execute (System.String commandLine) [0x003f2] in <5effe64a82764e3e8ea68a6e16968fe3>:0 
  at Microsoft.Build.CommandLine.MSBuildApp.Main () [0x00028] in <5effe64a82764e3e8ea68a6e16968fe3>:0 
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
File name: 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
  at Microsoft.Build.Shared.BuildEnvironmentHelper.get_Instance () [0x00017] in <5effe64a82764e3e8ea68a6e16968fe3>:0 
  at Microsoft.Build.Utilities.Traits.get_Instance () [0x00000] in <5effe64a82764e3e8ea68a6e16968fe3>:0 
  at Microsoft.Build.CommandLine.MSBuildApp.Execute (System.String commandLine) [0x000bb] in <5effe64a82764e3e8ea68a6e16968fe3>:0 

[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
File name: 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
  at Microsoft.Build.Shared.BuildEnvironmentHelper.get_Instance () [0x00017] in <5effe64a82764e3e8ea68a6e16968fe3>:0 
  at Microsoft.Build.Utilities.Traits.get_Instance () [0x00000] in <5effe64a82764e3e8ea68a6e16968fe3>:0 
  at Microsoft.Build.CommandLine.MSBuildApp.Execute (System.String commandLine) [0x003f2] in <5effe64a82764e3e8ea68a6e16968fe3>:0 
  at Microsoft.Build.CommandLine.MSBuildApp.Main () [0x00028] in <5effe64a82764e3e8ea68a6e16968fe3>:0 

   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1645.Invoke(String message)
   at FsAutoComplete.NETFrameworkInfoProvider.getInstalledNETVersions() in D:\\Programowanie\\ionide\\paket-files\\github.com\\fsharp\\FsAutoComplete\\src\\FsAutoComplete.Core\
ETFrameworkInfoProvider.fs:line 90
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at FsAutoComplete.Environment.netReferecesAssembliesTFMLatest() in D:\\Programowanie\\ionide\\paket-files\\github.com\\fsharp\\FsAutoComplete\\src\\FsAutoComplete.Core\\Environment.fs:line 144
   at <StartupCode$FsAutoComplete-Core>.$CompilerServiceInterface.GetProjectOptionsFromScript@510.Invoke(Unit unitVar) in D:\\Programowanie\\ionide\\paket-files\\github.com\\fsharp\\FsAutoComplete\\src\\FsAutoComplete.Core\\CompilerServiceInterface.fs:line 510
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction))"
```

## Additional:
 I do not have any oldsdk style targets, I am using netcore fsacRuntime, I am using vscode 1.29.0 with ionide 3.29.0

## dotnet info:

```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.403
 Commit:    04e15494b6

Runtime Environment:
 OS Name:     debian
 OS Version:  
 OS Platform: Linux
 RID:         debian-x64
 Base Path:   /home/user/.dotnet/sdk/2.1.403/
```

**Comment by abk-x** [comment]
It seems this error goes away on debian when you install `mono-complete`, it appears having just `mono` and `msbuild` is not enough.
